---
permalink: sm-storage/add-to-workload.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add workload, volume 
summary: Você pode adicionar um ou mais volumes a um workload novo ou existente para volumes que não estão associados atualmente a um workload. 
---
= Adicionar volumes a uma carga de trabalho no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar um ou mais volumes a um workload novo ou existente para volumes que não estão associados atualmente a um workload.

.Sobre esta tarefa
Os volumes não são associados a uma carga de trabalho se tiverem sido criados usando a interface de linha de comando (CLI) ou se tiverem sido migrados (importados/exportados) de um storage array diferente.

.Passos
. No painel esquerdo, selecione menu:Storage[Volumes].
. Selecione o menu:ellipsis icon[Add volumes to workload].
+
A visualização Aplicações e cargas de trabalho é exibida.

. Selecione *Adicionar à carga de trabalho*.
+
A caixa de diálogo Selecionar carga de trabalho é exibida.

. Execute as seguintes ações:
+
** *Adicionar volumes a uma carga de trabalho existente* -- Selecione esta opção para adicionar volumes a uma carga de trabalho existente.
+
Use a lista suspensa para selecionar uma carga de trabalho. O tipo de aplicativo associado da carga de trabalho é atribuído aos volumes que você adiciona a essa carga de trabalho.



. Selecione os volumes que você deseja adicionar à carga de trabalho.
. Revise os volumes que você deseja adicionar à carga de trabalho selecionada.
. Quando estiver satisfeito com a configuração da sua carga de trabalho, clique em *Add*.

