---
permalink: sm-storage/add-capacity-to-a-pool-or-volume-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, capacity, pool, volume, group 
summary: Você pode adicionar unidades para expandir a capacidade livre em um pool ou grupo de volumes existente. 
---
= Adicionar capacidade a um pool ou grupo de volumes no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar unidades para expandir a capacidade livre em um pool ou grupo de volumes existente.

A expansão faz com que a capacidade livre adicional seja incluída no pool ou no grupo de volumes. Você pode usar essa capacidade gratuita para criar volumes adicionais. Os dados nos volumes permanecem acessíveis durante esta operação.

.Antes de começar
* As unidades devem estar em um status ideal.
* As unidades devem ter o mesmo tipo de unidade (HDD ou SSD).
* O pool ou grupo de volume deve estar em um status ideal.
* O número máximo de volumes permitido num grupo de volumes é 256.
* O número máximo de volumes permitidos em um pool depende do modelo do sistema de armazenamento:
+
** 2.048 volumes (EF80, EF600 e E5700 series)
** 1.024 volumes (EF50 and EF300)
** 512 volumes (séries E4000 e E2800)


* Se o pool ou grupo de volumes contiver todas as unidades com capacidade segura, adicione apenas unidades com capacidade segura para continuar a usar as habilidades de criptografia das unidades com capacidade segura.
+
As unidades com capacidade segura podem ser unidades com criptografia total de disco (FDE) ou unidades FIPS (Federal Information Processing Standard).



.Sobre esta tarefa
Para pools, você pode adicionar um máximo de 60 unidades de cada vez. Para grupos de volumes, você pode adicionar um máximo de duas unidades de cada vez. Se for necessário adicionar mais do que o número máximo de unidades, repita o procedimento. (Um pool não pode conter mais unidades do que o limite máximo para um sistema de armazenamento.)

[NOTE]
====
Com a adição de unidades, sua capacidade de preservação pode precisar ser aumentada. Você deve considerar aumentar a capacidade reservada após uma operação de expansão.

====
[NOTE]
====
Evite usar unidades com suporte a Data Assurance (DA) para adicionar capacidade a um pool ou grupo de volume que não seja compatível com DA. O pool ou grupo de volume não pode aproveitar os recursos da unidade compatível com DA. Considere usar unidades que não sejam compatíveis com DA nessa situação.

====
.Passos
. No painel esquerdo, selecione menu:Storage[Pools and volume groups].
. Selecione o pool ou grupo de volume ao qual deseja adicionar unidades e clique no menu:ellipsis icon[Add capacity].
+
A caixa de diálogo Adicionar capacidade é exibida. Somente as unidades não atribuídas que são compatíveis com o pool ou grupo de volume aparecem.

. Em *Selecionar unidades para adicionar capacidade...*, selecione uma ou mais unidades que você deseja adicionar ao pool ou grupo de volume.
+
O firmware do controlador organiza as unidades não atribuídas com as melhores opções listadas na parte superior. A capacidade total gratuita adicionada ao pool ou grupo de volumes aparece abaixo da lista em *capacidade total selecionada*.

+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Campo | Descrição 


 a| 
Gaveta
 a| 
Indica a localização do compartimento da unidade.



 a| 
Baía
 a| 
Indica a localização do compartimento da unidade.



 a| 
Capacidade (GiB)
 a| 
Indica a capacidade da unidade.

** Sempre que possível, selecione unidades que tenham uma capacidade igual às capacidades das unidades atuais no pool ou grupo de volumes.
** Se você precisar adicionar unidades não atribuídas com uma capacidade menor, lembre-se de que a capacidade utilizável de cada unidade atualmente no pool ou grupo de volumes será reduzida. Portanto, a capacidade da unidade é a mesma em todo o pool ou grupo de volumes.
** Se você precisar adicionar unidades não atribuídas com uma capacidade maior, lembre-se de que a capacidade utilizável das unidades não atribuídas adicionadas será reduzida para que elas correspondam às capacidades atuais das unidades no pool ou grupo de volumes.




 a| 
Com capacidade segura
 a| 
Indica se a unidade é segura.

** Para proteger seu pool ou grupo de volumes com o recurso Segurança da unidade, todas as unidades devem ser seguras.
** É possível criar um pool ou grupo de volumes com uma combinação de unidades seguras e não seguras, mas o recurso Segurança da Unidade não pode ser ativado.
** Um pool ou grupo de volumes com todas as unidades com capacidade de segurança não pode aceitar uma unidade com capacidade de segurança para poupar ou expandir, mesmo que a capacidade de criptografia não esteja em uso.
** As unidades relatadas como seguras podem ser unidades com criptografia total de disco (FDE) ou unidades FIPS (Federal Information Processing Standard).
** Uma unidade FIPS pode ser nível 140-2 ou 140-3, com nível 140-3 como o nível mais alto de segurança. Se você selecionar uma combinação de unidades de nível 140-2 e 140-3, o pool ou grupo de volumes funcionará no nível mais baixo de segurança (140-2).




 a| 
DA capaz
 a| 
Indica se a unidade é capaz de Garantia de dados (DA).

** Não é recomendável usar unidades que não sejam compatíveis com Data Assurance (DA) para adicionar capacidade a um pool ou grupo de volume compatível com DA. O pool ou grupo de volume deixa de ter recursos de DA e você não tem mais a opção de habilitar DA em volumes recém-criados dentro do pool ou grupo de volume.
** Não é recomendável usar unidades com suporte a Data Assurance (DA) para adicionar capacidade a um pool ou grupo de volume que não tem suporte a DA, pois esse pool ou grupo de volume não poderá aproveitar os recursos da unidade com DA (os atributos da unidade não correspondem). Considere usar unidades sem suporte a DA nessa situação.




 a| 
DULBE capaz
 a| 
Indica se a unidade possui a opção de erro de bloco lógico desalocado ou não gravado (DULBE). DULBE é uma opção em unidades NVMe que permite que o array de storage EF80, EF50, EF300 ou EF600 suporte volumes com recursos provisionados.

|===
====
. Clique em *Add*.
+
Se você estiver adicionando unidades a um pool ou grupo de volumes, uma caixa de diálogo de confirmação será exibida se você selecionar uma unidade que faça com que o pool ou grupo de volumes não tenha mais um ou mais dos seguintes atributos:

+
** Proteção contra perda de prateleira*
** Proteção contra perda de gaveta
** Capacidade de encriptação total do disco
** Capacidade de garantia de dados
** Capacidade DULBE





NOTE: Atualmente, a caixa de diálogo de confirmação não é exibida ao adicionar unidades a um pool com proteção contra perda de prateleira ou proteção contra perda de gaveta.

. Para continuar, clique em *Yes*; caso contrário, clique em *Cancel*.


.Resultados
Depois de adicionar as unidades não atribuídas a um pool ou grupo de volumes, os dados em cada volume do pool ou grupo de volumes são redistribuídos para incluir as unidades adicionais.
