---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, snapshot, volume 
summary: Você pode alterar as configurações de um volume instantâneo para ajustar o ponto percentual no qual o sistema envia uma notificação de alerta quando a capacidade reservada para um volume instantâneo estiver quase cheia. 
---
= Altere as configurações de capacidade reservada para um volume instantâneo
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar as configurações de um volume instantâneo para ajustar o ponto percentual no qual o sistema envia uma notificação de alerta quando a capacidade reservada para um volume instantâneo estiver quase cheia.

.Passos
. Selecione menu:armazenamento[pools & grupos de volume].
. Clique na guia *capacidade reservada*.
. Selecione o volume instantâneo que deseja editar e clique em *Exibir/Editar configurações*.
+
A caixa de diálogo Configurações de capacidade reservada do volume instantâneo é exibida.

. Altere as configurações de capacidade reservada para o volume instantâneo, conforme apropriado.
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Definição | Descrição 


 a| 
Alerta-me quando...
 a| 
Use a caixa giratório para ajustar o ponto percentual no qual o sistema envia uma notificação de alerta quando a capacidade reservada para um volume de membro estiver quase cheia.

Quando a capacidade reservada para o volume instantâneo excede o limite especificado, o sistema envia um alerta, permitindo-lhe tempo para aumentar a capacidade reservada ou eliminar objetos desnecessários.

|===
====
. Clique em *Salvar* para aplicar as alterações às configurações de capacidade reservada do volume instantâneo.

