---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-mirrored-pair-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, mirrored pair volume 
summary: Você pode alterar as configurações de um volume de par espelhado para ajustar o ponto percentual no qual o System Manager envia uma notificação de alerta quando a capacidade reservada para um volume de par espelhado estiver quase cheia. 
---
= Alterar as configurações de capacidade reservada para um volume de par espelhado no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar as configurações de um volume de par espelhado para ajustar o ponto percentual no qual o Gerenciador de sistema do SANtricity envia uma notificação de alerta quando a capacidade reservada para um volume de par espelhado estiver quase cheia.

.Passos
. No painel esquerdo, selecione menu:Storage[Pools and volume groups].
. Selecione a guia *capacidade reservada*.
. Selecione o volume do par espelhado que você deseja editar e, em seguida, clique no menu:ícone de reticências[Edit Settings].
+
A janela Edit Mirrored Pair Volume Reserved Capacity Settings é exibida.

. Altere as configurações de capacidade reservada para o volume do par espelhado, conforme apropriado.
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Definição | Descrição 


 a| 
Limiar de alerta de capacidade reservada cheia
 a| 
Use a barra para ajustar o ponto percentual em que System Manager envia uma notificação de alerta quando a capacidade reservada para um par espelhado estiver quase cheia.

Quando a capacidade reservada para o par espelhado excede o limite especificado, o System Manager envia um alerta, permitindo que você aumente a capacidade reservada.


NOTE: Alterar a configuração Alerta para um par espelhado altera a configuração Alerta para todos os pares espelhados que pertencem ao mesmo grupo de consistência de espelho.

|===
====
. Clique em *Salvar* para aplicar suas alterações.

