---
permalink: sm-storage/change-settings-for-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, volume 
summary: Você pode alterar as configurações de um volume, como nome, atribuição de host, tamanho do segmento, prioridade de modificação, cache e assim por diante. 
---
= Alterar as configurações de um volume no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar as configurações de um volume, como nome, atribuição de host, tamanho do segmento, prioridade de modificação, cache e assim por diante.

.Antes de começar
O volume que pretende alterar está no estado ideal.


NOTE: Algumas operações podem estar indisponíveis enquanto as alterações nas definições de volume estão em curso

.Passos
. No painel esquerdo, selecione menu:Storage[Volumes].
. Selecione o volume que deseja alterar e clique no menu:ícone de reticências[Editar configurações].
+
A janela Edit Volume Settings é exibida, mostrando as configurações do volume selecionado.

. Configure as definições de volume conforme necessário:
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Definição | Descrição 


 a| 
Nome
 a| 
Exibe o nome do volume. Altere o nome de um volume quando o nome atual não for mais significativo ou aplicável.



 a| 
Host
 a| 
Exibe a atribuição de volume. Você atribui um volume a um host ou cluster de host para que ele possa ser acessado para operações de e/S. Essa atribuição concede a um host ou cluster de host acesso a um volume específico ou a um número de volumes em um storage array.

** *Assigned to* -- identifica o cluster de host ou host que tem acesso ao volume selecionado.
** *LUN* -- Um número de unidade lógica (LUN) é o número atribuído ao espaço de endereço que um host usa para acessar um volume. O volume é apresentado ao host como capacidade na forma de um LUN. Cada host tem seu próprio espaço de endereço LUN. Portanto, o mesmo LUN pode ser usado por diferentes hosts para acessar diferentes volumes.
+

NOTE: Para interfaces NVMe, essa coluna exibe o ID do namespace. Um namespace é o armazenamento NVM formatado para acesso a bloco. É análogo a uma unidade lógica em SCSI, que se relaciona a um volume no storage array. O ID do namespace é o identificador exclusivo da controladora NVMe para o namespace e pode ser definido como um valor entre 1 e 255. É análogo a um número de unidade lógica (LUN) no SCSI.





 a| 
Dimensionamento do segmento
 a| 
Mostra a definição para o dimensionamento de segmentos, que aparece apenas para volumes num grupo de volumes. Você pode alterar o tamanho do segmento para otimizar o desempenho.

* Transições permitidas de tamanho de segmento* -- o System Manager determina as transições de tamanho de segmento permitidas. Os tamanhos de segmento que são transições inadequadas do tamanho de segmento atual não estão disponíveis na lista suspensa. As transições permitidas geralmente são o dobro ou metade do tamanho atual do segmento. Por exemplo, se o tamanho atual do segmento de volume for 32 KiB, um novo tamanho de segmento de volume de 16 KiB ou 64 KiB será permitido.

*Volumes habilitados para cache SSD* -- você pode especificar um tamanho de segmento de 4 KiB para volumes habilitados para cache SSD. Certifique-se de selecionar o tamanho de segmento de 4 KiB apenas para volumes habilitados para cache SSD que lidam com operações de e/S de bloco pequeno (por exemplo, tamanhos de bloco de e/S KiB 16 ou menores). O desempenho pode ser afetado se você selecionar 4 KiB como o tamanho do segmento para volumes habilitados para cache SSD que lidam com operações sequenciais de blocos grandes.

*Quantidade de tempo para alterar o tamanho do segmento* -- a quantidade de tempo para alterar o tamanho do segmento de um volume depende dessas variáveis:

** A carga de e/S do host
** A prioridade de modificação do volume
** O número de unidades no grupo de volumes
** O número de canais da unidade
** A capacidade de processamento das controladoras de storage array quando você altera o tamanho de segmento de um volume, a performance de e/S é afetada, mas seus dados permanecem disponíveis.




 a| 
Prioridade de modificação
 a| 
Mostra a definição de prioridade de modificação, que só aparece para volumes num grupo de volumes.

A prioridade de modificação define quanto tempo de processamento é alocado para operações de modificação de volume em relação ao desempenho do sistema. Você pode aumentar a prioridade de modificação de volume, embora isso possa afetar o desempenho do sistema.

Mova as barras deslizantes para selecionar um nível de prioridade.

*Taxas de prioridade de modificação* -- a taxa de prioridade mais baixa beneficia o desempenho do sistema, mas a operação de modificação demora mais tempo. A taxa de prioridade mais alta beneficia a operação de modificação, mas o desempenho do sistema pode estar comprometido.

|===
====
. Clique em *Salvar*.
+
O System Manager altera as definições do volume com base nas suas seleções.



.Depois de terminar
Selecione o menu:Storage[Operations in Progress] para visualizar o progresso das operações de alteração que estão sendo executadas no volume selecionado.
