---
permalink: sm-storage/create-host-manually.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, host, manually 
summary: Para hosts que não podem ser descobertos automaticamente, você pode criar manualmente um host. A criação de um host é uma das etapas necessárias para que o storage array saiba quais hosts estão conetados a ele e para permitir o acesso de e/S aos volumes. 
---
= Criar host manualmente
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para hosts que não podem ser descobertos automaticamente, você pode criar manualmente um host. A criação de um host é uma das etapas necessárias para que o storage array saiba quais hosts estão conetados a ele e para permitir o acesso de e/S aos volumes.

.Sobre esta tarefa
Mantenha estas diretrizes em mente quando você cria um host:

* Você deve definir as portas de identificador de host que estão associadas ao host.
* Certifique-se de fornecer o mesmo nome que o nome do sistema atribuído pelo host.
* Esta operação não é bem-sucedida se o nome que você escolher já estiver em uso.
* O comprimento do nome não pode exceder 30 carateres.


.Passos
. Selecione menu:armazenamento[hosts].
. Clique em menu:criar[Host].
+
A caixa de diálogo criar host é exibida.

. Selecione as configurações para o host, conforme apropriado.
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Definição | Descrição 


 a| 
Nome
 a| 
Digite um nome para o novo host.



 a| 
Tipo de sistema operacional de host
 a| 
Selecione o sistema operacional que está sendo executado no novo host na lista suspensa.



 a| 
Tipo de interface de host
 a| 
(Opcional) se você tiver mais de um tipo de interface de host compatível com seu storage array, selecione o tipo de interface de host que deseja usar.



 a| 
Portas de host
 a| 
Execute um dos seguintes procedimentos:

** *Selecione Interface I/o*
+
Geralmente, as portas do host devem ter feito login e estar disponíveis na lista suspensa. Você pode selecionar os identificadores de porta do host na lista.

** *Manual add*
+
Se um identificador de porta do host não for exibido na lista, isso significa que a porta do host não foi conetada. Um utilitário HBA ou o utilitário iniciador iSCSI podem ser usados para localizar os identificadores de porta do host e associá-los ao host.

+
Você pode inserir manualmente os identificadores de porta do host ou copiá-los/colá-los do utilitário (um de cada vez) no campo *Host Ports*.

+
Você deve selecionar um identificador de porta de host de cada vez para associá-lo ao host, mas pode continuar a selecionar quantos identificadores estão associados ao host. Cada identificador é exibido no campo *Host Ports*. Se necessário, você também pode remover um identificador selecionando *X* ao lado dele.





 a| 
Iniciador CHAP
 a| 
(Opcional) se você selecionou ou inseriu manualmente uma porta de host com um IQN iSCSI e se quiser exigir que um host que tente acessar a matriz de armazenamento para se autenticar usando o Challenge Handshake Authentication Protocol (CHAP), marque a caixa de seleção *iniciador CHAP*. Para cada porta de host iSCSI selecionada ou inserida manualmente, faça o seguinte:

** Insira o mesmo segredo CHAP que foi definido em cada iniciador de host iSCSI para autenticação CHAP. Se você estiver usando autenticação CHAP mútua (autenticação bidirecional que permite que um host se valide para o storage array e para que um storage array se valide para o host), você também deve definir o segredo CHAP para o storage array na configuração inicial ou alterando as configurações.
** Deixe o campo em branco se você não precisar de autenticação de host.


Atualmente, o único método de autenticação iSCSI usado pelo System Manager é CHAP.

|===
====
. Clique em *criar*.


.Resultados
Depois que o host é criado com êxito, o sistema cria um nome padrão para cada porta de host configurada para o host (rótulo do usuário).

O alias predefinido é``Hostname_Port Number`` >. Por exemplo, o alias padrão para a primeira porta criada para `host IPT is IPT_1`.
