---
permalink: sm-storage/create-pool-automatically.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, pool, automatically 
summary: A criação de pool é iniciada automaticamente quando o System Manager deteta unidades não atribuídas no storage array. Você pode usar a criação automática de pool para configurar facilmente todas as unidades não atribuídas no storage em um pool e adicionar unidades a pools existentes. 
---
= Crie um pool automaticamente no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A criação de pool é iniciada automaticamente quando o Gerenciador de sistema do SANtricity deteta unidades não atribuídas no storage array. Você pode usar a criação automática de pool para configurar facilmente todas as unidades não atribuídas no storage em um pool e adicionar unidades a pools existentes.

.Antes de começar
Você pode iniciar a caixa de diálogo Pool Auto-Configuration (Configuração automática do pool) quando uma destas condições for verdadeira:

* Pelo menos uma unidade não atribuída foi detetada que pode ser adicionada a um pool existente com tipos de unidade semelhantes.
* Onze (11) ou mais unidades não atribuídas foram detetadas que podem ser usadas para criar um novo pool (se elas não puderem ser adicionadas a um pool existente devido a tipos de unidades diferentes).


.Sobre esta tarefa
Tenha em mente o seguinte:

* Quando você adiciona unidades a um storage array, o System Manager deteta automaticamente as unidades e solicita que você crie um único pool ou vários pools com base no tipo de unidade e na configuração atual.
* Se os pools foram definidos anteriormente, o System Manager solicitará automaticamente a opção de adicionar as unidades compatíveis a um pool existente. Quando novas unidades são adicionadas a um pool existente, o System Manager redistribui automaticamente os dados pela nova capacidade, que agora inclui as novas unidades adicionadas.
* Ao configurar um storage de armazenamento EF600 ou EF300, verifique se cada controlador tem acesso a um número igual de unidades nos primeiros 12 slots e a um número igual de unidades nos últimos 12 slots. Essa configuração ajuda os controladores a usar os dois barramentos PCIe do lado da unidade de forma mais eficaz.


Você pode iniciar a caixa de diálogo Configuração automática do pool usando qualquer um dos seguintes métodos:

* Quando a capacidade não atribuída é detetada, a recomendação Pool Auto-Configuration (Configuração automática do conjunto) é apresentada na página inicial na área Notification (notificação). Clique em *View Pool Auto-Configuration* para iniciar a caixa de diálogo.
* Você também pode iniciar a caixa de diálogo Pool Auto-Configuration (Configuração automática do pool) na página pools e grupos de volume, conforme descrito na tarefa a seguir.


.Passos
. Selecione menu:armazenamento[pools & grupos de volume].
. Selecione menu:mais[Launch pool auto-Configuration] (Iniciar configuração automática do pool).
+
A tabela de resultados lista novos pools, pools existentes com unidades adicionadas ou ambos. Um novo pool é nomeado com um número sequencial por padrão.

+
O System Manager executa as seguintes tarefas:

+
** Cria um único pool se houver um número suficiente de unidades com o mesmo tipo de unidade (HDD ou SSD) e tiverem capacidade semelhante.
** Cria vários pools se a capacidade não atribuída consistir em diferentes tipos de unidade.
** Adiciona as unidades a um pool existente se um pool já estiver definido no storage de armazenamento e você adicionar novas unidades do mesmo tipo de unidade ao pool.
** Adiciona as unidades do mesmo tipo de unidade ao pool existente e usa os outros tipos de unidade para criar pools diferentes se as novas unidades forem de tipos de unidade diferentes.


. Para alterar o nome de um novo pool, clique no ícone *Editar* (o lápis).
. Para ver caraterísticas adicionais do pool, posicione o cursor sobre ou toque no ícone *Detalhes* (a página).
+
São exibidas informações sobre o tipo de unidade, a capacidade de segurança, a capacidade de garantia de dados (DA), a proteção contra perda de gaveta e a proteção contra perda de gaveta.

+
Para storages EF600 e EF300, as configurações também são exibidas para provisionamento de recursos e tamanhos de blocos de volume.

. Clique em *aceitar*.

