---
permalink: sm-storage/create-host-cluster.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, host, cluster 
summary: Você cria um cluster de host quando dois ou mais hosts exigem acesso de e/S aos mesmos volumes. 
---
= Crie um cluster de host no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você cria um cluster de host quando dois ou mais hosts exigem acesso de e/S aos mesmos volumes.

.Sobre esta tarefa
Tenha essas diretrizes em mente ao criar um cluster de host:

* Esta operação não é iniciada a menos que haja dois ou mais hosts disponíveis para criar o cluster.
* Os hosts em clusters de host podem ter sistemas operacionais diferentes (heterogêneos).
* Os hosts NVMe nos clusters de host não podem ser misturados a hosts não NVMe.
* Para criar um volume habilitado para Data Assurance (DA), a conexão de host que você está planejando usar deve suportar DA.
+
Se qualquer uma das conexões de host nos controladores do storage array não suportar DA, os hosts associados não poderão acessar dados em volumes habilitados PARA DA.

* Esta operação não é bem-sucedida se o nome que você escolher já estiver em uso.
* O comprimento do nome não pode exceder 30 carateres.


.Passos
. Selecione menu:armazenamento[hosts].
. Selecione menu:criar[Host Cluster].
+
A caixa de diálogo criar cluster de host é exibida.

. Selecione as configurações do cluster de host, conforme apropriado.
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Definição | Descrição 


 a| 
Nome
 a| 
Digite o nome do novo cluster de host.



 a| 
Selecione hosts para compartilhar o acesso ao volume
 a| 
Selecione dois ou mais hosts na lista suspensa. Apenas os hosts que ainda não fazem parte de um cluster de host aparecem na lista.

|===
====
. Clique em *criar*.
+
Se os hosts selecionados estiverem conetados a tipos de interface que tenham diferentes recursos de Data Assurance (DA), uma caixa de diálogo será exibida com a mensagem de que DA estará indisponível no cluster de host. Essa indisponibilidade impede que volumes habilitados PARA DA sejam adicionados ao cluster de host. Selecione *Sim* para continuar ou *não* para cancelar.

+
DA aumenta a integridade dos dados em todo o sistema de storage. O DA permite que o storage array verifique se há erros que possam ocorrer quando os dados são movidos entre os hosts e as unidades. O uso DA para o novo volume garante que quaisquer erros sejam detetados.



.Resultados
O novo cluster de host aparece na tabela com os hosts atribuídos nas linhas abaixo.
