---
permalink: sm-storage/delete-host-or-host-cluster.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, host, host cluster 
summary: Você pode excluir um host ou cluster de host. 
---
= Excluir um host ou cluster de host no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode excluir um host ou cluster de host.

.Sobre esta tarefa
Tenha estas diretrizes em mente quando você excluir um host ou um cluster de host:

* Quaisquer atribuições específicas de volume são excluídas e os volumes associados estão disponíveis para uma nova atribuição.
* Se o host fizer parte de um cluster de host que tenha suas próprias atribuições específicas, o cluster de host não será afetado. No entanto, se o host fizer parte de um cluster de host que não tenha outras atribuições, o cluster de host e quaisquer outros hosts ou identificadores de porta de host associados herdarão quaisquer atribuições padrão.
* Quaisquer identificadores de porta de host que foram associados ao host tornam-se indefinidos.


.Passos
. Selecione menu:armazenamento[hosts].
. Selecione o host ou cluster de host que você deseja excluir e clique em *Excluir*.
+
É apresentada a caixa de diálogo de confirmação.

. Confirme se deseja executar a operação e clique em *Excluir*.


.Resultados
Se você excluir um host, o sistema executará as seguintes ações:

* Exclui o host e, se aplicável, o remove do cluster de host.
* Remove o acesso a quaisquer volumes atribuídos.
* Retorna os volumes associados a um estado não atribuído.
* Retorna qualquer identificador de porta de host associado ao host para um estado não associado.


Se você excluir um cluster de host, o sistema executará as seguintes ações:

* Exclui o cluster de host e seus hosts associados (se houver).
* Remove o acesso a quaisquer volumes atribuídos.
* Retorna os volumes associados a um estado não atribuído.
* Retorna todos os identificadores de porta de host associados aos hosts para um estado não associado.

