---
permalink: sm-storage/enable-security.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, security, pool, volume group 
summary: Você pode ativar o Drive Security para um pool ou grupo de volumes para impedir o acesso não autorizado aos dados nas unidades contidas no pool ou grupo de volumes. O acesso de leitura e gravação para as unidades só está disponível através de um controlador configurado com uma chave de segurança. 
---
= Habilitar segurança para um pool ou grupo de volumes no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode ativar o Drive Security para um pool ou grupo de volumes para impedir o acesso não autorizado aos dados nas unidades contidas no pool ou grupo de volumes. O acesso de leitura e gravação para as unidades só está disponível através de um controlador configurado com uma chave de segurança.

.Antes de começar
* O recurso Segurança da unidade deve estar ativado.
* Uma chave de segurança deve ser criada.
* O pool ou grupo de volume deve estar em um estado ideal.
* Todas as unidades no pool ou grupo de volumes devem ser unidades com capacidade de segurança.


.Sobre esta tarefa
Se você quiser usar o Drive Security, selecione um pool ou grupo de volume que seja seguro. Um pool ou grupo de volumes pode conter unidades com capacidade de segurança e não seguras, mas todas as unidades devem ser seguras para usar seus recursos de criptografia.

Depois de ativar a segurança, você só pode removê-la excluindo o pool ou grupo de volumes e apagando as unidades.

.Passos
. Selecione menu:armazenamento[pools & grupos de volume].
. Selecione o pool ou grupo de volume no qual deseja ativar a segurança e clique em menu:mais[Ativar segurança].
+
A caixa de diálogo confirmar ativação da segurança é exibida.

. Confirme se deseja ativar a segurança para o pool ou grupo de volumes selecionado e clique em *Ativar*.

