---
permalink: sm-storage/faq-remote-storage.html 
sidebar: sidebar 
keywords:  
summary: Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta. 
---
= Perguntas frequentes sobre armazenamento remoto para o SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta.



== O que eu preciso saber antes de criar uma conexão de armazenamento remoto?

Para configurar a funcionalidade armazenamento remoto, tem de ligar diretamente o dispositivo remoto e os sistemas de armazenamento de destino através de iSCSI.

Para configurar a ligação do sistema iSCSI, consulte:

* link:../sm-hardware/configure-iscsi-ports-hardware.html["Configurar portas iSCSI"]
* https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["Relatório técnico de armazenamento remoto"^]




== Por que estou sendo solicitado a remover meus volumes remotos?

Quando atinge o número máximo de volumes remotos, o sistema de armazenamento deteta automaticamente quaisquer volumes remotos não utilizados e solicita que os remova.

Existem alguns casos em que os volumes remotos não utilizados não são limpos durante o processo de criação. Antes de iniciar quaisquer operações de importação adicionais, verifique se os seus sistemas são ideais e as ligações de rede são estáveis.



== Por que não vejo todos os meus volumes no meu array de destino?

Ao configurar uma importação para o recurso armazenamento remoto, você pode notar que alguns volumes não aparecem na lista de candidatos alvo devido ao tamanho do bloco, capacidade ou disponibilidade de volume.

Para aparecer na lista, os candidatos ao volume devem ter:

* Capacidade igual ou superior ao volume remoto.
* Tamanho do bloco que é o mesmo que o volume remoto.
* Status atual do Optimal.


Os candidatos a volumes são excluídos da lista se tiverem:

* Qualquer uma das seguintes relações: Cópia de volume, snapshot ou espelhamento.
* Operação de reconfiguração em curso.
* Mapeamento para outro dispositivo (host ou cluster de host).
* Ler cache flash ativado.




== O que eu preciso saber sobre o volume remoto em uma importação?

Ao utilizar a funcionalidade armazenamento remoto, tenha em atenção que o volume remoto é a origem da origem dos dados.

Quando a importação está em andamento, os dados são transferidos do volume remoto para o volume de destino no sistema de armazenamento de destino. Esses dois volumes devem ter um tamanho de bloco correspondente.



== O que eu preciso saber antes de iniciar uma importação de armazenamento remoto?

O recurso armazenamento remoto permite copiar dados de um sistema de storage remoto para um volume em um sistema de storage local e-Series. Antes de usar esse recurso, revise as diretrizes a seguir.



=== Configuração

Antes de criar a importação de armazenamento remoto, você deve concluir as seguintes ações e verificar as seguintes condições:

* Certifique-se de que cada controlador do sistema de storage local e-Series tem uma conexão iSCSI ao sistema de storage remoto.
* No sistema de storage local do e-Series, crie um volume de destino para a operação de importação. Certifique-se de que o volume tem uma capacidade igual ou superior ao volume de origem, tem um tamanho de bloco que corresponde ao volume de origem e não está mapeado. link:create-volumes.html["Criar volumes"]Consulte .
* Configure o sistema de storage local e-Series como um host no sistema remoto usando seu nome qualificado iSCSI (IQN). Pode visualizar o IQN a partir do menu:Definições[sistema > Definições iSCSI > IQN de destino]. Além disso, certifique-se de definir o tipo de host apropriado com base no sistema que está sendo usado.
* Pare todas as I/os, desmonte quaisquer sistemas de arquivos e remova quaisquer atribuições a hosts ou aplicativos para o volume selecionado no sistema de storage remoto.
* Atribua o volume ao sistema de storage remoto ao recém-criado host local do sistema de storage e-Series.
* Reúna as seguintes informações do sistema de armazenamento remoto para que a importação possa ser criada:
+
** Nome qualificado iSCSI (IQN)
** Endereço IP iSCSI
** O número LUN do dispositivo de armazenamento remoto, onde os dados de origem são originários


* Assim que o processo de importação começar, todo o volume de destino local é substituído pelos dados copiados. Todos os novos dados gravados no volume de destino local são propagados para o volume no dispositivo de armazenamento remoto após a criação da importação. Portanto, recomendamos que você faça backup de volumes no sistema de armazenamento remoto antes de iniciar o processo de importação.




=== Processo de importação

As etapas a seguir descrevem o processo de importação.

. Acesse a interface do System Manager e vá para a página *armazenamento remoto*. Selecione *Importar* para iniciar uma nova criação de importação. Para obter instruções detalhadas, link:rtv-import-remote-storage.html["Importar armazenamento remoto"]consulte .
+
Se você quiser executar uma importação off-line, não mapeie o volume de destino até que a importação seja concluída.

. Monitorize o progresso da importação.
+
Assim que a importação for iniciada, o volume de destino poderá ser mapeado. O tempo necessário para concluir a operação de importação depende do tamanho do dispositivo de armazenamento remoto (volume de origem), da configuração de prioridade para a importação e da quantidade de carga de e/S em ambos os sistemas de armazenamento e seus volumes associados.

+
Após a conclusão da importação, o volume de destino é uma cópia da origem.

. Quando estiver pronto para quebrar a relação de mapeamento, execute um *Disconnect* no objeto de importação do painel *Operations in Progress*.


Quando a importação é desconetada, o desempenho do destino local retorna ao normal e não é mais afetado pela conexão remota.



=== Restrições

O recurso de armazenamento remoto tem as seguintes restrições:

* O espelhamento deve estar desativado.
* O volume de destino no sistema e-Series não deve ter instantâneos.
* O volume de destino no sistema e-Series não deve ser mapeado para nenhum host antes que a importação seja iniciada.
* O volume de destino no sistema e-Series deve ter o provisionamento de recursos desativado.
* Mapeamentos diretos do volume de armazenamento remoto para um host ou vários hosts não são suportados.
* O proxy de serviços da Web não é suportado.
* Segredos CHAP iSCSI não são suportados.
* O smcli não é suportado.
* O VMware datastore não é compatível.
* Apenas um sistema de armazenamento no par de relacionamento/importação pode ser atualizado de uma vez em que há um par de importação presente.




=== Informações adicionais

Para obter mais informações sobre a funcionalidade de armazenamento remoto, consulte a https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["Relatório técnico de armazenamento remoto"^] .
