---
permalink: sm-storage/how-do-i-maintain-shelf-drawer-loss-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, shelf, drawer, loss, protection 
summary: Para manter a proteção contra perda de gaveta/gaveta para um pool ou grupo de volumes, use os critérios especificados na tabela a seguir. 
---
= Como faço para manter a proteção contra perda de prateleira/gaveta?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para manter a proteção contra perda de gaveta/gaveta para um pool ou grupo de volumes, use os critérios especificados na tabela a seguir.

[cols="1a,1a,1a"]
|===
| Nível | Critérios para proteção contra perda de prateleira/gaveta | Número mínimo de prateleiras/gavetas necessário 


 a| 
Piscina
 a| 
Para gavetas, o pool não deve conter mais de duas unidades em uma única gaveta.

Para gavetas, o pool deve incluir um número igual de unidades de cada gaveta.
 a| 
6 para prateleiras

5 para gavetas



 a| 
RAID 6
 a| 
O grupo de volumes não contém mais do que duas unidades em um único compartimento ou gaveta.
 a| 
3



 a| 
RAID 3 ou RAID 5
 a| 
Cada unidade no grupo de volume está localizada em uma gaveta ou gaveta separada.
 a| 
3



 a| 
RAID 1
 a| 
Cada unidade em um par espelhado deve estar localizada em uma gaveta ou gaveta separada.
 a| 
2



 a| 
RAID 0
 a| 
Não é possível obter proteção contra perda de prateleira/gaveta.
 a| 
Não aplicável

|===
[NOTE]
====
A proteção contra perda de gaveta/gaveta não será mantida se uma unidade já tiver falhado no pool ou no grupo de volumes. Nessa situação, perder o acesso a um compartimento de unidades ou gaveta e, consequentemente, outra unidade no pool ou grupo de volume, causa perda de dados.

====