---
permalink: sm-storage/how-workloads-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, application, workloads, volume, 
summary: Ao criar um volume, você seleciona uma carga de trabalho para personalizar a configuração do storage array para um aplicativo específico. 
---
= Como as cargas de trabalho funcionam no software SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao criar um volume, você seleciona uma carga de trabalho para personalizar a configuração do storage array para um aplicativo específico.

Um workload é um objeto de storage compatível com uma aplicação. Você pode definir uma ou mais cargas de trabalho ou instâncias por aplicação. Para alguns aplicativos, o sistema configura a carga de trabalho para conter volumes com caraterísticas de volume subjacentes semelhantes. Essas características de volume são otimizadas com base no tipo de aplicação compatível com o workload. Por exemplo, se você criar uma carga de trabalho que suporte um aplicativo Microsoft SQL Server e, posteriormente, criar volumes para essa carga de trabalho, as caraterísticas de volume subjacentes serão otimizadas para oferecer suporte ao Microsoft SQL Server.

Durante a criação de volume, o sistema solicita que você responda a perguntas sobre o uso de uma carga de trabalho. Por exemplo, se você estiver criando volumes para o Microsoft Exchange, será perguntado quantas caixas de correio você precisa, quais são seus requisitos médios de capacidade de caixa de correio e quantas cópias do banco de dados deseja. O sistema usa essas informações para criar uma configuração de volume ideal para você, que pode ser editada conforme necessário. Opcionalmente, você pode pular esta etapa na sequência de criação de volume.



== Tipos de workloads

Você pode criar dois tipos de workloads: Específicos da aplicação e outros.

* *Específico da aplicação*. Quando você está criando volumes usando uma carga de trabalho específica da aplicação, o sistema pode recomendar uma configuração de volume otimizada para minimizar a contenção entre a e/S da carga de trabalho do aplicativo e outro tráfego da instância do aplicativo. As características de volume, como tipo de e/S, tamanho do segmento, propriedade da controladora e cache de leitura e gravação, são automaticamente recomendadas e otimizadas para cargas de trabalho criadas para os seguintes tipos de aplicativos.
+
** Microsoft SQL Server
** Microsoft Exchange Server
** Aplicações de vigilância por vídeo
** VMware ESXi (para volumes a serem usados com o Virtual Machine File System)
+
Você pode revisar a configuração de volume recomendada e editar, adicionar ou excluir os volumes e caraterísticas recomendados pelo sistema usando a caixa de diálogo Adicionar/Editar volumes.



* *Outros* (ou aplicativos sem suporte específico para criação de volume). Outros workloads usam uma configuração de volume que você precisa especificar manualmente quando deseja criar um workload que não esteja associado a uma aplicação específica ou se o sistema não tiver otimização incorporada para a aplicação que você pretende usar no storage array. Você deve especificar manualmente a configuração do volume usando a caixa de diálogo Adicionar/Editar volumes.




== Visualizações de aplicação e workload

Para visualizar aplicações e workloads, inicie o Gerenciador de sistemas do SANtricity. Nessa interface, você pode exibir informações associadas a uma carga de trabalho específica do aplicativo de algumas maneiras diferentes:

* Você pode selecionar a guia *aplicativos e cargas de trabalho* no bloco volumes para exibir os volumes do storage array agrupados por carga de trabalho e o tipo de aplicativo ao qual a carga de trabalho está associada.
* Você pode selecionar a guia *aplicativos e cargas de trabalho* no bloco desempenho para exibir métricas de desempenho (latência, IOPS e MBs) para objetos lógicos. Os objetos são agrupados por aplicativo e carga de trabalho associada. Ao coletar esses dados de desempenho em intervalos regulares, você pode estabelecer medições de linha de base e analisar tendências, o que pode ajudar a investigar problemas relacionados ao desempenho de e/S.

