---
permalink: sm-storage/how-volumes-are-assigned-to-hosts-and-host-clusters.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volumes, assigned, hosts, clusters 
summary: Para que um host ou cluster de host envie e/S para um volume, você deve atribuir o volume ao host ou cluster de host. 
---
= Como os volumes são atribuídos a hosts e clusters de hosts no software SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para que um host ou cluster de host envie e/S para um volume, você deve atribuir o volume ao host ou cluster de host.

Você pode selecionar um host ou cluster de host ao criar um volume ou atribuir um volume a um host ou cluster de host posteriormente. Um cluster de host é um grupo de hosts. Você cria um cluster de host para facilitar a atribuição dos mesmos volumes a vários hosts.

Atribuir volumes a hosts é flexível, permitindo que você atenda às suas necessidades de armazenamento específicas.

* * Host autônomo, não parte de um cluster de host* -- você pode atribuir um volume a um host individual. O volume só pode ser acessado por um host.
* *Host cluster* -- você pode atribuir um volume a um cluster de host. O volume pode ser acessado por todos os hosts no cluster de host.
* *Host dentro de um cluster de host* -- você pode atribuir um volume a um host individual que faz parte de um cluster de host. Mesmo que o host faça parte de um cluster de host, o volume pode ser acessado apenas pelo host individual e não por nenhum outro host no cluster de host.


Quando os volumes são criados, os números de unidade lógica (LUNs) são atribuídos automaticamente. O LUN serve como o "endereço" entre o host e o controlador durante as operações de e/S. Você pode alterar LUNs depois que o volume é criado.
