---
permalink: sm-storage/how-workloads-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, application, workloads, volume, 
summary: Ao criar um volume, você seleciona uma carga de trabalho para personalizar a configuração do storage array para um aplicativo específico. 
---
= Como as cargas de trabalho funcionam no software SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao criar um volume, você seleciona uma carga de trabalho para personalizar a configuração do storage array para um aplicativo específico.

Um workload é um objeto de storage compatível com uma aplicação. Você pode definir uma ou mais cargas de trabalho ou instâncias por aplicação.



== Criando uma carga de trabalho

Você deve especificar manualmente quando deseja criar uma carga de trabalho que não esteja associada a um aplicativo específico. Você também deve especificar manualmente a configuração de volume usando a página Add Volumes.



== Visualizações de aplicação e workload

Para visualizar aplicações e workloads, inicie o Gerenciador de sistemas do SANtricity. Nessa interface, você pode exibir informações associadas a uma carga de trabalho específica do aplicativo de algumas maneiras diferentes:

* Você pode selecionar a guia *Aplicações e cargas de trabalho* na página Volumes para visualizar os volumes do array de storage agrupados por carga de trabalho e pelo tipo de aplicação ao qual a carga de trabalho está associada.
* Você pode selecionar a guia *Aplicações e cargas de trabalho* na página Desempenho para visualizar métricas de desempenho (latência, IOPS e MBs) de objetos lógicos. Os objetos são agrupados por aplicação e carga de trabalho associada. Ao coletar esses dados de desempenho em intervalos regulares, você pode estabelecer medições de referência e analisar tendências, o que pode ajudar na investigação de problemas relacionados ao desempenho de I/O.

