---
permalink: sm-storage/increase-capacity-of-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, increase, capacity, volume 
summary: 'Você pode aumentar a capacidade reportada (a capacidade relatada aos hosts) de um volume usando a capacidade livre disponível no pool ou no grupo de volumes.' 
---
= Aumentar a capacidade de um volume no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode aumentar a capacidade reportada (a capacidade relatada aos hosts) de um volume usando a capacidade livre disponível no pool ou no grupo de volumes.

.Antes de começar
* A capacidade livre suficiente está disponível no pool ou grupo de volumes associados ao volume.
* O volume é ótimo e não em nenhum estado de modificação.
* A capacidade máxima reportada de 256 TIB não foi atingida para volumes finos.
* Não há unidades hot spare em uso no volume. (Aplica-se apenas a volumes em grupos de volumes.)



NOTE: Você só pode expandir a capacidade de volume até 128 TIB em um único momento.

.Sobre esta tarefa
Lembre-se de quaisquer requisitos de capacidade futuros que você possa ter para outros volumes nesse pool ou grupo de volumes. Certifique-se de que permite uma capacidade livre suficiente para criar imagens instantâneas, volumes instantâneos ou espelhos remotos.

[NOTE]
====
O aumento da capacidade de um volume é suportado apenas em determinados sistemas operacionais. Se você aumentar a capacidade de volume em um sistema operacional host que não é suportado, a capacidade expandida será inutilizável e você não poderá restaurar a capacidade de volume original.

====
.Passos
. No painel esquerdo, selecione menu:Storage[Volumes].
. Selecione o volume para o qual deseja aumentar a capacidade e, em seguida, clique no menu:ícone de reticências[Aumentar capacidade].
+
A página Confirm Increase Capacity é exibida.

. Selecione *Sim* para continuar.
+
A página Aumento da Capacidade Reportada é exibida.

+
Esta página exibe a capacidade atual relatada do volume e a capacidade livre disponível no pool ou grupo de volume associado ao volume.

. Use a caixa *Aumentar a capacidade relatada adicionando...* para adicionar capacidade à capacidade relatada disponível atualmente. Você pode alterar o valor da capacidade para exibir em mebibytes (MiB), gibibytes (GiB) ou tebibytes (TiB).
. Clique em *aumentar*.


.Resultados
* O System Manager aumenta a capacidade do volume com base na sua seleção.
* Selecione menu:Storage[Operations in Progress] para visualizar o progresso da operação de aumento de capacidade que está sendo executada para o volume selecionado. Essa operação pode ser demorada e pode afetar o desempenho do sistema.


.Depois de terminar
Depois de expandir a capacidade de volume, você deve aumentar manualmente o tamanho do sistema de arquivos para corresponder. A forma como você faz isso depende do sistema de arquivos que você está usando. Consulte a documentação do sistema operacional do host para obter detalhes.
