---
permalink: sm-storage/initialize-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, initialize, volumes 
summary: Um volume é inicializado automaticamente quando é criado pela primeira vez. No entanto, o Recovery Guru pode aconselhar que você inicialize manualmente um volume para recuperar de certas condições de falha. Utilize esta opção apenas sob a orientação do suporte técnico. Pode selecionar um ou mais volumes para inicializar. 
---
= Inicializar volumes no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um volume é inicializado automaticamente quando é criado pela primeira vez. No entanto, o Recovery Guru pode aconselhar que você inicialize manualmente um volume para recuperar de certas condições de falha. Utilize esta opção apenas sob a orientação do suporte técnico. Pode selecionar um ou mais volumes para inicializar.

.Antes de começar
* Todas as operações de e/S foram interrompidas.
* Todos os dispositivos ou sistemas de arquivos nos volumes que você deseja inicializar devem ser desmontados.
* O volume está no estado ideal e não estão em curso operações de modificação no volume.


[CAUTION]
====
Não é possível cancelar a operação depois de iniciada. Todos os dados de volume são apagados. Não tente esta operação, a menos que o Recovery Guru o aconselhe a fazê-lo. Contacte o suporte técnico antes de iniciar este procedimento.

====
.Sobre esta tarefa
Ao inicializar um volume, o volume mantém suas configurações WWN, atribuições de host, capacidade alocada e capacidade reservada. Ele também mantém as mesmas configurações de garantia de dados (DA) e configurações de segurança.

Os seguintes tipos de volumes _não podem_ ser inicializados:

* Volume base de um volume instantâneo
* Volume primário em uma relação espelhada
* Volume secundário em uma relação de espelho
* Volume de origem em uma cópia de volume
* Volume de destino em uma cópia de volume
* Volume que já tem uma inicialização em curso


Este tópico aplica-se apenas a volumes padrão criados a partir de pools ou grupos de volumes.

.Passos
. Selecione menu:armazenamento[volumes].
. Selecione qualquer volume e, em seguida, selecione menu:mais[Inicializar volumes].
+
A caixa de diálogo Inicializar volumes é exibida. Todos os volumes na matriz de armazenamento aparecem nesta caixa de diálogo.

. Selecione um ou mais volumes que deseja inicializar e confirme que deseja executar a operação.


.Resultados
O System Manager executa as seguintes ações:

* Apaga todos os dados dos volumes que foram inicializados.
* Limpa os índices de bloco, o que faz com que os blocos não escritos sejam lidos como se fossem preenchidos com zero (o volume parece estar completamente vazio).


Selecione menu:Home[View Operations in Progress] (Ver operações em curso) para ver o progresso da operação de inicialização que está atualmente em execução para o volume selecionado. Esta operação pode ser demorada e pode afetar o desempenho do sistema.
