---
permalink: sm-storage/rtv-modify-connection-settings-for-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, modify, connection, settings, remote, storage 
summary: Pode editar, adicionar ou eliminar definições de ligação para qualquer configuração de armazenamento remoto através da opção Ver/Editar definições. 
---
= Modificar as definições de ligação para armazenamento remoto
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pode editar, adicionar ou eliminar definições de ligação para qualquer configuração de armazenamento remoto através da opção Ver/Editar definições.

.Sobre esta tarefa
Fazer alterações nas propriedades de conexão afetará as importações em andamento. Para evitar interrupções, faça apenas alterações nas propriedades de conexão quando as importações não estiverem em execução.

.Passos
. Selecione menu:armazenamento[armazenamento remoto].
. Na lista, selecione o objeto de armazenamento remoto que deseja modificar.
. Clique em *Exibir/Editar configurações*.
+
A caixa de diálogo Configurações de armazenamento remoto é exibida.

. Clique na guia *Propriedades da conexão*.
+
São apresentadas as definições de endereço IP e de porta configuradas para a importação de armazenamento remoto.

. Execute uma das seguintes ações:
+
** *Editar* -- clique em *Editar* ao lado do item de linha correspondente para o objeto de armazenamento remoto. Introduza o endereço IP revisto e/ou as informações da porta nos campos.
** *Add* -- clique em *Add* e, em seguida, insira o novo endereço IP e as informações da porta nos campos fornecidos. Clique em *Add* para confirmar e, em seguida, a nova conexão aparece na lista de objetos de armazenamento remoto.
** *Excluir* -- Selecione a conexão desejada na lista e clique em *Excluir*. Confirme a operação digitando `delete` no campo fornecido e clique em *Excluir*. A conexão é removida da lista de objetos de armazenamento remoto.


. Clique em *Salvar*.
+
As configurações de conexão modificadas são aplicadas ao objeto de armazenamento remoto.


