---
permalink: sm-storage/what-is-optimization-capacity-volume-groups.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, optimization, capacity, volume, groups 
summary: As unidades SSD terão vida útil mais longa e melhor desempenho máximo de gravação quando uma parte de sua capacidade não for alocada. 
---
= O que é a capacidade de otimização para grupos de volumes?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As unidades SSD terão vida útil mais longa e melhor desempenho máximo de gravação quando uma parte de sua capacidade não for alocada.

Para unidades associadas a um grupo de volumes, a capacidade não alocada é composta pela capacidade livre de um grupo de volumes (capacidade não usada por volumes) e uma parte da capacidade utilizável reservada como capacidade de otimização. A capacidade de otimização adicional garante um nível mínimo de capacidade de otimização, reduzindo a capacidade utilizável, e, como tal, não está disponível para criação de volume.

Quando um grupo de volumes é criado, uma capacidade de otimização recomendada é gerada, que fornece um equilíbrio de desempenho, vida útil de desgaste e capacidade disponível. O controle deslizante capacidade de otimização adicional na caixa de diálogo Configurações do grupo de volume permite ajustes na capacidade de otimização de um grupo de volume. O ajuste da barra deslizante proporciona um melhor desempenho e vida útil do desgaste à custa da capacidade disponível, ou da capacidade disponível adicional à custa do desempenho e da vida útil do desgaste da transmissão.

[NOTE]
====
O controle deslizante capacidade de otimização adicional está disponível apenas para sistemas de armazenamento EF600 e EF300.

====