---
permalink: sm-storage/what-is-automatic-load-balancing.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ALB, automatic, load, balancing 
summary: O recurso balanceamento de carga automático fornece balanceamento de e/S automatizado e garante que o tráfego de e/S recebido dos hosts seja gerenciado e balanceado dinamicamente entre ambos os controladores. 
---
= O que é balanceamento de carga automático?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O recurso balanceamento de carga automático fornece balanceamento de e/S automatizado e garante que o tráfego de e/S recebido dos hosts seja gerenciado e balanceado dinamicamente entre ambos os controladores.

O recurso balanceamento de carga automático fornece gerenciamento de recursos de e/S aprimorado, reagindo dinamicamente às alterações de carga ao longo do tempo e ajustando automaticamente a propriedade do controlador de volume para corrigir quaisquer problemas de desequilíbrio de carga quando as cargas de trabalho mudam entre os controladores.

A carga de trabalho de cada controlador é continuamente monitorizada e, com a colaboração dos drivers multipath instalados nos hosts, pode ser automaticamente colocada em equilíbrio sempre que necessário. Quando o workload é rebalanceado automaticamente entre os controladores, o administrador de storage fica aliviado da sobrecarga de ajustar manualmente a propriedade do controlador de volume para acomodar alterações de carga no storage array.

Quando o balanceamento de carga automático está ativado, ele executa as seguintes funções:

* Monitora e equilibra automaticamente a utilização de recursos do controlador.
* Ajusta automaticamente a propriedade do controlador de volume quando necessário, otimizando assim a largura de banda de e/S entre os hosts e o storage array.


[NOTE]
====
Qualquer volume atribuído para usar o cache SSD de um controlador não é elegível para uma transferência automática de balanceamento de carga.

====