---
permalink: sm-storage/what-do-i-need-to-know-about-increasing-reserved-capacity.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved, capacity 
summary: Normalmente, você deve aumentar a capacidade quando receber um aviso de que a capacidade reservada corre o risco de ficar cheia. Você pode aumentar a capacidade reservada apenas em incrementos de 8 GiB. 
---
= O que eu preciso saber sobre o aumento da capacidade reservada?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Normalmente, você deve aumentar a capacidade quando receber um aviso de que a capacidade reservada corre o risco de ficar cheia. Você pode aumentar a capacidade reservada apenas em incrementos de 8 GiB.

* Você precisa ter capacidade livre suficiente no pool ou no grupo de volumes para que possa ser expandido, se necessário.
+
Se não houver capacidade livre em nenhum pool ou grupo de volumes, você poderá adicionar capacidade não atribuída na forma de unidades não utilizadas a um pool ou grupo de volumes.

* O volume no pool ou grupo de volumes deve ter um status ideal e não deve estar em nenhum estado de modificação.
* A capacidade livre deve existir no pool ou grupo de volumes que você deseja usar para aumentar a capacidade.
* Não é possível aumentar a capacidade reservada para um volume instantâneo que seja somente leitura. Somente os volumes snapshot que são leitura-gravação exigem capacidade reservada.


Para operações de snapshot, a capacidade reservada geralmente é de 40% do volume base. Para operações de espelhamento assíncrono, a capacidade reservada é de 20% do volume base. Use uma porcentagem maior se você acredita que o volume base sofrerá muitas mudanças ou se a expetativa de vida estimada da operação de serviço de cópia de um objeto de armazenamento será muito longa.
