---
permalink: sm-storage/why-would-i-want-to-manually-configure-a-pool.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, manually, configure, pool 
summary: Os exemplos a seguir descrevem por que você deseja configurar manualmente um pool. 
---
= Por que eu gostaria de configurar manualmente um pool?
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os exemplos a seguir descrevem por que você deseja configurar manualmente um pool.

* Se você tiver vários aplicativos em seu storage array e não quiser que eles concorram para os mesmos recursos de unidade, considere criar manualmente um pool menor para um ou mais aplicativos.
+
Você pode atribuir apenas um ou dois volumes em vez de atribuir a carga de trabalho a um pool grande que tenha muitos volumes para distribuir os dados. A criação manual de um pool separado dedicado ao workload de uma aplicação específica pode permitir que as operações de storage array tenham performance mais rápida, com menos contenção.

+
Para criar manualmente um pool: Selecione *armazenamento* e, em seguida, selecione *pools e grupos de volume*. Na guia All Capacity (todas as capacidades), clique em menu:Create[Pool] (criar [Pool]).

* Se houver vários pools do mesmo tipo de unidade, uma mensagem será exibida indicando que o System Manager não pode recomendar as unidades para um pool automaticamente. No entanto, você pode adicionar manualmente as unidades a um pool existente.
+
Para adicionar manualmente unidades a um pool existente: Na página pools & grupos de volume, selecione o pool e clique em *Adicionar capacidade*.


