---
permalink: sm-storage/why-am-i-seeing-a-capacity-over-allocation-error-when-i-have-enough-free-capacity-in-a-volume-group-to-create-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity, over-allocation, error, 
summary: O grupo de volume selecionado pode ter uma ou mais áreas de capacidade livre. Uma área de capacidade livre é a capacidade livre que pode resultar da exclusão de um volume ou da não utilização de toda a capacidade livre disponível durante a criação do volume. 
---
= Por que estou vendo um erro de superalocação de capacidade quando tenho capacidade livre suficiente em um grupo de volumes para criar volumes?
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O grupo de volume selecionado pode ter uma ou mais áreas de capacidade livre. Uma área de capacidade livre é a capacidade livre que pode resultar da exclusão de um volume ou da não utilização de toda a capacidade livre disponível durante a criação do volume.

Quando você cria um volume em um grupo de volumes que tenha uma ou mais áreas de capacidade livre, a capacidade do volume é limitada à maior área de capacidade livre nesse grupo de volumes. Por exemplo, se um grupo de volume tiver um total de 15 GiB de capacidade livre, e a maior área de capacidade livre for de 10 GiB, o maior volume que você pode criar é de 10 GiB.

Se um grupo de volume tiver áreas de capacidade livre, o gráfico de grupo de volume contém um link indicando o número de áreas de capacidade livre existentes. Selecione o link para exibir um pop-over que indica a capacidade de cada área.

Ao consolidar a capacidade gratuita, você pode criar volumes adicionais a partir da quantidade máxima de capacidade livre em um grupo de volumes. Você pode consolidar a capacidade livre existente em um grupo de volumes selecionado usando um dos seguintes métodos:

* Quando é detetada pelo menos uma área de capacidade livre para um grupo de volumes, a recomendação "consolidar capacidade livre" aparece na página inicial na área de notificação. Clique no link *consolidar capacidade livre* para iniciar a caixa de diálogo.
* Você também pode selecionar menu:pools e grupos de volume[tarefas incomuns > consolidar capacidade livre do grupo de volume] para iniciar a caixa de diálogo.


Se você quiser usar uma área de capacidade livre específica em vez da maior área de capacidade livre, use a interface de linha de comando (CLI).
