---
permalink: sm-storage/why-do-i-need-reserved-capacity-for-every-member-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved, capacity, member, volume 
summary: Cada volume de membro em um grupo de consistência de snapshot deve ter sua própria capacidade reservada para salvar quaisquer modificações feitas pelo aplicativo host no volume base sem afetar a imagem de snapshot do grupo de consistência referenciada. A capacidade reservada fornece ao aplicativo host acesso de gravação a uma cópia dos dados contidos no volume do membro designado como leitura-gravação. 
---
= Por que eu preciso de capacidade reservada para cada volume de membro?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada volume de membro em um grupo de consistência de snapshot deve ter sua própria capacidade reservada para salvar quaisquer modificações feitas pelo aplicativo host no volume base sem afetar a imagem de snapshot do grupo de consistência referenciada. A capacidade reservada fornece ao aplicativo host acesso de gravação a uma cópia dos dados contidos no volume do membro designado como leitura-gravação.

Uma imagem instantânea de grupo de consistência não é diretamente lida ou escrita acessível aos hosts. Em vez disso, a imagem instantânea é usada para salvar apenas os dados capturados do volume base.

Durante a criação de um volume instantâneo de grupo de consistência designado como leitura-gravação, o System Manager cria uma capacidade reservada para cada volume de membro no grupo de consistência. Essa capacidade reservada fornece ao aplicativo host acesso de gravação a uma cópia dos dados contidos na imagem instantânea do grupo de consistência.
