---
permalink: sm-storage/why-dont-i-see-all-my-volumes-hosts-or-host-clusters.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volumes, hosts, host clusters, data assurance 
summary: 'Os volumes instantâneos com um volume base habilitado PARA DA não são elegíveis para serem atribuídos a um host que não seja capaz de Data Assurance (DA). Você deve desativar O DA no volume base antes que um volume instantâneo possa ser atribuído a um host que não seja capaz de DA."' 
---
= Por que não vejo todos os meus volumes, hosts ou clusters de host?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os volumes instantâneos com um volume base habilitado PARA DA não são elegíveis para serem atribuídos a um host que não seja capaz de Data Assurance (DA). Você deve desativar DA no volume base antes que um volume instantâneo possa ser atribuído a um host que não seja capaz de DA.

Considere as seguintes diretrizes para o host ao qual você está atribuindo o volume de snapshot:

* Um host não é capaz de DA se ele estiver conetado ao storage array por meio de uma interface de e/S que não seja capaz de DA.
* Um cluster de host não é capaz de DA se tiver pelo menos um membro de host que não seja capaz de DA.


[NOTE]
====
Não é possível desativar DA em um volume associado a snapshots (grupos de consistência, grupos de snapshot, imagens de snapshot e volumes de snapshot), cópias de volume e espelhos. Todos os objetos snapshot e capacidade reservada associados devem ser excluídos antes que DA possa ser desabilitada no volume base.

====