---
permalink: sm-storage/why-cant-i-choose-another-amount-to-decrease-by.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, decrease, reserved capacity 
summary: Você pode diminuir a capacidade reservada somente pelo valor usado para aumentá-la. A capacidade reservada para volumes membros só pode ser removida na ordem inversa em que foram adicionados. 
---
= Por que não posso escolher outra quantia para diminuir?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode diminuir a capacidade reservada somente pelo valor usado para aumentá-la. A capacidade reservada para volumes membros só pode ser removida na ordem inversa em que foram adicionados.

Não é possível diminuir a capacidade reservada para um objeto de armazenamento se existir uma destas condições:

* Se o objeto de storage for um volume de par espelhado.
* Se o objeto de armazenamento contiver apenas um volume para a capacidade reservada. O objeto de storage deve conter pelo menos dois volumes para a capacidade reservada.
* Se o objeto de armazenamento for um volume instantâneo desativado.
* Se o objeto de armazenamento contiver uma ou mais imagens instantâneas associadas.


Você pode remover volumes para capacidade reservada somente na ordem inversa em que foram adicionados.

Não é possível diminuir a capacidade reservada para um volume instantâneo que seja somente leitura porque não tem nenhuma capacidade reservada associada. Somente os volumes snapshot que são leitura-gravação exigem capacidade reservada.
