---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.90 
summary: Novos recursos no SANtricity os. 
---
= Novidades no SANtricity os 11,90
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
A tabela a seguir descreve os novos recursos no Gerenciador de sistema do SANtricity 11,9.



== Novos recursos na versão 11.90R2

Esta versão contém apenas pequenas alterações e não há novos recursos. Para obter mais informações sobre as alterações nesta versão, consulte o https://library.netapp.com/ecm/ecm_download_file/ECMLP3334464["Notas de versão do e-Series 11,90"^].



== Novos recursos na versão 11.90R1

[cols="35h,~"]
|===
| Novo recurso | Descrição 


 a| 
Novos modelos de sistemas de armazenamento – EF300C e EF600C
 a| 
Esta versão apresenta os sistemas de storage all-flash NVMe EF300C e EF600C. O EF300C e o EF600C são versões flash de alta capacidade dos sistemas de storage EF300 e EF600 existentes. As unidades SSD NVMe de alta capacidade de tamanhos 30TB ou 60TB são compatíveis com o EF300C e o EF600C. O EF300C/EF600C é compatível para uso do Dynamic Disk Pool somente sem suporte a RAID legado.



 a| 
Suporte para interfaces SAS de 12GB GB no EF4000
 a| 
A controladora E4000 agora oferece suporte a placas de interface de host SAS de 12GB GB.

|===


== Novos recursos na versão 11,90

[cols="35h,~"]
|===
| Novo recurso | Descrição 


 a| 
Novo modelo de sistema de armazenamento – E4000
 a| 
Esta versão apresenta o sistema de armazenamento de baixo custo E4000. O E4000 suporta unidades de 12 TB e 60 TB e uma única placa de interface de host (HIC) por controladora. Para a versão inicial, as placas de interface de host suportadas incluem iSCSI e Fibre Channel. Os sistemas de storage E4000 e outros sistemas de storage e-Series podem ser visualizados e gerenciados no Unified Manager.



 a| 
Maior capacidade para Dynamic Disk Pools
 a| 
A capacidade de Dynamic Disk Pools (DDP) foi aumentada para 12 PB sempre que a capacidade de cada uma das unidades individuais no pool for maior que 23 TB de tamanho. Se a capacidade de unidade individual for inferior a 23 TB, a capacidade DDP será de 6 PB.



 a| 
As definições de digitalização de multimédia predefinidas aumentaram
 a| 
A taxa de digitalização de multimédia predefinida foi aumentada para 120 dias.



 a| 
Chave privada agora aceita para gerenciamento de chaves externas
 a| 
O arquivo de solicitação de assinatura de certificado (CSR) gerado externamente por meio de pares de chaves públicas e privadas agora pode ser importado por meio do System Manager.



 a| 
O recurso de bloqueio de login agora está disponível para Serviços Web
 a| 
Configurável somente pela API REST, uma nova configuração de bloqueio de login agora está disponível para serviços Web incorporados e proxy.

|===