---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 12.0 
summary: Novos recursos no SANtricity os. 
---
= Novidades no SANtricity OS 12.0
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
A tabela a seguir descreve os novos recursos no SANtricity System Manager 12.0.



== Novidades na versão 12.0


NOTE: A versão 12.0 do SANtricity OS é compatível apenas com os novos sistemas de storage all-flash EF80 e EF50. Se você estiver usando SANtricity OS 11.9 ou anterior, consulte link:known-issues.html["Problemas conhecidos"] para uma lista de novos recursos das versões anteriores.

[cols="35h,~"]
|===
| Novo recurso | Descrição 


 a| 
Novos modelos de sistema de storage – sistemas de storage all-flash EF80 e EF50
 a| 
Esta versão apresenta os sistemas de storage all-NVMe-flash EF80 e EF50. O EF80 e o EF50 suportam 24 unidades SSD NVMe e uma única placa de interface de host (HIC) por controlador. As interfaces de host NVMe over Fabrics suportadas incluem NVMe over RoCE, NVMe over IB para EF80 e NVMe over FC para EF50. As interfaces SCSI suportadas incluem Fibre Channel.

Unidades SSD NVMe de alta capacidade, de 30TB ou 60TB, também são suportadas com o EF80 e EF30. O EF80 e o EF30 são compatíveis apenas para uso com Dynamic Disk Pool, sem suporte a RAID legado.



 a| 
Nova interface de usuário para SANtricity System Manager
 a| 
Para os novos controladores EF80 e EF50, a interface de usuário do SANtricity System Manager foi redesenhada para oferecer uma aparência e experiência mais modernas. A nova interface inclui navegação no painel esquerdo e usabilidade aprimorada para simplificar as tarefas de gerenciamento.


NOTE: A nova interface de usuário está disponível atualmente apenas para os sistemas de storage EF80 e EF50 com o lançamento do SANtricity 12.0. Se você estiver usando SANtricity 11.9 ou anterior, consulte link:https://docs.netapp.com/us-en/e-series-santricity-119/system-manager/index.html["Gerenciador de sistemas SANtricity 11,9"] para obter instruções sobre como usar a interface de usuário legada.



 a| 
Subject Alternative Names (SANs) para certificado de servidor agora permitem apenas letras, dígitos e caracteres de hífen
 a| 
Ao criar ou editar um certificado de servidor no SANtricity System Manager ou Unified Manager, o campo Subject Alternative Names (SANs) agora permite apenas letras, dígitos e hífens. Essa alteração aprimora a segurança e garante a compatibilidade com os padrões do setor para certificados SSL/TLS.



 a| 
O tamanho do segmento do Dynamic Disk Pools agora é definido como 32K por padrão para sistemas baseados em SSD e NVMe
 a| 
Para Dynamic Disk Pools em sistemas baseados em SSD e NVMe, o tamanho padrão do segmento foi alterado para 32K. Anteriormente, o tamanho padrão do segmento dos Dynamic Disk Pools era fixo em 128K para esses sistemas. Essa alteração otimiza o desempenho para cargas de trabalho que envolvem uma combinação de operações de E/S pequenas e grandes.



 a| 
Editor de scripts agora disponível no SANtricity System Manager
 a| 
Um novo editor de scripts já está disponível no SANtricity System Manager. O editor de scripts permite criar ou editar um arquivo de script, salvar um arquivo de script no disco local da estação de gerenciamento de storage ou carregar um arquivo de script do disco. O editor de scripts oferece recursos de verificação de sintaxe e execução de comandos para gerenciar seu sistema de storage. Para mais informações, consulte link:sm-support/use-script-editor.html["Usando o editor de script"^].

|===