---
permalink: sm-mirroring/asynchronous-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, asynchronous, mirroring, terms, 
summary: Saiba como os termos do espelhamento assíncrono se aplicam ao storage array. 
---
= Aprenda sobre a terminologia de espelhamento assíncrono no software SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba como os termos do espelhamento assíncrono se aplicam ao storage array.

[cols="25h,~"]
|===
| Prazo | Descrição 


 a| 
Storage array local
 a| 
O storage array local é o storage array em que você está agindo.

Quando você vê *Primary* na coluna de função local, indica que o storage array contém o volume que detém a função primária na relação de espelhamento. Quando você vê *secundário* na coluna função local, indica que a matriz de armazenamento contém o volume que detém a função secundária na relação de espelhamento.



 a| 
Grupo de consistência do espelho
 a| 
Um grupo de consistência de espelho é um recipiente para um ou mais pares espelhados. Para operações de espelhamento assíncrono, você precisa criar um grupo de consistência de espelhamento.



 a| 
Par espelhado
 a| 
Um par espelhado é composto por dois volumes, um volume primário e um volume secundário.

No espelhamento assíncrono, um par espelhado sempre pertence a um grupo de consistência de espelho. As operações de gravação são executadas primeiro no volume primário e, em seguida, replicadas no volume secundário. Cada par espelhado em um grupo de consistência de espelho compartilha as mesmas configurações de sincronização.



 a| 
Volume primário
 a| 
O volume primário de um par espelhado é o volume de origem a ser espelhado.



 a| 
Storage array remoto
 a| 
O storage array remoto geralmente é designado como local secundário, que geralmente contém uma réplica dos dados em uma configuração de espelhamento.



 a| 
Capacidade reservada
 a| 
A capacidade reservada é a capacidade alocada física usada para qualquer operação de serviço de cópia e objeto de storage. Não é diretamente legível pelo host.



 a| 
Mudança de função
 a| 
A mudança de função está atribuindo a função primária ao volume secundário e vice-versa.



 a| 
Volume secundário
 a| 
O volume secundário de um par espelhado geralmente está localizado em um local secundário e contém uma réplica dos dados.



 a| 
Sincronização
 a| 
A sincronização ocorre na sincronização inicial entre o storage array local e o storage array remoto. A sincronização também ocorre quando os volumes primário e secundário ficam não sincronizados após uma interrupção da comunicação. Quando o link de comunicação está funcionando novamente, todos os dados não replicados são sincronizados com o storage array do volume secundário.

|===