---
permalink: sm-mirroring/asynchronous-mirroring-why-dont-i-see-all-my-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, asynchronous, volumes 
summary: Ao selecionar um volume primário para um par espelhado, uma lista mostra todos os volumes elegíveis. 
---
= Espelhamento assíncrono - por que não vejo todos os meus volumes?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao selecionar um volume primário para um par espelhado, uma lista mostra todos os volumes elegíveis.

Quaisquer volumes que não sejam elegíveis para serem usados não são exibidos nessa lista. Os volumes não podem ser elegíveis por qualquer um dos seguintes motivos:

* O volume não é ideal.
* O volume já está participando de uma relação de espelhamento.
* Para volumes finos, a expansão automática deve estar ativada.



NOTE: Para controladores EF600 e EF300, os volumes primário e secundário de um par espelhado assíncrono devem corresponder ao mesmo protocolo, nível da bandeja, tamanho do segmento, tipo de segurança e nível RAID. Pares espelhados assíncronos não elegíveis não aparecerão na lista de volumes disponíveis.
