---
permalink: sm-mirroring/deactivate-synchronous-mirroring.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, deactivate, synchronous, mirroring, adapter, host, bus, 
summary: 'Você pode desativar o recurso de espelhamento síncrono em um storage array para restabelecer o uso normal da porta host 4 do adaptador de barramento do host (HBA), que foi reservada para transmissão de dados espelhados.' 
---
= Desativar o espelhamento síncrono
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode desativar o recurso de espelhamento síncrono em um storage array para restabelecer o uso normal da porta host 4 do adaptador de barramento do host (HBA), que foi reservada para transmissão de dados espelhados.

.Antes de começar
Você deve ter excluído todas as relações espelhadas síncronas. Verifique se todos os pares espelhados foram excluídos do storage array.

.Passos
. Selecione menu:armazenamento[Espelhamento síncrono].
. Selecione menu:tarefas incomuns[Desativar].
+
O sistema apresenta uma confirmação.

. Selecione *Sim* para confirmar.


.Resultados
* A porta de host HBA 4 da controladora, dedicada à comunicação de espelhamento síncrono, agora pode aceitar solicitações de leitura e gravação do host.
* Os volumes de capacidade reservada no storage array são excluídos.

