---
permalink: sm-mirroring/faq-async-mirroring.html 
sidebar: sidebar 
keywords:  
summary: Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta. 
---
= Perguntas frequentes sobre espelhamento assíncrono para o SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta.



== Como o espelhamento assíncrono difere do espelhamento síncrono?

O recurso de espelhamento assíncrono difere do recurso de espelhamento síncrono de uma maneira essencial: Captura o estado do volume de origem em um determinado ponto no tempo e copia apenas os dados que foram alterados desde a última captura de imagem.

Com o espelhamento síncrono, o estado do volume primário não é capturado em algum momento do tempo, mas sim reflete todas as alterações que foram feitas no volume primário para o volume secundário. O volume secundário é idêntico ao volume primário a cada momento porque, com este tipo de espelho, cada vez que uma gravação é feita no volume primário, uma gravação é feita no volume secundário. O host não recebe uma confirmação de que a gravação foi bem-sucedida até que o volume secundário seja atualizado com êxito com as alterações feitas no volume primário.

Com o espelhamento assíncrono, o storage array remoto não é totalmente sincronizado com o storage array local. Portanto, se o aplicativo precisar fazer a transição para o storage array remoto devido à perda do storage array local, algumas transações poderão ser perdidas.

Comparação entre os recursos de espelhamento:

[cols="1a,1a"]
|===
| Espelhamento assíncrono | Espelhamento síncrono 


 a| 
*Método de replicação*



 a| 
* *Ponto no tempo*
+
O espelhamento é feito sob demanda ou automaticamente de acordo com uma programação definida pelo usuário. Os horários podem ser definidos na granularidade de minutos. O tempo mínimo entre sincronizações é de 10 minutos.


 a| 
* *Contínuo*
+
O espelhamento é executado automaticamente continuamente, copiando dados de cada gravação do host.





 a| 
*Capacidade reservada*



 a| 
* *Múltiplo*
+
Um volume de capacidade reservada é necessário para cada par espelhado.


 a| 
* *Single*
+
É necessário um único volume de capacidade reservada para todos os volumes espelhados.





 a| 
*Comunicação*



 a| 
* *ISCSI e Fibre Channel*
+
Suporta interfaces iSCSI e Fibre Channel entre storage arrays.


 a| 
* *Fibre Channel*
+
Suporta apenas interfaces Fibre Channel entre storage arrays.





 a| 
*Distância*



 a| 
* *Ilimitado*
+
Suporte para distâncias praticamente ilimitadas entre a matriz de armazenamento local e a matriz de armazenamento remoto, com a distância normalmente limitada apenas pelos recursos da rede e da tecnologia de extensão de canal.


 a| 
* *Restrito*
+
Normalmente, deve estar a cerca de 10 km (6,2 milhas) do storage array local para atender aos requisitos de latência e desempenho do aplicativo.



|===


== Por que não consigo acessar o recurso de espelhamento escolhido?

O espelhamento é configurado na interface do SANtricity Unified Manager.

[NOTE]
====
O espelhamento síncrono não está disponível no storage array EF600/EF600C ou EF300/EF300C.

====
Para ativar e configurar o espelhamento entre dois arrays, verifique o seguinte:

* O serviço Web Services Proxy deve estar em execução. (O Unified Manager é instalado em um sistema host juntamente com o Web Services Proxy.)
* O Unified Manager deve estar em execução em seu host local por meio de uma conexão HTTPS.
* Os dois storage arrays que você deseja usar para espelhamento devem ser descobertos no Unified Manager.
* O Unified Manager deve ter certificados SSL válidos para as matrizes de armazenamento. Você pode aceitar um certificado autoassinado ou instalar certificados assinados pela CA do Unified Manager.


Para obter instruções de configuração, consulte o seguinte:

* link:../um-manage/create-asynchronous-mirrored-pair-um.html["Criar par espelhado assíncrono (no Unified Manager)"]
* link:../um-manage/create-synchronous-mirrored-pair-um.html["Criar par espelhado síncrono (no Unified Manager)"]




== O que eu preciso saber antes de criar um grupo de consistência de espelho?

Siga estas diretrizes antes de criar um grupo de consistência espelhada.

[NOTE]
====
O espelhamento síncrono não está disponível no sistema de storage EF600/EF600C ou EF300/EF300C.

====
Você cria um grupo de consistência no Unified Manager no assistente criar pares espelhados.

Atender aos seguintes requisitos do Unified Manager:

* O serviço Web Services Proxy deve estar em execução.
* O Unified Manager deve estar em execução em seu host local por meio de uma conexão HTTPS.
* O Unified Manager deve mostrar certificados SSL válidos para a matriz de armazenamento. Você pode aceitar um certificado autoassinado ou instalar seu próprio certificado de segurança usando o Unified Manager e navegando para o menu:certificado[Gerenciamento de certificados].


Certifique-se também de atender aos seguintes requisitos para matrizes de armazenamento:

* Os dois storage arrays devem ser descobertos no Unified Manager.
* Cada storage array deve ter duas controladoras.
* Cada controlador no array primário e no array secundário deve ter uma porta de gerenciamento Ethernet configurada e estar conetado à rede.
* As matrizes de armazenamento têm uma versão mínima de firmware de 7,84. (Cada um deles pode executar diferentes versões do sistema operacional.)
* Você deve saber a senha para os storages de armazenamento local e remoto.
* Seus storage arrays locais e remotos são conectados por meio de uma malha Fibre Channel ou de uma interface iSCSI.




== Espelhamento assíncrono - o que preciso saber antes de criar um par espelhado?

Você configura pares espelhados na interface do Gerenciador Unificado do SANtricity e gerencia os pares no Gerenciador de sistemas do SANtricity.

Antes de criar um par espelhado, siga estas diretrizes.

* Você precisa ter dois storage arrays.
* Cada storage array deve ter duas controladoras.
* Cada controlador no array primário e no array secundário deve ter uma porta de gerenciamento Ethernet configurada e estar conetado à rede.
* Seus storage arrays locais e remotos são conectados por meio de uma malha Fibre Channel ou de uma interface iSCSI.
* As matrizes de armazenamento têm uma versão mínima de firmware de 7,84. (Cada um deles pode executar diferentes versões do sistema operacional.)
* Você deve saber a senha para os storages de armazenamento local e remoto.
* Você precisa ter capacidade livre suficiente no storage array remoto para criar um volume secundário igual ou maior que o volume principal que deseja espelhar.
* Você instalou o Web Services Proxy e o Unified Manager. Os pares espelhados são configurados na interface do Unified Manager.
* Os dois storage arrays são descobertos no Unified Manager.
* Seu storage array deve conter pelo menos um grupo de consistência de espelho. Você cria um grupo de consistência no Unified Manager no assistente criar pares espelhados.




== O que eu preciso saber antes de aumentar minha capacidade reservada em um volume de par espelhado?

Normalmente, você deve aumentar a capacidade reservada quando receber um aviso de que a capacidade reservada para um par espelhado está ficando cheia. Você pode aumentar a capacidade reservada apenas em incrementos de 8 GiB.

Para operações de espelhamento assíncrono, a capacidade reservada costuma ser de 20% do volume base. Escolha uma capacidade maior para a capacidade reservada se uma ou ambas as condições existirem:

* Você pretende manter o par espelhado por um longo período de tempo.
* Uma grande porcentagem de blocos de dados mudará no volume primário devido à intensa atividade de e/S. Use dados históricos de desempenho ou outros utilitários do sistema operacional para ajudá-lo a determinar a atividade típica de e/S para o volume principal.


Você pode aumentar a capacidade reservada para um par espelhado executando uma destas ações:

* Ajuste a porcentagem de capacidade para um volume de par espelhado selecionando menu:armazenamento[pools and volumes groups] e clicando na guia *capacidade reservada*.
* Crie um novo volume usando a capacidade gratuita disponível em um pool ou grupo de volumes.
+
Se não houver capacidade livre em nenhum pool ou grupo de volumes, você poderá adicionar capacidade não configurada na forma de unidades não utilizadas a um pool ou grupo de volumes.





== Por que não consigo aumentar a capacidade reservada com a quantidade solicitada?

Você pode aumentar a capacidade reservada apenas em incrementos de 4 GiB.

Reveja as seguintes diretrizes:

* Você precisa ter capacidade livre suficiente no pool ou no grupo de volumes para que possa ser expandido, se necessário.
+
Se não houver capacidade livre em nenhum pool ou grupo de volumes, você poderá adicionar capacidade não atribuída na forma de unidades não utilizadas a um pool ou grupo de volumes.

* O volume no pool ou grupo de volumes deve ter um status ideal e não deve estar em nenhum estado de modificação.
* A capacidade livre deve existir no pool ou grupo de volumes que você deseja usar para aumentar a capacidade.


Para operações de espelhamento assíncrono, a capacidade reservada é de 20% do volume base. Use uma porcentagem maior se você acredita que o volume base sofrerá muitas mudanças ou se a expetativa de vida estimada da operação de serviço de cópia de um objeto de armazenamento será muito longa.



== Por que eu alteraria essa porcentagem?

A capacidade reservada geralmente é de 40% do volume base para operações de snapshot e 20% do volume base para operações de espelhamento assíncrono.

Normalmente, essa capacidade é suficiente. A capacidade necessária varia, dependendo da frequência e tamanho das gravações de e/S no volume base e quanto tempo você pretende usar a operação de serviço de cópia do objeto de armazenamento.

Em geral, escolha uma porcentagem maior para a capacidade reservada se uma ou ambas as condições existirem:

* Se a vida útil de uma operação de serviço de cópia de um objeto de armazenamento específico será muito longa.
* Se uma grande porcentagem de blocos de dados mudar no volume base devido à intensa atividade de e/S. Use dados históricos de desempenho ou outros utilitários do sistema operacional para ajudá-lo a determinar a atividade típica de e/S para o volume base.




== Por que vejo mais de um candidato à capacidade reservada?

Se houver mais de um volume em um pool ou grupo de volumes que atenda ao valor percentual de capacidade selecionado para o objeto de armazenamento, você verá vários candidatos.

Você pode atualizar a lista de candidatos recomendados alterando a porcentagem de espaço físico da unidade que deseja reservar no volume base para operações de serviço de cópia. Os melhores candidatos são exibidos com base na sua seleção.



== Por que vejo valores não disponíveis exibidos na tabela?

A tabela lista valores não disponíveis quando os dados localizados na matriz de armazenamento remoto não estão disponíveis para serem exibidos.

Para exibir os dados do storage array remoto, inicie o System Manager do Unified Manager.



== Por que não vejo todos os meus pools e grupos de volumes?

Quando você cria um volume secundário para o par espelhado assíncrono, o sistema exibe uma lista de todos os pools qualificados e grupos de volumes para esse par espelhado assíncrono. Qualquer pool ou grupo de volume que não seja elegível para ser usado não é exibido nessa lista.

Pools ou grupos de volumes podem não ser elegíveis por qualquer um dos seguintes motivos.

* Os recursos de segurança de um pool ou grupo de volumes não correspondem.
* Um pool ou grupo de volume está em um estado não ideal.
* A capacidade de um pool ou grupo de volume é muito pequena.




== Espelhamento assíncrono - Por que não vejo todos os meus volumes?

Ao selecionar um volume primário para um par espelhado, uma lista mostra todos os volumes elegíveis.

Quaisquer volumes que não sejam elegíveis para serem usados não são exibidos nessa lista. Os volumes não podem ser elegíveis por qualquer um dos seguintes motivos:

* O volume não é ideal.
* O volume já está participando de uma relação de espelhamento.
* Para volumes finos, a expansão automática deve estar ativada.



NOTE: Para controladores EF600 e EF300, os volumes primário e secundário de um par espelhado assíncrono devem corresponder ao mesmo protocolo, nível da bandeja, tamanho do segmento, tipo de segurança e nível RAID. Pares espelhados assíncronos não elegíveis não aparecerão na lista de volumes disponíveis.



== Espelhamento assíncrono - Por que não vejo todos os volumes no array de armazenamento remoto?

Quando você está selecionando um volume secundário no storage array remoto, uma lista mostra todos os volumes elegíveis para esse par espelhado.

Quaisquer volumes que não sejam elegíveis para serem usados, não serão exibidos nessa lista. Os volumes podem não ser elegíveis por qualquer um dos seguintes motivos:

* O volume não é ideal.
* O volume já está participando de uma relação de espelhamento.
* Os atributos de volume fino entre o volume primário e o volume secundário não correspondem.
* Se estiver a utilizar o Data Assurance (DA), o volume primário e o volume secundário têm de ter as mesmas definições DE DA.
+
** Se o volume primário for DA ativado, o volume secundário tem de ser DA ativado.
** Se o volume primário não estiver ativado DA, o volume secundário não deve ser ativado DA.






== Por que eu atualizaria o endereço IP do meu array de armazenamento remoto?

Você atualiza o endereço IP da matriz de armazenamento remoto quando o endereço IP de uma porta iSCSI muda e a matriz de armazenamento local não consegue se comunicar com a matriz de armazenamento remoto.

Ao estabelecer uma relação de espelhamento assíncrono com uma conexão iSCSI, os storage arrays locais e remotos armazenam um Registro do endereço IP do storage array remoto na configuração de espelhamento assíncrono. Se o endereço IP de uma porta iSCSI mudar, o storage de armazenamento remoto que está tentando usar essa porta encontra um erro de comunicação.

A matriz de armazenamento com o endereço IP alterado envia uma mensagem para cada matriz de armazenamento remoto associada aos grupos de consistência de espelho configurados para espelhar uma conexão iSCSI. As matrizes de armazenamento que recebem esta mensagem atualizam automaticamente o endereço IP de destino remoto.

Se a matriz de armazenamento com o endereço IP alterado não puder enviar sua mensagem entre arrays para um storage remoto, o sistema enviará um alerta sobre o problema de conetividade. Use a opção Atualizar endereço IP remoto para restabelecer a conexão com a matriz de armazenamento local.
