---
permalink: sm-mirroring/how-does-asynchronous-mirroring-differ-from-synchronous-mirroring-sync.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, asynchronous, mirroring, differ, synchronous, mirroring, 
summary: 'O recurso de espelhamento assíncrono difere do recurso de espelhamento síncrono de uma maneira essencial: Captura o estado do volume de origem em um determinado ponto no tempo e copia apenas os dados que foram alterados desde a última captura de imagem.' 
---
= Como o espelhamento assíncrono difere do espelhamento síncrono?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O recurso de espelhamento assíncrono difere do recurso de espelhamento síncrono de uma maneira essencial: Captura o estado do volume de origem em um determinado ponto no tempo e copia apenas os dados que foram alterados desde a última captura de imagem.

Com o espelhamento síncrono, o estado do volume primário não é capturado em algum momento do tempo, mas sim reflete todas as alterações que foram feitas no volume primário para o volume secundário. O volume secundário é idêntico ao volume primário a cada momento porque, com este tipo de espelho, cada vez que uma gravação é feita no volume primário, uma gravação é feita no volume secundário. O host não recebe uma confirmação de que a gravação foi bem-sucedida até que o volume secundário seja atualizado com êxito com as alterações feitas no volume primário.

Com o espelhamento assíncrono, o storage array remoto não é totalmente sincronizado com o storage array local. Portanto, se o aplicativo precisar fazer a transição para o storage array remoto devido à perda do storage array local, algumas transações poderão ser perdidas.

Comparação entre os recursos de espelhamento:

[cols="1a,1a"]
|===
| Espelhamento assíncrono | Espelhamento síncrono 


 a| 
*Método de replicação*



 a| 
* *Ponto no tempo*
+
O espelhamento é feito sob demanda ou automaticamente de acordo com uma programação definida pelo usuário. Os horários podem ser definidos na granularidade de minutos. O tempo mínimo entre sincronizações é de 10 minutos.


 a| 
* *Contínuo*
+
O espelhamento é executado automaticamente continuamente, copiando dados de cada gravação do host.





 a| 
*Capacidade reservada*



 a| 
* *Múltiplo*
+
Um volume de capacidade reservada é necessário para cada par espelhado.


 a| 
* *Single*
+
É necessário um único volume de capacidade reservada para todos os volumes espelhados.





 a| 
*Comunicação*



 a| 
* *ISCSI e Fibre Channel*
+
Suporta interfaces iSCSI e Fibre Channel entre storage arrays.


 a| 
* *Fibre Channel*
+
Suporta apenas interfaces Fibre Channel entre storage arrays.





 a| 
*Distância*



 a| 
* *Ilimitado*
+
Suporte para distâncias praticamente ilimitadas entre a matriz de armazenamento local e a matriz de armazenamento remoto, com a distância normalmente limitada apenas pelos recursos da rede e da tecnologia de extensão de canal.


 a| 
* *Restrito*
+
Normalmente, deve estar a cerca de 10 km (6,2 milhas) do storage array local para atender aos requisitos de latência e desempenho do aplicativo.



|===