---
permalink: sm-mirroring/suspend-and-resume-synchronization-for-a-mirrored-pair.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, suspend, resume, synchronization, mirrored, pair, 
summary: Você pode usar a opção suspender e a opção continuar para controlar quando sincronizar os dados no volume primário e no volume secundário em um par espelhado. 
---
= Suspender e retomar a sincronização para pares espelhados no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar a opção suspender e a opção continuar para controlar quando sincronizar os dados no volume primário e no volume secundário em um par espelhado.

.Sobre esta tarefa
Se um par espelhado for suspenso manualmente, o par espelhado não será sincronizado até que seja retomado manualmente.

.Passos
. Selecione menu:armazenamento[Espelhamento síncrono].
. Selecione o par espelhado que pretende suspender ou retomar e, em seguida, selecione menu:mais[suspender] ou menu:mais[continuar].
+
O sistema apresenta uma confirmação.

. Selecione *Sim* para confirmar.


.Resultados
O System Manager executa as seguintes ações:

* Suspende ou retoma a transferência de dados entre o par espelhado sem remover a relação de espelhamento.
* Para um par espelhado _suspenso_:
+
** Exibe *suspenso* na tabela par espelhado.
** Registra todos os dados que foram gravados no volume primário do par espelhado enquanto a sincronização é suspensa.


* Para um par espelhado _retomado_, grava os dados automaticamente no volume secundário do par espelhado quando a sincronização é retomada. Não é necessária uma sincronização completa.

