---
permalink: sm-mirroring/synchronous-mirroring-why-dont-i-see-all-the-volumes-on-the-remote-storage-array.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, synchronous, mirroring, 
summary: Quando você está selecionando um volume secundário no storage array remoto, uma lista mostra todos os volumes elegíveis para esse par espelhado. 
---
= Espelhamento síncrono - por que não vejo todos os volumes no storage array remoto?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você está selecionando um volume secundário no storage array remoto, uma lista mostra todos os volumes elegíveis para esse par espelhado.

Quaisquer volumes que não sejam elegíveis para serem usados, não serão exibidos nessa lista. Os volumes podem não ser elegíveis por qualquer um dos seguintes motivos:

* O volume é um volume não padrão, como um volume instantâneo ou um volume fino.
* O volume não é ideal.
* O volume já está participando de uma relação de espelhamento.
* Se estiver a utilizar o Data Assurance (DA), o volume primário e o volume secundário têm de ter as mesmas definições DE DA.
+
** Se o volume primário for DA ativado, o volume secundário tem de ser DA ativado.
** Se o volume primário não estiver ativado DA, o volume secundário não deve ser ativado DA.



