---
permalink: sm-mirroring/what-do-i-need-to-know-before-increasing-my-reserved-capacity-on-a-mirrored-pair-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved, capacity, mirrored, pair, volume, 
summary: Normalmente, você deve aumentar a capacidade reservada quando receber um aviso de que a capacidade reservada para um par espelhado está ficando cheia. Você pode aumentar a capacidade reservada apenas em incrementos de 8 GiB. 
---
= O que eu preciso saber antes de aumentar minha capacidade reservada em um volume de par espelhado?
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Normalmente, você deve aumentar a capacidade reservada quando receber um aviso de que a capacidade reservada para um par espelhado está ficando cheia. Você pode aumentar a capacidade reservada apenas em incrementos de 8 GiB.

Para operações de espelhamento assíncrono, a capacidade reservada costuma ser de 20% do volume base. Escolha uma capacidade maior para a capacidade reservada se uma ou ambas as condições existirem:

* Você pretende manter o par espelhado por um longo período de tempo.
* Uma grande porcentagem de blocos de dados mudará no volume primário devido à intensa atividade de e/S. Use dados históricos de desempenho ou outros utilitários do sistema operacional para ajudá-lo a determinar a atividade típica de e/S para o volume principal.


Você pode aumentar a capacidade reservada para um par espelhado executando uma destas ações:

* Ajuste a porcentagem de capacidade para um volume de par espelhado selecionando menu:armazenamento[pools and volumes groups] e clicando na guia *capacidade reservada*.
* Crie um novo volume usando a capacidade gratuita disponível em um pool ou grupo de volumes.
+
Se não houver capacidade livre em nenhum pool ou grupo de volumes, você poderá adicionar capacidade não configurada na forma de unidades não utilizadas a um pool ou grupo de volumes.


