---
permalink: sm-mirroring/what-do-i-need-to-know-before-creating-a-mirror-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, mirror, consistency, group, 
summary: Siga estas diretrizes antes de criar um grupo de consistência espelhada. 
---
= O que eu preciso saber antes de criar um grupo de consistência de espelho?
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estas diretrizes antes de criar um grupo de consistência espelhada.

[NOTE]
====
O espelhamento síncrono não está disponível no sistema de storage EF600/EF600C ou EF300/EF300C.

====
Você cria um grupo de consistência no Unified Manager no assistente criar pares espelhados.

Atender aos seguintes requisitos do Unified Manager:

* O serviço Web Services Proxy deve estar em execução.
* O Unified Manager deve estar em execução em seu host local por meio de uma conexão HTTPS.
* O Unified Manager deve mostrar certificados SSL válidos para a matriz de armazenamento. Você pode aceitar um certificado autoassinado ou instalar seu próprio certificado de segurança usando o Unified Manager e navegando para o menu:certificado[Gerenciamento de certificados].


Certifique-se também de atender aos seguintes requisitos para matrizes de armazenamento:

* Os dois storage arrays devem ser descobertos no Unified Manager.
* Cada storage array deve ter duas controladoras.
* Cada controlador no array primário e no array secundário deve ter uma porta de gerenciamento Ethernet configurada e estar conetado à rede.
* As matrizes de armazenamento têm uma versão mínima de firmware de 7,84. (Cada um deles pode executar diferentes versões do sistema operacional.)
* Você deve saber a senha para os storages de armazenamento local e remoto.
* Seus storage arrays locais e remotos são conectados por meio de uma malha Fibre Channel ou de uma interface iSCSI.

