---
permalink: sm-mirroring/why-would-i-update-my-remote-storage-arrays-ip-address.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, update, remote, ip, address, 
summary: Você atualiza o endereço IP da matriz de armazenamento remoto quando o endereço IP de uma porta iSCSI muda e a matriz de armazenamento local não consegue se comunicar com a matriz de armazenamento remoto. 
---
= Por que eu atualizaria o endereço IP da minha matriz de armazenamento remoto?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você atualiza o endereço IP da matriz de armazenamento remoto quando o endereço IP de uma porta iSCSI muda e a matriz de armazenamento local não consegue se comunicar com a matriz de armazenamento remoto.

Ao estabelecer uma relação de espelhamento assíncrono com uma conexão iSCSI, os storage arrays locais e remotos armazenam um Registro do endereço IP do storage array remoto na configuração de espelhamento assíncrono. Se o endereço IP de uma porta iSCSI mudar, o storage de armazenamento remoto que está tentando usar essa porta encontra um erro de comunicação.

A matriz de armazenamento com o endereço IP alterado envia uma mensagem para cada matriz de armazenamento remoto associada aos grupos de consistência de espelho configurados para espelhar uma conexão iSCSI. As matrizes de armazenamento que recebem esta mensagem atualizam automaticamente o endereço IP de destino remoto.

Se a matriz de armazenamento com o endereço IP alterado não puder enviar sua mensagem entre arrays para um storage remoto, o sistema enviará um alerta sobre o problema de conetividade. Use a opção Atualizar endereço IP remoto para restabelecer a conexão com a matriz de armazenamento local.
