---
permalink: sm-mirroring/workflow-for-mirroring-a-volume-asynchronously.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, workflow, mirroring, asynchronously, 
summary: Você configura o espelhamento assíncrono usando o fluxo de trabalho a seguir. 
---
= Espelhar um volume de forma assíncrona no software SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você configura o espelhamento assíncrono usando o fluxo de trabalho a seguir.

. Execute a configuração inicial no Unified Manager:
+
.. Selecione a matriz de armazenamento local como a origem para a transferência de dados.
.. Crie ou selecione um grupo de consistência de espelho existente, que é um contentor para o volume primário no array local e o volume secundário no array remoto. Os volumes primário e secundário são referidos como o "par espelhado". Se você estiver criando o grupo de consistência de espelho pela primeira vez, especifique se deseja executar sincronizações manuais ou agendadas.
.. Selecione um volume primário no storage array local e, em seguida, determine sua capacidade reservada. A capacidade reservada é a capacidade física alocada a ser usada para a operação de cópia.
.. Selecione um storage array remoto como o destino da transferência, um volume secundário e, em seguida, determine sua capacidade reservada.
.. Inicie a transferência de dados inicial do volume primário para o volume secundário. Dependendo do tamanho do volume, esta transferência inicial pode demorar várias horas.


. Verifique o progresso da sincronização inicial:
+
.. No Unified Manager, inicie o System Manager para o array local.
.. No System Manager, visualize o status da operação de espelhamento. Quando o espelhamento estiver concluído, o status do par espelhado é "ótimo".


. *Opcional:* você pode reagendar ou realizar manualmente transferências de dados subsequentes no System Manager. Somente blocos novos e alterados são transferidos do volume primário para o volume secundário.
+
[NOTE]
====
Como a replicação assíncrona é periódica, o sistema pode consolidar os blocos alterados e conservar a largura de banda da rede. Há impacto mínimo na taxa de transferência de gravação e na latência de gravação.

====

