---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, admin password 
summary: Você deve configurar o storage array com uma senha de administrador para protegê-lo contra acesso não autorizado. 
---
= Gerenciar a proteção por senha
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar o storage array com senhas para protegê-lo contra acesso não autorizado.



== Definir e alterar senhas

Ao iniciar o System Manager pela primeira vez, você será solicitado a definir uma senha de administrador. Qualquer usuário que tenha a senha de administrador pode fazer alterações de configuração na matriz de armazenamento, como adicionar, alterar ou remover objetos ou configurações. Para definir a senha de administrador durante a inicialização inicial, link:../san-getstarted/access-sam.html["Acesse o System Manager"]consulte .

Por razões de segurança, você pode tentar inserir uma senha apenas cinco vezes antes que o storage de armazenamento entre em um estado de "bloqueio". Nesse estado, o storage array rejeitará tentativas subsequentes de senha. Você deve esperar 10 minutos para que a matriz de armazenamento seja redefinida para um estado "normal" antes de tentar digitar uma senha novamente.

Além da senha de administrador, o storage array inclui perfis de usuário predefinidos com uma ou mais funções mapeadas para eles. Para obter mais informações, link:../sm-settings/permissions-for-mapped-roles.html["Permissões para funções mapeadas"]consulte . Os perfis de usuário e mapeamentos não podem ser alterados. Apenas as senhas podem ser modificadas. Se pretender alterar a palavra-passe de administrador ou outras palavras-passe de utilizador, link:../sm-settings/change-passwords.html["Alterar senhas"]consulte .



== Volte a introduzir palavras-passe após os tempos limite da sessão

O sistema solicita a senha apenas uma vez durante uma única sessão de gerenciamento. No entanto, uma sessão expira após 30 minutos de inatividade, altura em que deve introduzir novamente a palavra-passe. Se outro usuário que gerencia o mesmo storage array de outro cliente de gerenciamento alterar a senha enquanto sua sessão estiver em andamento, você será solicitado a digitar uma senha da próxima vez que tentar uma operação de configuração ou uma operação de exibição.

Você pode ajustar o tempo limite da sessão ou desativar completamente os tempos limite da sessão. link:../sm-settings/manage-session-timeouts-sam.html["Gerenciar tempos limite de sessão"]Consulte .



== Remova as unidades ou a proteção por senha

Se você remover unidades protegidas por senha ou quiser desativar a proteção por senha, tenha em atenção o seguinte:

* *Se você remover unidades com proteção por senha* -- a senha é armazenada em uma área reservada de cada unidade no storage de armazenamento. Se você remover todas as unidades de um storage array, sua senha não funcionará mais. Para corrigir essa condição, reinstale uma das unidades originais no storage de armazenamento.
* *Se você quiser remover a proteção por senha* -- se você não quiser mais ter comandos protegidos por senha, digite a senha atual do administrador e deixe as caixas de texto da nova senha em branco.


[CAUTION]
====
Executar comandos de configuração em um storage array pode causar sérios danos, incluindo perda de dados. Por esse motivo, você sempre deve definir uma senha de administrador para o storage array. Use uma senha de administrador longa com pelo menos 15 carateres alfanuméricos para aumentar a segurança.

====