---
permalink: sm-interface/faq-storage-system-setup.html 
sidebar: sidebar 
keywords:  
summary: Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta. 
---
= Perguntas frequentes sobre configuração do sistema de armazenamento para o SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta.



== E se eu não conseguir ver todos os meus componentes de hardware?

Se você não vir todos os componentes de hardware na caixa de diálogo verificar hardware, isso pode significar que um compartimento de unidade não está conetado corretamente ou que um compartimento incompatível está instalado no storage de armazenamento.

Verifique se todos os compartimentos de unidades estão conetados corretamente. Se você não tiver certeza sobre quais gavetas de unidade são compatíveis, entre em Contato com o suporte técnico.



== E se eu não vir todos os meus hosts?

Se você não vir seus hosts conetados, a deteção automática falhou, os hosts estão conetados incorretamente ou nenhum host está conetado atualmente.

Você pode configurar os hosts mais tarde, uma vez que você terminar com a configuração. Você pode criar hosts manualmente da seguinte forma:

* Você pode criar manualmente hosts e associar os identificadores de porta de host apropriados acessando o menu:armazenamento[hosts]. Os hosts que foram criados manualmente também são exibidos no assistente *Initial Setup*.
* O destino e o host devem ser configurados para o tipo de porta do host (por exemplo, iSCSI ou NVMe sobre RoCE) e uma sessão para o storage estabelecida antes que a deteção automática funcione.




== Como a identificação de aplicativos me ajuda a gerenciar meu storage array?

Ao identificar aplicações, o Gerenciador de sistemas do SANtricity recomenda automaticamente uma configuração de volume que otimiza o storage com base no tipo de aplicação.

Otimizar volumes por aplicação pode tornar as operações de storage de dados mais eficientes. Caraterísticas como tipo de e/S, tamanho do segmento, propriedade do controlador e cache de leitura e gravação estão incluídas na configuração do volume. Além disso, você pode visualizar os dados de performance por aplicação e workload para avaliar a latência, IOPS e MIB/s das aplicações e seus workloads associados.



== O que é uma carga de trabalho?

Para alguns aplicativos em sua rede, como SQL Server ou Exchange, você pode definir uma carga de trabalho que otimiza o armazenamento para esse aplicativo.

Um workload é um objeto de storage compatível com uma aplicação. Você pode definir uma ou mais cargas de trabalho ou instâncias por aplicação. Para alguns aplicativos, o sistema configura a carga de trabalho para conter volumes com caraterísticas de volume subjacentes semelhantes. Essas características de volume são otimizadas com base no tipo de aplicação compatível com o workload. Por exemplo, se você criar uma carga de trabalho que suporte um aplicativo Microsoft SQL Server e, posteriormente, criar volumes para essa carga de trabalho, as caraterísticas de volume subjacentes serão otimizadas para oferecer suporte ao Microsoft SQL Server.

Durante a criação de volume, o sistema solicita que você responda a perguntas sobre o uso de uma carga de trabalho. Por exemplo, se você estiver criando volumes para o Microsoft Exchange, será perguntado quantas caixas de correio você precisa, quais são seus requisitos médios de capacidade de caixa de correio e quantas cópias do banco de dados deseja. O sistema usa essas informações para criar uma configuração de volume ideal para você, que pode ser editada conforme necessário.



== Como faço para configurar o método de entrega para o AutoSupport?

Para acessar as tarefas de configuração para os métodos de entrega do AutoSupport, vá para o menu:suporte[Centro de suporte] e clique na guia *AutoSupport*.

São suportados os seguintes protocolos: HTTPS e SMTP.



== Como sei se devo aceitar a configuração recomendada do pool?

Se você aceitar a configuração de pool recomendada depende de alguns fatores.

Determine o tipo de armazenamento mais adequado aos seus requisitos respondendo às seguintes perguntas:

* Você prefere vários pools de capacidades menores, em vez dos maiores pools possíveis?
* Você prefere grupos de volume RAID em pools?
* Você prefere provisionar manualmente suas unidades, em vez de ter uma configuração recomendada para você?


Se você respondeu Sim a qualquer uma dessas perguntas, considere rejeitar a configuração recomendada do pool.



== O Gerenciador de sistema do SANtricity não detetou nenhum host. O que faço?

Se você não vir seus hosts conetados, a deteção automática falhou, os hosts estão conetados incorretamente ou nenhum host está conetado atualmente.

Você pode configurar os hosts mais tarde, uma vez que você terminar com a configuração. Você pode criar hosts manualmente da seguinte forma:

* Você pode criar manualmente hosts e associar os identificadores de porta de host apropriados acessando o menu:armazenamento[hosts]. Os hosts que foram criados manualmente também são exibidos no assistente *Initial Setup*.
* O destino e o host devem ser configurados para o tipo de porta do host (por exemplo, iSCSI ou NVMe sobre RoCE) e uma sessão para o storage estabelecida antes que a deteção automática funcione.

