---
permalink: sm-interface/overview-interface-sam.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: Você navega na interface principal para acessar recursos e tarefas do System Manager. 
---
= Saiba mais sobre a interface do SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SANtricity System Manager é uma interface baseada na Web que permite gerenciar um storage array em uma única visualização.



== Página inicial

A página inicial fornece uma visualização de painel para o gerenciamento diário de seu storage array. Ao iniciar sessão no System Manager, a página inicial é a primeira tela exibida.

A visualização do painel é composta por três áreas de resumo que contêm informações importantes sobre o estado e a integridade do seu array de storage. Você pode encontrar mais informações na área de resumo.

[cols="25h,~"]
|===
| Área | Descrição 


 a| 
Desempenho
 a| 
A área desempenho permite comparar e contrastar o uso de recursos ao longo do tempo. É possível visualizar as métricas de desempenho de um storage array para tempo de resposta (IOPS), taxas de transferência (MIB/s) e a quantidade de capacidade de processamento usada (CPU).



 a| 
Capacidade
 a| 
A área capacidade exibe uma visualização de gráfico da capacidade alocada, da capacidade de armazenamento livre e da capacidade de armazenamento não atribuída no storage.



 a| 
Hierarquia de armazenamento
 a| 
A área hierarquia de armazenamento fornece uma visualização organizada dos vários componentes de hardware e objetos de armazenamento gerenciados pelo seu storage array. Clique na seta suspensa para executar uma determinada ação nesse componente de hardware ou objeto de armazenamento.

|===


== Área de notificações

A área de Notificações pode ser acessada pelo ícone de sino no canto superior da janela. A área de Notificações exibe notificações de problemas que indicam o status do array de storage e seus componentes. Além disso, esta seção exibe alertas automatizados que podem ajudar você a solucionar problemas antes que eles afetem outras áreas do seu ambiente de storage.



== Definições de interface

Pode alterar as preferências de apresentação e outras definições a partir da interface principal.



== Logins de usuário e senhas

O usuário atualmente conectado ao sistema é exibido nas configurações de usuário.

Para obter mais informações sobre usuários e senhas, consulte:

* link:administrator-password-protection.html["Defina a proteção de senha de administrador"]
* link:../sm-settings/change-passwords.html["Alterar senhas"]

