---
permalink: sm-interface/what-is-a-workload.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, workload 
summary: Para alguns aplicativos em sua rede, como SQL Server ou Exchange, você pode definir uma carga de trabalho que otimiza o armazenamento para esse aplicativo. 
---
= O que é uma carga de trabalho?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para alguns aplicativos em sua rede, como SQL Server ou Exchange, você pode definir uma carga de trabalho que otimiza o armazenamento para esse aplicativo.

Um workload é um objeto de storage compatível com uma aplicação. Você pode definir uma ou mais cargas de trabalho ou instâncias por aplicação. Para alguns aplicativos, o sistema configura a carga de trabalho para conter volumes com caraterísticas de volume subjacentes semelhantes. Essas características de volume são otimizadas com base no tipo de aplicação compatível com o workload. Por exemplo, se você criar uma carga de trabalho que suporte um aplicativo Microsoft SQL Server e, posteriormente, criar volumes para essa carga de trabalho, as caraterísticas de volume subjacentes serão otimizadas para oferecer suporte ao Microsoft SQL Server.

Durante a criação de volume, o sistema solicita que você responda a perguntas sobre o uso de uma carga de trabalho. Por exemplo, se você estiver criando volumes para o Microsoft Exchange, será perguntado quantas caixas de correio você precisa, quais são seus requisitos médios de capacidade de caixa de correio e quantas cópias do banco de dados deseja. O sistema usa essas informações para criar uma configuração de volume ideal para você, que pode ser editada conforme necessário.
