---
permalink: sm-interface/what-are-the-keyboard-shortcuts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, keyboard shortcuts 
summary: Você pode navegar pelo System Manager usando apenas o teclado. 
---
= Quais são os atalhos de teclado?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode navegar pelo Gerenciador de sistema do SANtricity usando o teclado sozinho.



== Navegação geral

[cols="1a,1a"]
|===
| Ação | Atalho de teclado 


 a| 
Mover para o item seguinte.
 a| 
Separador



 a| 
Mover para o item anterior.
 a| 
Shift e Tab



 a| 
Selecione um item.
 a| 
Introduza



 a| 
Lista suspensa - mova para o item seguinte ou anterior.
 a| 
Seta para baixo ou seta para cima



 a| 
Caixa de seleção--Selecione um item.
 a| 
Barra de espaço



 a| 
Botões de rádio - alternar entre itens.
 a| 
Seta para baixo ou seta para cima



 a| 
Texto expansível--expandir ou contrato item.
 a| 
Introduza

|===


== Navegação da mesa

[cols="1a,1a"]
|===
| Ação | Atalho de teclado 


 a| 
Selecione uma linha.
 a| 
Para selecionar uma linha e, em seguida, prima Enter



 a| 
Role para cima ou para baixo.
 a| 
Seta para baixo/seta para cima ou Página para baixo/Página para cima



 a| 
Altere a ordem de classificação de uma coluna.
 a| 
Para selecionar um título de coluna e, em seguida, prima Enter

|===


== Navegação no calendário

[cols="1a,1a"]
|===
| Ação | Atalho de teclado 


 a| 
Passar para o mês anterior.
 a| 
Página para cima



 a| 
Passar para o próximo mês.
 a| 
Página para baixo



 a| 
Mudar para o ano anterior.
 a| 
Página para cima



 a| 
Mude para o próximo ano.
 a| 
Página para baixo



 a| 
Abra o seletor de data se estiver fechado.
 a| 
Controle e Home



 a| 
Mover para o mês atual.
 a| 
Controle / comando e Home



 a| 
Passar para o dia anterior.
 a| 
Controle / comando à esquerda



 a| 
Passar para o dia seguinte.
 a| 
Controle / comando à direita



 a| 
Passar para a semana anterior.
 a| 
Controle / comando para cima



 a| 
Passar para a próxima semana.
 a| 
Controle / comando para baixo



 a| 
Selecione a data focada.
 a| 
Introduza



 a| 
Feche o seletor de data e apague a data.
 a| 
Controle / comando e fim



 a| 
Feche o seletor de data sem seleção.
 a| 
Escape

|===