---
permalink: sm-hardware/configure-iser-over-infiniband-ports-hardware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iser, infiniband, ports, 
summary: Se o controlador incluir uma porta iSER over InfiniBand, você poderá configurar a conexão de rede ao host. 
---
= Configurar portas iSER sobre InfiniBand no SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se o controlador incluir uma porta iSER over InfiniBand, você poderá configurar a conexão de rede ao host.

.Antes de começar
* Sua controladora deve incluir uma porta iSER over InfiniBand; caso contrário, as configurações iSER over InfiniBand não estão disponíveis no System Manager.
* Você deve saber o endereço IP da conexão do host.


.Passos
. Selecione *hardware*.
. Se o gráfico mostrar as unidades, clique na guia *Controllers & Components* (Controladores e componentes).
+
O gráfico muda para mostrar os controladores em vez das unidades.

. Clique no controlador com a porta iSER over InfiniBand que você deseja configurar.
+
É apresentado o menu de contexto do controlador.

. Selecione *Configure iSER over InfiniBand Ports*.
+
A caixa de diálogo Configurar portas iSER em InfiniBand é aberta.

. Na lista suspensa, selecione a porta HIC que deseja configurar e insira o endereço IP do host.
. Clique em *Configurar*.
. Conclua a configuração e, em seguida, redefina a porta iSER em InfiniBand clicando em *Yes*.

