---
permalink: sm-hardware/configure-nvme-over-infiniband-ports-hardware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, infiniband, ports, nvme, 
summary: Se o controlador incluir uma conexão NVMe over InfiniBand, você poderá configurar as configurações da porta NVMe na página hardware. 
---
= Configurar portas NVMe em InfiniBand
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se o controlador incluir uma conexão NVMe over InfiniBand, você poderá configurar as configurações da porta NVMe na página hardware.

.Antes de começar
* Seu controlador deve incluir uma porta de host NVMe over InfiniBand. Caso contrário, as configurações de NVMe em InfiniBand não estão disponíveis no System Manager.
* Você deve saber o endereço IP da conexão do host.


[NOTE]
====
As configurações e funções do NVMe over InfiniBand aparecerão somente se a controladora do storage array incluir uma porta NVMe over InfiniBand.

====
.Passos
. Selecione *hardware*.
. Se o gráfico mostrar as unidades, clique na guia *Controllers & Components* (Controladores e componentes).
+
O gráfico muda para mostrar os controladores em vez das unidades.

. Clique no controlador com a porta NVMe over InfiniBand que você deseja configurar.
+
É apresentado o menu de contexto do controlador.

. Selecione *Configurar portas NVMe over InfiniBand*.
+
A caixa de diálogo Configurar portas NVMe over InfiniBand será exibida.

. Selecione a porta HIC que pretende configurar na lista pendente e, em seguida, introduza o endereço IP.
+
Se você estiver configurando um storage array EF600 com um HIC compatível com 200GB, essa caixa de diálogo exibirá dois campos de Endereço IP, um para uma porta física (externa) e outro para uma porta virtual (interna). Você deve atribuir um endereço IP exclusivo para ambas as portas. Essas configurações permitem que o host estabeleça um caminho entre cada porta e que o HIC alcance o máximo desempenho. Se você não atribuir um endereço IP à porta virtual, o HIC será executado a aproximadamente metade de sua velocidade capaz.

. Clique em *Configurar*.
. Conclua a configuração e, em seguida, redefina a porta NVMe over InfiniBand clicando em *Yes*.

