---
permalink: sm-hardware/faq-storage-shelf.html 
sidebar: sidebar 
keywords:  
summary: Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta. 
---
= Perguntas frequentes sobre prateleiras de armazenamento para o SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta.



== O que é proteção contra perda de prateleira e proteção contra perda de gaveta?

A proteção contra perda de gaveta e a proteção contra perda de gaveta são atributos de pools e grupos de volumes que permitem manter o acesso aos dados em caso de falha de gaveta ou gaveta única.



=== Proteção contra perda de prateleira

Um compartimento é o compartimento que contém as unidades ou as unidades e a controladora. A proteção contra perda de gaveta garante a acessibilidade aos dados nos volumes em um pool ou grupo de volumes se houver perda total de comunicação com um único compartimento de unidade. Um exemplo de perda total de comunicação pode ser perda de energia para o compartimento de unidades ou falha de ambos os módulos de e/S (IOMs).

[NOTE]
====
A proteção contra perda de gaveta não é garantida se uma unidade já tiver falhado no pool ou grupo de volumes. Nessa situação, a perda de acesso a um compartimento de unidades e, consequentemente, outra unidade no pool ou grupo de volumes causa a perda de dados.

====
Os critérios para a proteção contra perdas de prateleira dependem do método de proteção, conforme descrito na seguinte tabela:

[cols="1a,1a,1a"]
|===
| Nível | Critérios para proteção contra perdas de prateleira | Número mínimo de gavetas necessário 


 a| 
Piscina
 a| 
O pool deve incluir unidades de pelo menos cinco gavetas, e deve haver um número igual de unidades em cada gaveta. A proteção contra perda de prateleira não é aplicável às prateleiras de alta capacidade; se o sistema contiver prateleiras de alta capacidade, consulte proteção contra perda de gaveta.
 a| 
5



 a| 
RAID 6
 a| 
O grupo de volumes não contém mais do que duas unidades em uma única gaveta.
 a| 
3



 a| 
RAID 3 ou RAID 5
 a| 
Cada unidade no grupo de volume está localizada em uma gaveta separada.
 a| 
3



 a| 
RAID 1
 a| 
Cada unidade em um par RAID 1 deve estar localizada em uma gaveta separada.
 a| 
2



 a| 
RAID 0
 a| 
Não é possível obter proteção contra perdas de prateleira.
 a| 
Não aplicável

|===


=== Proteção contra perda de gaveta

Uma gaveta é um dos compartimentos de uma prateleira que você puxa para fora para acessar as unidades. Apenas as prateleiras de alta capacidade têm gavetas. A proteção contra perda de gaveta garante a acessibilidade aos dados nos volumes em um pool ou grupo de volumes se ocorrer uma perda total de comunicação com uma única gaveta. Um exemplo de perda total de comunicação pode ser perda de energia para a gaveta ou falha de um componente interno dentro da gaveta.

[NOTE]
====
A proteção contra perda de gaveta não é garantida se uma unidade já tiver falhado no pool ou grupo de volume. Nesta situação, perder o acesso a uma gaveta (e, consequentemente, outra unidade no pool ou grupo de volume) causa perda de dados.

====
Os critérios para a proteção contra perda de gaveta dependem do método de proteção, conforme descrito na seguinte tabela:

[cols="1a,1a,1a"]
|===
| Nível | Critérios para proteção contra perda de gaveta | Número mínimo de gavetas necessário 


 a| 
Piscina
 a| 
Os candidatos ao pool devem incluir unidades de todas as gavetas, e deve haver um número igual de unidades em cada gaveta.

O pool deve incluir unidades de pelo menos cinco gavetas e deve haver um número igual de unidades em cada gaveta.

Um compartimento de 60 unidades pode obter proteção contra perda de gaveta quando o pool contém 15, 20, 25, 30, 35, 40, 45, 50, 55 ou 60 unidades. Incrementos em múltiplos de 5 podem ser adicionados ao pool após a criação inicial.
 a| 
5



 a| 
RAID 6
 a| 
O grupo de volumes não contém mais do que duas unidades em uma única gaveta.
 a| 
3



 a| 
RAID 3 ou RAID 5
 a| 
Cada unidade do grupo de volume está localizada em uma gaveta separada.
 a| 
3



 a| 
RAID 1
 a| 
Cada unidade em um par espelhado deve estar localizada em uma gaveta separada.
 a| 
2



 a| 
RAID 0
 a| 
Não é possível obter proteção contra perda de gaveta.
 a| 
Não aplicável

|===


== O que são ciclos de aprendizagem da bateria?

Um ciclo de aprendizagem é um ciclo automático para calibrar o indicador inteligente da bateria.

Um ciclo de aprendizagem consiste nestas fases:

* Descarga controlada da bateria
* Período de repouso
* Carregar


As baterias são descarregadas até um limite predeterminado. Durante esta fase, o indicador da bateria é calibrado.

Um ciclo de aprendizagem requer estes parâmetros:

* Baterias totalmente carregadas
* Sem pilhas sobreaquecidas


Os ciclos de aprendizagem para sistemas de controlador duplex ocorrem simultaneamente. Para controladores com alimentação de backup de mais de uma bateria ou conjunto de células de bateria, os ciclos de aprendizagem ocorrem sequencialmente.

Os ciclos de aprendizagem são programados para iniciar automaticamente em intervalos regulares, ao mesmo tempo e no mesmo dia da semana. O intervalo entre os ciclos é descrito em semanas.

[NOTE]
====
Um ciclo de aprendizagem pode levar várias horas para ser concluído.

====