---
permalink: sm-hardware/hot-spare-drives.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hot, spare, drives, raid1, raid6, raid5 
summary: As peças sobressalentes ativas funcionam como unidades de reserva nos grupos de volume RAID 1, RAID 5 ou RAID 6 para o System Manager. 
---
= Saiba mais sobre unidades de reserva no SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As peças sobressalentes ativas funcionam como unidades de reserva nos grupos de volume RAID 1, RAID 5 ou RAID 6 para o Gerenciador de sistemas SANtricity.

São unidades totalmente funcionais que não contêm dados. Se uma unidade falhar no grupo de volumes, o controlador reconstrói automaticamente os dados da unidade com falha para uma unidade atribuída como hot spare.

As peças sobressalentes quentes não são dedicadas a grupos de volumes específicos. Eles podem ser usados para qualquer unidade com falha na matriz de armazenamento, desde que o hot spare e a unidade compartilhem esses atributos:

* Capacidade igual (ou maior capacidade para o hot spare)
* Mesmo tipo de material (por exemplo, HDD ou SSD)
* Mesmo tipo de interface (por exemplo, SAS)




== Como identificar peças sobressalentes quentes

Você pode atribuir hot spares através do Assistente de configuração inicial ou da página hardware. Para determinar se os hot spares são atribuídos, vá para a página hardware e procure os compartimentos de unidade mostrados em rosa.



== Como funciona a cobertura hot spare

A cobertura hot spare funciona da seguinte forma:

* Você reserva uma unidade não atribuída como hot spare para grupos de volume RAID 1, RAID 5 ou RAID 6.
+
[NOTE]
====
Os hot spares não podem ser usados para pools, que têm um método diferente de proteção de dados. Em vez de reservar uma unidade adicional, os pools reservam capacidade extra (chamada _capacidade de preservação_) dentro de cada unidade da piscina. Se uma unidade falhar em um pool, o controlador reconstruirá os dados nessa capacidade extra.

====
* Se uma unidade dentro de um grupo de volumes RAID 1, RAID 5 ou RAID 6 falhar, a controladora usará automaticamente dados de redundância para reconstruir os dados da unidade com falha. O hot spare é substituído automaticamente pela unidade com falha sem exigir uma troca física.
* Quando você substituiu fisicamente a unidade com falha, uma operação de cópia ocorre da unidade hot spare para a unidade substituída. Se você designou a unidade hot spare como um membro permanente de um grupo de volume, a operação copyback não é necessária.
* A disponibilidade de proteção contra perda de bandeja e proteção contra perda de gaveta para um grupo de volumes depende da localização das unidades que compõem o grupo de volumes. A proteção contra perda de bandeja e a proteção contra perda de gaveta podem ser perdidas devido a uma unidade com falha e à localização da unidade hot spare. Para garantir que a proteção contra perda de bandeja e a proteção contra perda de gaveta não sejam afetadas, você deve substituir uma unidade com falha para iniciar o processo de cópia de segurança.
* O volume do storage array permanece on-line e acessível enquanto você está substituindo a unidade com falha, porque a unidade hot spare é substituída automaticamente pela unidade com falha.




== Considerações sobre a capacidade da unidade hot spare

Selecione uma unidade com uma capacidade igual ou superior à capacidade total da unidade que pretende proteger. Por exemplo, se você tiver uma unidade de 18 GiB com capacidade configurada de 8 GiB, poderá usar uma unidade de 9 GiB ou maior como hot spare. Geralmente, não atribua uma unidade como hot spare a menos que sua capacidade seja igual ou maior que a capacidade da unidade maior no storage de armazenamento.

[NOTE]
====
Se as peças sobressalentes quentes não estiverem disponíveis que tenham a mesma capacidade física, uma unidade com menor capacidade pode ser usada como hot spare se a "capacidade usada" da unidade for a mesma ou menor que a capacidade da unidade hot spare.

====


== Considerações para tipos de Mídia e interface

A unidade usada como hot spare deve compartilhar o mesmo tipo de Mídia e tipo de interface que as unidades que protegerão. Por exemplo, uma unidade HDD não pode servir como hot spare para unidades SSD.



== Considerações para unidades com capacidade de segurança

Uma unidade com capacidade segura, como FDE ou FIPS, pode servir como um hot spare para unidades com ou sem recursos de segurança. No entanto, uma unidade que não seja segura não pode servir como hot spare para unidades com recursos de segurança.

Quando você seleciona uma unidade habilitada para segurança a ser usada para um hot spare, o System Manager solicita que você execute uma eliminação segura antes de prosseguir. A eliminação segura repõe os atributos de segurança da unidade para uma capacidade segura, mas não ativada para segurança.

[NOTE]
====
Quando você ativa o recurso Segurança da Unidade e cria um pool ou grupo de volumes a partir de unidades com capacidade segura, as unidades tornam-se _seguras-ativadas_. O acesso de leitura e gravação está disponível somente por meio de um controlador configurado com a chave de segurança correta. Essa segurança adicional impede o acesso não autorizado aos dados em uma unidade que é fisicamente removida do storage array.

====


== Número recomendado de unidades hot spare

Se você usou o assistente de configuração inicial para criar automaticamente hot spares, o System Manager cria um hot spare para cada 30 unidades de um tipo de Mídia e tipo de interface específicos. Caso contrário, você pode criar manualmente unidades hot spare entre os grupos de volume no storage de armazenamento.
