---
permalink: sm-hardware/what-are-icmp-ping-responses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, icmp, ping, responses, message, protocol, 
summary: 'O ICMP (Internet Control Message Protocol) é um dos protocolos do conjunto TCP/IP.' 
---
= O que são respostas ICMP PING?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ICMP (Internet Control Message Protocol) é um dos protocolos do conjunto TCP/IP.

As `ICMP echo request` mensagens e(`ICMP echo reply` são comumente conhecidas como `ping` mensagens. `Ping` é uma ferramenta de solução de problemas usada pelos administradores de sistema para testar manualmente a conetividade entre dispositivos de rede e também para testar o atraso da rede e a perda de pacotes. O `ping` comando envia um `ICMP echo request` para um dispositivo na rede e o dispositivo responde imediatamente com um(`ICMP echo reply`. às vezes, a diretiva de segurança de rede de uma empresa exige `ping` (`ICMP echo reply`que o ) seja desativado em todos os dispositivos para torná-los mais difíceis de serem descobertos por pessoas não autorizadas.
