---
permalink: sm-hardware/what-is-ipv6-stateless-address-auto-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ipv6, stateless, address, auto, configuration, 
summary: Com a configuração automática sem estado, os hosts não obtêm endereços e outras informações de configuração de um servidor. 
---
= O que é a auto-configuração de endereço sem estado IPv6?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Com a configuração automática sem estado, os hosts não obtêm endereços e outras informações de configuração de um servidor.

A configuração automática sem estado no IPv6 apresenta endereços locais de ligação, multicast e o protocolo Neighbor Discovery (ND). O IPv6 pode gerar o ID da interface de um endereço a partir do endereço da camada de enlace de dados subjacente.

A configuração automática sem estado e a configuração automática com estado complementam-se. Por exemplo, o host pode usar a configuração automática sem estado para configurar seus próprios endereços, mas usar a configuração automática com estado para obter outras informações. A configuração automática com estado permite que os hosts obtenham endereços e outras informações de configuração de um servidor. O Internet Protocol versão 6 (IPv6) também define um método pelo qual todos os endereços IP de uma rede podem ser renumerados de uma só vez. IPv6 define um método para que os dispositivos na rede configurem automaticamente seu endereço IP e outros parâmetros sem a necessidade de um servidor.

Os dispositivos executam estas etapas ao usar a configuração automática sem monitoração de estado:

. *Generate a link-local address* -- o dispositivo gera um endereço link-local, que tem 10 bits, seguido de 54 zeros, e seguido pelo ID de interface de 64 bits.
. *Teste a singularidade de um endereço local de link* -- o nó testa para se certificar de que o endereço local de link que ele gera ainda não está em uso na rede local. O nó envia uma mensagem de solicitação de vizinho usando o protocolo ND. Em resposta, a rede local escuta uma mensagem de anúncio vizinho, que indica que outro dispositivo já está usando o endereço local de link. Em caso afirmativo, um novo endereço local de link deve ser gerado ou falha de configuração automática, e outro método deve ser usado.
. * Atribuir um endereço local de link* -- se o dispositivo passar no teste de exclusividade, o dispositivo atribui o endereço local de link à sua interface IP. O endereço local do link pode ser usado para comunicação na rede local, mas não pela Internet.
. *Contate o roteador* -- o nó tenta entrar em Contato com um roteador local para obter mais informações sobre como continuar a configuração. Esse Contato é realizado ouvindo mensagens de anúncio do roteador enviadas periodicamente pelos roteadores ou enviando uma mensagem específica de solicitação do roteador para pedir informações a um roteador sobre o que fazer a seguir.
. *Forneça direção para o nó* -- o roteador fornece direção para o nó sobre como proceder com a configuração automática. Como alternativa, o roteador informa ao host como determinar o endereço global da Internet.
. *Configure o endereço global* -- o host se configura com seu endereço de Internet exclusivo globalmente. Esse endereço geralmente é formado a partir de um prefixo de rede fornecido ao host pelo roteador.

