---
permalink: um-manage/considerations-for-discovering-arrays.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, considerations, discovering, arrays 
summary: Antes que o Unified Manager possa exibir e gerenciar recursos de storage, ele deve descobrir os storages que você deseja gerenciar na rede da sua organização. Você pode descobrir vários arrays ou descobrir um único array. 
---
= Saiba mais sobre como descobrir matrizes de armazenamento no SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes que o SANtricity Unified Manager possa exibir e gerenciar recursos de storage, ele deve descobrir os storages que você deseja gerenciar na rede da organização. Você pode descobrir vários arrays ou descobrir um único array.



== Descobrindo vários storages de armazenamento

Se você optar por descobrir vários arrays, insira um intervalo de endereços IP de rede e, em seguida, o Unified Manager tentará conexões individuais para cada endereço IP nesse intervalo. Qualquer matriz de armazenamento alcançada com sucesso aparece na página descobrir e pode ser adicionada ao seu domínio de gerenciamento.



== Descobrindo um único storage array

Se você optar por descobrir um único array, insira o endereço IP único de um dos controladores no storage array e, em seguida, o storage array individual será adicionado.

[NOTE]
====
O Unified Manager deteta e exibe apenas o único endereço IP ou endereço IP dentro de um intervalo atribuído a um controlador. Se houver controladores alternativos ou endereços IP atribuídos a esses controladores que estejam fora desse único endereço IP ou intervalo de endereços IP, o Unified Manager não os detetará ou exibirá. No entanto, depois de adicionar a matriz de armazenamento, todos os endereços IP associados serão descobertos e exibidos na visualização Gerenciar.

====


== Credenciais do usuário

Como parte do processo de descoberta, você deve fornecer a senha de administrador para cada storage que deseja adicionar.



== Certificados de serviços da Web

Como parte do processo de descoberta, o Unified Manager verifica se os storage arrays descobertos estão usando certificados de uma fonte confiável. O Unified Manager usa dois tipos de autenticação baseada em certificado para todas as conexões que estabelece com o navegador:

* *Certificados confiáveis*
+
Para storages descobertos pelo Unified Manager, talvez seja necessário instalar certificados confiáveis adicionais fornecidos pela Autoridade de certificação.

+
Use o botão *Import* para importar esses certificados. Se você já tiver conetado a esse array antes, um ou ambos os certificados do controlador expiram, revogam ou faltam um certificado raiz ou um certificado intermediário em sua cadeia de certificados. Você deve substituir o certificado expirado ou revogado ou adicionar o certificado raiz ou o certificado intermediário em falta antes de gerenciar o storage array.

* *Certificados autoassinados*
+
Certificados autoassinados também podem ser usados. Se o administrador tentar descobrir matrizes sem importar certificados assinados, o Unified Manager exibirá uma caixa de diálogo de erro que permite que o administrador aceite o certificado autoassinado. O certificado autoassinado do storage array será marcado como confiável e o storage array será adicionado ao Unified Manager.

+
Se você não confiar nas conexões com o storage array, selecione *Cancelar* e valide a estratégia de certificado de segurança do storage antes de adicionar o storage array ao Unified Manager.


