---
permalink: um-manage/faq-storage-mirroring.html 
sidebar: sidebar 
keywords:  
summary: Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta. 
---
= Perguntas frequentes sobre espelhamento de armazenamento para o SANtricity Unified Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta.



== O que eu preciso saber antes de criar um grupo de consistência de espelho?

Siga estas diretrizes antes de criar um grupo de consistência espelhada.

Atender aos seguintes requisitos do Unified Manager:

* O serviço Web Services Proxy deve estar em execução.
* O Unified Manager deve estar em execução em seu host local por meio de uma conexão HTTPS.
* O Unified Manager deve mostrar certificados SSL válidos para a matriz de armazenamento. Você pode aceitar um certificado autoassinado ou instalar seu próprio certificado de segurança usando o Unified Manager e navegando para o menu:certificado[Gerenciamento de certificados].


Certifique-se também de atender aos seguintes requisitos para matrizes de armazenamento:

* Os dois storage arrays devem ser descobertos no Unified Manager.
* Cada storage array deve ter duas controladoras.
* Cada controlador no array primário e no array secundário deve ter uma porta de gerenciamento Ethernet configurada e estar conetado à rede.
* As matrizes de armazenamento têm uma versão mínima de firmware de 7,84. (Cada um deles pode executar diferentes versões do sistema operacional.)
* Você deve saber a senha para os storages de armazenamento local e remoto.
* Seus storage arrays locais e remotos são conectados por meio de uma malha Fibre Channel ou de uma interface iSCSI.


[NOTE]
====
O espelhamento síncrono não está disponível no sistema de storage EF600/EF600C ou EF300/EF300C.

====


== O que eu preciso saber antes de criar um par espelhado?

Antes de criar um par espelhado, siga estas diretrizes.

* Você precisa ter dois storage arrays.
* Cada storage array deve ter duas controladoras.
* Os dois storage arrays devem ser descobertos no Unified Manager.
* Cada controlador no array primário e no array secundário deve ter uma porta de gerenciamento Ethernet configurada e estar conetado à rede.
* As matrizes de armazenamento têm uma versão mínima de firmware de 7,84. (Cada um deles pode executar diferentes versões do sistema operacional.)
* Você deve saber a senha para os storages de armazenamento local e remoto.
* Você precisa ter capacidade livre suficiente no storage array remoto para criar um volume secundário igual ou maior que o volume principal que deseja espelhar.
* O espelhamento assíncrono é compatível com controladoras com portas de host Fibre Channel (FC) ou iSCSI, enquanto o espelhamento síncrono é compatível somente com controladoras com portas de host FC.


[NOTE]
====
O espelhamento síncrono não está disponível no sistema de storage EF600/EF600C ou EF300/EF300C.

====


== Por que eu alteraria essa porcentagem?

A capacidade reservada costuma ser de 20% do volume base para operações de espelhamento assíncrono. Normalmente, essa capacidade é suficiente.

A capacidade necessária varia, dependendo da frequência e tamanho das gravações de e/S no volume base e quanto tempo você pretende usar a operação de serviço de cópia do objeto de armazenamento. Em geral, escolha uma porcentagem maior para a capacidade reservada se uma ou ambas as condições existirem:

* Se a vida útil de uma operação de serviço de cópia de um objeto de armazenamento específico será muito longa.
* Se uma grande porcentagem de blocos de dados mudar no volume base devido à intensa atividade de e/S. Use dados históricos de desempenho ou outros utilitários do sistema operacional para ajudá-lo a determinar a atividade típica de e/S para o volume base.




== Por que vejo mais de um candidato à capacidade reservada?

Se houver mais de um volume em um pool ou grupo de volumes que atenda ao valor percentual de capacidade selecionado para o objeto de armazenamento, você verá vários candidatos.

Você pode atualizar a lista de candidatos recomendados alterando a porcentagem de espaço físico da unidade que deseja reservar no volume base para operações de serviço de cópia. Os melhores candidatos são exibidos com base na sua seleção.



== Por que não vejo todos os meus volumes?

Ao selecionar um volume primário para um par espelhado, uma lista mostra todos os volumes elegíveis.

Quaisquer volumes que não sejam elegíveis para serem usados não são exibidos nessa lista. Os volumes podem não ser elegíveis por qualquer um dos seguintes motivos:

* O volume não é ideal.
* O volume já está participando de uma relação de espelhamento.
* Para o espelhamento síncrono, os volumes primário e secundário em um par espelhado devem ser volumes padrão. Não podem ser volumes finos ou volumes instantâneos.
* Para o espelhamento assíncrono, os thin volumes devem ter a expansão automática ativada.



NOTE: Para controladores EF600 e EF300, os volumes primário e secundário de um par espelhado assíncrono devem corresponder ao mesmo protocolo, nível da bandeja, tamanho do segmento, tipo de segurança e nível RAID. Pares espelhados assíncronos não elegíveis não aparecerão na lista de volumes disponíveis.



== Por que não vejo todos os volumes no conjunto de armazenamento remoto?

Quando você está selecionando um volume secundário no storage array remoto, uma lista mostra todos os volumes elegíveis para esse par espelhado.

Quaisquer volumes que não sejam elegíveis para serem usados, não serão exibidos nessa lista. Os volumes não podem ser elegíveis por qualquer um dos seguintes motivos:

* O volume é um volume não padrão, como um volume instantâneo.
* O volume não é ideal.
* O volume já está participando de uma relação de espelhamento.
* Para espelhamento assíncrono, os atributos de volume fino entre o volume primário e o volume secundário não correspondem.
* Se estiver a utilizar o Data Assurance (DA), o volume primário e o volume secundário têm de ter as mesmas definições DE DA.
+
** Se o volume primário for DA ativado, o volume secundário tem de ser DA ativado.
** Se o volume primário não estiver ativado DA, o volume secundário não deve ser ativado DA.


* Para o espelhamento assíncrono, o volume primário e o volume secundário devem ter os mesmos recursos de Segurança da Unidade.
+
** Se o volume primário for compatível com FIPS, o volume secundário deve ser capaz de FIPS.
** Se o volume principal for compatível com FDE, o volume secundário tem de ser capaz de FDE.
** Se o volume principal não estiver usando o Drive Security, o volume secundário não deve estar usando o Drive Security.






== Qual o impactos que a prioridade de sincronização tem nas taxas de sincronização?

A prioridade de sincronização define quanto tempo de processamento é alocado para atividades de sincronização em relação ao desempenho do sistema.

O proprietário do controlador do volume primário executa esta operação em segundo plano. Ao mesmo tempo, o proprietário do controlador processa gravações de e/S locais no volume principal e gravações remotas associadas no volume secundário. Como a ressincronização desvia os recursos de processamento do controlador da atividade de e/S, a ressincronização pode ter um impacto no desempenho do aplicativo host.

Mantenha essas diretrizes em mente para ajudá-lo a determinar quanto tempo uma prioridade de sincronização pode levar e como as prioridades de sincronização podem afetar o desempenho do sistema.

Estas tarifas prioritárias estão disponíveis:

* Mais baixo
* Baixo
* Média
* Alta
* Mais alto


A taxa de prioridade mais baixa suporta o desempenho do sistema, mas a ressincronização leva mais tempo. A taxa de prioridade mais alta é compatível com a ressincronização, mas o desempenho do sistema pode estar comprometido.

Estas orientações aproximam aproximadamente as diferenças entre as prioridades.

[cols="45h,~"]
|===
| Taxa de prioridade para sincronização completa | Tempo decorrido em comparação com a taxa de sincronização mais elevada 


 a| 
Mais baixo
 a| 
Aproximadamente oito vezes, desde que na taxa de prioridade mais alta.



 a| 
Baixo
 a| 
Aproximadamente seis vezes, desde que na taxa de prioridade mais alta.



 a| 
Média
 a| 
Aproximadamente três vezes e meia, desde que com a taxa de prioridade mais alta.



 a| 
Alta
 a| 
Aproximadamente o dobro do tempo na taxa de prioridade mais alta.

|===
As cargas de tamanho de volume e taxa de e/S do host afetam as comparações de tempo de sincronização.



== Por que é recomendável usar uma política de sincronização manual?

A ressincronização manual é recomendada porque permite gerenciar o processo de ressincronização de uma forma que forneça a melhor oportunidade para recuperar dados.

Se você usar uma política de ressincronização automática e ocorrerem problemas de comunicação intermitente durante a ressincronização, os dados no volume secundário poderão ser corrompidos temporariamente. Quando a ressincronização é concluída, os dados são corrigidos.
