---
permalink: um-manage/import-alert-settings.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, import, alert, settings 
summary: Você pode importar configurações de alerta de um storage array para outros storage arrays. Esta operação em lote economiza tempo quando você precisa configurar vários arrays na rede. 
---
= Importar definições de alerta
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode importar configurações de alerta de um storage array para outros storage arrays. Esta operação em lote economiza tempo quando você precisa configurar vários arrays na rede.

.Antes de começar
* Os alertas são configurados no System Manager para a matriz de armazenamento que você deseja usar como fonte (menu:Configurações[Alertas]).
* A configuração existente para os storages de armazenamento de destino é feita com backup no System Manager (menu:Configurações[sistema > Salvar configuração da matriz de armazenamento]).


.Sobre esta tarefa
Você pode selecionar alertas de e-mail, SNMP ou syslog para a operação de importação. As definições importadas incluem:

* *Alertas por e-mail* -- Um endereço de servidor de e-mail e os endereços de e-mail dos destinatários do alerta.
* *Alertas Syslog* -- Um endereço de servidor syslog e uma porta UDP.
* *Alertas SNMP* -- Um nome de comunidade e endereço IP para o servidor SNMP.


.Passos
. Na página Gerenciar, clique em *Importar configurações*.
+
O assistente Importar configurações é aberto.

. Na caixa de diálogo Selecionar configurações, selecione *Email alerts*, *SNMP alerts* ou *Syslog alerts* e, em seguida, clique em *Next*.
+
Abre-se uma caixa de diálogo para selecionar a matriz de origem.

. Na caixa de diálogo Selecionar fonte, selecione a matriz com as configurações que deseja importar e clique em *Avançar*.
. Na caixa de diálogo Selecionar destinos, selecione um ou mais arrays para receber as novas configurações.
+
[NOTE]
====
Matrizes de armazenamento com firmware abaixo de 8,50 não estão disponíveis para seleção. Além disso, uma matriz não aparece nesta caixa de diálogo se o Unified Manager não puder se comunicar com essa matriz (por exemplo, se estiver offline ou se tiver problemas de certificado, senha ou rede).

====
. Clique em *Finish*.
+
A página operações exibe os resultados da operação de importação. Se a operação falhar, você pode clicar em sua linha para ver mais informações.



.Resultados
Os storages de armazenamento de destino agora estão configurados para enviar alertas aos administradores por e-mail, SNMP ou syslog.
