---
permalink: um-manage/requirements-for-replicating-storage-configurations.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, requirements, replicating, storage, configurations 
summary: Antes de importar uma configuração de armazenamento de um storage array para outro, revise os requisitos e as diretrizes. 
---
= Requisitos para replicar configurações de matriz de armazenamento no SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de importar uma configuração de armazenamento de um storage array para outro, revise os requisitos e as diretrizes.



== Compartimentos

* Os compartimentos em que os controladores residem devem ser idênticos nos arrays de origem e destino.
* As IDs de gaveta devem ser idênticas nos arrays de origem e destino.
* Os compartimentos de expansão devem ser preenchidos nos mesmos slots com os mesmos tipos de unidade (se a unidade for usada na configuração, o local das unidades não utilizadas não importa).




== Controladores

* O tipo de controlador pode ser diferente entre os arrays de origem e destino (por exemplo, importando de um E2800 para um E5700), mas o tipo de gabinete RBOD deve ser idêntico.
* As HICs, incluindo os recursos DA DO host, devem ser idênticas entre os arrays de origem e destino.
* A importação de uma configuração duplex para simplex não é suportada; no entanto, a importação de simplex para duplex é permitida.
* As definições FDE não estão incluídas no processo de importação.




== Estado

* Os arrays de destino devem estar no status ideal.
* O array de origem não precisa estar no status ideal.




== Armazenamento

* A capacidade da unidade pode variar entre os arrays de origem e destino, desde que a capacidade de volume no destino seja maior do que a origem. (Um array de destino pode ter unidades de capacidade mais novas e maiores que não seriam totalmente configuradas em volumes pela operação de replicação.)
* Volumes de pool de discos de 64 TB ou maiores no array de origem impedirão o processo de importação nos destinos.
* Os volumes finos não estão incluídos no processo de importação.

