---
permalink: um-manage/storage-array-groups.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, storage, array, groups 
summary: Você pode gerenciar sua infraestrutura física e virtualizada agrupando um conjunto de storage arrays. Você pode querer agrupar storages para facilitar a execução de tarefas de monitoramento ou geração de relatórios. 
---
= Saiba mais sobre grupos de matrizes de armazenamento no SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerenciar sua infraestrutura física e virtualizada agrupando um conjunto de storage arrays. Você pode querer agrupar storages para facilitar a execução de tarefas de monitoramento ou geração de relatórios.



== Tipos de grupos de storage array

* *Todos os grupos*
+
O grupo todos é o grupo padrão e inclui todos os storage arrays descobertos em sua organização. O grupo todos pode ser acessado a partir da vista principal.

* *Grupo criado pelo usuário*
+
Um grupo criado pelo usuário inclui os storage arrays que você seleciona manualmente para adicionar a esse grupo. Os grupos criados pelo utilizador podem ser acedidos a partir da vista principal.


