---
permalink: um-manage/what-do-i-need-to-know-before-creating-a-mirrored-pair-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, creating, mirrored, pair 
summary: Antes de criar um par espelhado, siga estas diretrizes. 
---
= O que eu preciso saber antes de criar um par espelhado?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de criar um par espelhado, siga estas diretrizes.

* Você precisa ter dois storage arrays.
* Cada storage array deve ter duas controladoras.
* Os dois storage arrays devem ser descobertos no Unified Manager.
* Cada controlador no array primário e no array secundário deve ter uma porta de gerenciamento Ethernet configurada e estar conetado à rede.
* As matrizes de armazenamento têm uma versão mínima de firmware de 7,84. (Cada um deles pode executar diferentes versões do sistema operacional.)
* Você deve saber a senha para os storages de armazenamento local e remoto.
* Você precisa ter capacidade livre suficiente no storage array remoto para criar um volume secundário igual ou maior que o volume principal que deseja espelhar.
* O espelhamento assíncrono é compatível com controladoras com portas de host Fibre Channel (FC) ou iSCSI, enquanto o espelhamento síncrono é compatível somente com controladoras com portas de host FC.


[NOTE]
====
O espelhamento síncrono não está disponível no sistema de storage EF600/EF600C ou EF300/EF300C.

====