---
permalink: um-manage/why-dont-i-see-all-my-volumes-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, volumes missing 
summary: Ao selecionar um volume primário para um par espelhado, uma lista mostra todos os volumes elegíveis. 
---
= Por que não vejo todos os meus volumes?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao selecionar um volume primário para um par espelhado, uma lista mostra todos os volumes elegíveis.

Quaisquer volumes que não sejam elegíveis para serem usados não são exibidos nessa lista. Os volumes podem não ser elegíveis por qualquer um dos seguintes motivos:

* O volume não é ideal.
* O volume já está participando de uma relação de espelhamento.
* Para o espelhamento síncrono, os volumes primário e secundário em um par espelhado devem ser volumes padrão. Não podem ser volumes finos ou volumes instantâneos.
* Para o espelhamento assíncrono, os thin volumes devem ter a expansão automática ativada.



NOTE: Para controladores EF600 e EF300, os volumes primário e secundário de um par espelhado assíncrono devem corresponder ao mesmo protocolo, nível da bandeja, tamanho do segmento, tipo de segurança e nível RAID. Pares espelhados assíncronos não elegíveis não aparecerão na lista de volumes disponíveis.
