---
permalink: sm-settings/change-passwords.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, passwords, user, passwords, 
summary: Você pode alterar as senhas de usuário para cada perfil de usuário no Gerenciamento de acesso. 
---
= Alterar senhas no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar as senhas de usuário para cada perfil de usuário no Gerenciamento de acesso.

.Antes de começar
* Você deve estar logado como administrador local, o que inclui permissões de administrador raiz.
* Você deve saber a senha do administrador local.


.Sobre esta tarefa
Tenha em mente estas diretrizes ao escolher uma senha:

* Quaisquer novas senhas de usuário local devem atender ou exceder a configuração atual para uma senha mínima (em Configurações de visualização/edição).
* As senhas diferenciam maiúsculas de minúsculas.
* Os espaços de saída não são removidos das senhas quando são definidos. Tenha cuidado para incluir espaços se eles foram incluídos na senha.
* Para maior segurança, use pelo menos 15 carateres alfanuméricos e altere a senha com frequência.


[NOTE]
====
Alterar a senha no System Manager também a altera na interface de linha de comando (CLI). Além disso, as alterações de senha fazem com que a sessão ativa do usuário seja encerrada.

====
.Passos
. Selecione menu:Definições[Gestão de Acesso].
. Selecione a guia *funções de usuário local*.
. Selecione um usuário na tabela.
+
O botão alterar senha fica disponível.

. Selecione *alterar palavra-passe*.
+
A caixa de diálogo alterar senha será exibida.

. Se não estiver definido um comprimento mínimo de palavra-passe para palavras-passe de utilizador local, pode marcar a caixa para exigir que o utilizador selecionado introduza uma palavra-passe para aceder à matriz de armazenamento e, em seguida, pode introduzir a nova palavra-passe para o utilizador selecionado.
. Introduza a palavra-passe do administrador local e, em seguida, clique em *alterar*.


.Resultados
Se o usuário estiver conetado no momento, a alteração da senha fará com que a sessão ativa do usuário seja encerrada.
