---
permalink: sm-settings/change-local-user-passwords-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, local, user, password, settings, 
summary: Você pode definir o comprimento mínimo necessário para todas as senhas de usuário locais novas ou atualizadas na matriz de armazenamento. Você também pode permitir que os usuários locais acessem o storage array sem inserir uma senha. 
---
= Alterar as configurações de senha do usuário local no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode definir o comprimento mínimo necessário para todas as senhas de usuário locais novas ou atualizadas na matriz de armazenamento. Você também pode permitir que os usuários locais acessem o storage array sem inserir uma senha.

.Antes de começar
Você deve estar logado como administrador local, o que inclui permissões de administrador raiz.

.Sobre esta tarefa
Tenha estas diretrizes em mente ao definir o comprimento mínimo para senhas de usuário local:

* A definição de alterações não afetará as palavras-passe de utilizador locais existentes.
* A definição de comprimento mínimo necessário para palavras-passe de utilizador local tem de ter entre 0 e 30 carateres.
* Quaisquer novas senhas de usuário local devem atender ou exceder a configuração de comprimento mínimo atual.
* Não defina um tamanho mínimo para a senha se você quiser que os usuários locais acessem o storage array sem digitar uma senha.


.Passos
. Selecione menu:Definições[Gestão de Acesso].
. Selecione a guia *funções de usuário local*.
. Selecione o botão *View/Edit Settings* (Ver/Editar definições).
+
A caixa de diálogo Configurações de senha do usuário local é aberta.

. Execute um dos seguintes procedimentos:
+
** Para permitir que os usuários locais acessem o storage array _sem_ inserir uma senha, desmarque a caixa de seleção "exigir que todas as senhas de usuário local sejam pelo menos".
** Para definir um comprimento mínimo de palavra-passe para todas as palavras-passe de utilizador local, marque a caixa de verificação "exigir que todas as palavras-passe de utilizador local sejam pelo menos" e, em seguida, utilize a caixa de seleção para definir o comprimento mínimo necessário para todas as palavras-passe de utilizador local.
+
Todas as novas senhas de usuário local devem atender ou exceder a configuração atual.



. Clique em *Salvar*.

