---
permalink: sm-settings/configure-nvme-over-roce-ports-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, nvme, roce, ports, 
summary: 'Se o controlador incluir uma conexão para NVMe em RoCE (RDMA em Converged Ethernet), você poderá configurar as configurações da porta NVMe na página sistema.' 
---
= Configurar o NVMe em portas RoCE
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se o controlador incluir uma conexão para NVMe em RoCE (RDMA em Converged Ethernet), você poderá configurar as configurações da porta NVMe na página sistema.

.Antes de começar
* Sua controladora deve incluir uma porta de host NVMe em RoCE; caso contrário, as configurações NVMe em RoCE não estarão disponíveis no System Manager.
* Você deve saber o endereço IP da conexão do host.


.Passos
. Selecione menu:Definições[sistema].
. Em *NVMe over ROCE settings*, selecione *Configure NVMe over ROCE ports*.
. Selecione o controlador com a porta NVMe sobre RoCE que deseja configurar. Clique em *seguinte*.
. Selecione a porta HIC que deseja configurar na lista suspensa. Clique em *seguinte*.
. Configure as definições da porta.
+
Para ver todas as configurações de porta, clique no link *Mostrar mais configurações de porta* à direita da caixa de diálogo.

+
.Detalhes do campo
[%collapsible]
====
[cols="1a,1a"]
|===
| Definição da porta | Descrição 


 a| 
Velocidade da porta ethernet configurada
 a| 
Selecione a velocidade que corresponde à capacidade de velocidade do SFP na porta.



 a| 
Ativar IPv4 / ativar IPv6
 a| 
Selecione uma ou ambas as opções para ativar o suporte para redes IPv4G e IPv6G.


NOTE: Se pretender desativar o acesso à porta, desmarque ambas as caixas de verificação.



 a| 
Tamanho MTU (disponível clicando em *Mostrar mais configurações de porta*.)
 a| 
Se necessário, introduza um novo tamanho em bytes para a unidade máxima de transmissão (MTU).

O tamanho padrão da unidade máxima de transmissão (MTU) é de 1500 bytes por quadro. Tem de introduzir um valor entre 1500 e 9000.

|===
====
+
Se você selecionou *Ativar IPv4*, uma caixa de diálogo será aberta para selecionar IPv4 configurações depois de clicar em *Avançar*. Se você selecionou *Ativar IPv6*, uma caixa de diálogo será aberta para selecionar IPv6 configurações depois de clicar em *Avançar*. Se você selecionou ambas as opções, a caixa de diálogo para configurações IPv4 será aberta primeiro e, depois de clicar em *Avançar*, a caixa de diálogo para configurações IPv6 será aberta.

. Configure as definições IPv4 e/ou IPv6, automática ou manualmente.
+
.Detalhes do campo
[%collapsible]
====
[cols="1a,1a"]
|===
| Definição da porta | Descrição 


 a| 
Obter automaticamente a configuração
 a| 
Selecione esta opção para obter a configuração automaticamente.



 a| 
Especifique manualmente a configuração estática
 a| 
Selecione esta opção e, em seguida, introduza um endereço estático nos campos. (Se desejado, você pode cortar e colar endereços nos campos.) Para IPv4, inclua a máscara de sub-rede e o gateway. Para IPv6, inclua o endereço IP roteável e o endereço IP do roteador. Se você estiver configurando um storage array EF600 com um HIC compatível com 200GB, essa caixa de diálogo exibirá dois conjuntos de campos para parâmetros de rede, um para uma porta física (externa) e outro para uma porta virtual (interna). Você deve atribuir parâmetros exclusivos para ambas as portas. Essas configurações permitem que o host estabeleça um caminho entre cada porta e que o HIC alcance o máximo desempenho. Se você não atribuir um endereço IP à porta virtual, o HIC será executado a aproximadamente metade de sua velocidade capaz.

|===
====
. Clique em *Finish*.

