---
permalink: sm-settings/edit-key-management-server-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, edit, key, management, server, settings, 
summary: Se você tiver configurado o gerenciamento de chaves externas, poderá exibir e editar as configurações do servidor de gerenciamento de chaves a qualquer momento. 
---
= Editar as configurações do servidor de gerenciamento de chaves no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você tiver configurado o gerenciamento de chaves externas, poderá exibir e editar as configurações do servidor de gerenciamento de chaves a qualquer momento.

.Passos
. Selecione menu:Definições[sistema].
. Em *Gerenciamento de chaves de segurança*, selecione *Exibir/Editar Configurações do servidor de gerenciamento de chaves*.
. Edite informações nos seguintes campos:
+
** *Endereço do servidor de gerenciamento de chaves* -- Digite o nome de domínio totalmente qualificado ou o endereço IP (IPv4 ou IPv6) do servidor usado para o gerenciamento de chaves.
** *Número da porta de gerenciamento de chaves* -- Digite o número da porta usada para as comunicações KMIP (Key Management Interoperability Protocol).
+
*Opcional:* você pode incluir outro servidor de chaves clicando em *Add Key Server*.



. Clique em *Salvar*.

