---
permalink: sm-settings/how-do-i-interpret-iser-over-infiniband-statistics.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, interpret, iser, over, infiniband, statistics, 
summary: 'A caixa de diálogo View iSER over InfiniBand Statistics exibe estatísticas de destino local (protocolo) e estatísticas de interface iSER over InfiniBand (IB). Todas as estatísticas são apenas de leitura e não podem ser definidas.' 
---
= Como faço para interpretar estatísticas iSER over InfiniBand?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A caixa de diálogo View iSER over InfiniBand Statistics exibe estatísticas de destino local (protocolo) e estatísticas de interface iSER over InfiniBand (IB). Todas as estatísticas são apenas de leitura e não podem ser definidas.

* *Estatísticas locais de destino (protocolo)* -- fornece estatísticas para o destino iSER over InfiniBand, que mostra acesso em nível de bloco a sua Mídia de storage.
* *ISER over InfiniBand Interface statistics* -- fornece estatísticas para todas as portas iSER over InfiniBand na interface InfiniBand, que inclui estatísticas de desempenho e informações de erro de link associadas a cada porta do switch.


Você pode visualizar cada uma dessas estatísticas como estatísticas em bruto ou como estatísticas de linha de base. As estatísticas em bruto são todas as estatísticas que foram coletadas desde que os controladores foram iniciados. As estatísticas da linha de base são estatísticas pontuais que foram reunidas desde que você definiu o tempo da linha de base.
