---
permalink: sm-settings/how-do-i-interpret-nvme-over-fabrics-statistics.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, interpret, nvme, over, Fabrics, statistics, 
summary: A caixa de diálogo View NVMe over Fabrics Statistics exibe estatísticas do subsistema NVMe e da interface RDMA. Todas as estatísticas são apenas de leitura e não podem ser definidas. 
---
= Como interpretar as estatísticas do NVMe sobre Fabrics?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A caixa de diálogo View NVMe over Fabrics Statistics exibe estatísticas do subsistema NVMe e da interface RDMA. Todas as estatísticas são apenas de leitura e não podem ser definidas.

* *Estatísticas do subsistema NVMe* -- mostra estatísticas para o controlador NVMe e sua fila. O controlador NVMe fornece um caminho de acesso entre um host e os namespaces no storage array. Você pode revisar as estatísticas do subsistema NVMe para itens como falhas de conexão, reconfigurações e paradas. Para obter mais informações sobre essas estatísticas, clique em *Exibir legenda para títulos de tabela*.
* *Estatísticas da interface RDMA* -- fornece estatísticas para todas as portas NVMe sobre Fabrics na interface RDMA, que inclui estatísticas de desempenho e informações de erro de link associadas a cada porta do switch. Essa guia só aparece quando as portas NVMe sobre Fabrics estiverem disponíveis. Para obter mais informações sobre as estatísticas, clique em *Exibir legenda para títulos de tabela*.


Você pode visualizar cada uma dessas estatísticas como estatísticas em bruto ou como estatísticas de linha de base. As estatísticas em bruto são todas as estatísticas que foram coletadas desde que os controladores foram iniciados. As estatísticas da linha de base são estatísticas pontuais que foram reunidas desde que você definiu o tempo da linha de base.
