---
permalink: sm-settings/remove-directory-server.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, directory, server, 
summary: Para interromper a conexão entre um servidor de diretório e o storage array, você pode remover as informações do servidor da página Gerenciamento de acesso. Talvez você queira executar essa tarefa se tiver configurado um novo servidor e, em seguida, desejar remover o antigo. 
---
= Remover servidor de diretório no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para interromper a conexão entre um servidor de diretório e o storage array, você pode remover as informações do servidor da página Gerenciamento de acesso. Talvez você queira executar essa tarefa se tiver configurado um novo servidor e, em seguida, desejar remover o antigo.

.Antes de começar
Você deve estar conetado com um perfil de usuário que inclua permissões de administrador de segurança. Caso contrário, as funções de Gerenciamento de Acesso não aparecem.

.Sobre esta tarefa
Depois de concluir esta tarefa, todas as sessões ativas do utilizador são encerradas. Apenas a sessão de utilizador atual é mantida.

.Passos
. Selecione menu:Definições[Gestão de Acesso].
. Selecione a guia *Serviços de diretório*.
. Na lista, selecione o servidor de diretório que deseja excluir.
. Clique em *Remover*.
+
A caixa de diálogo Remover servidor de diretório é aberta.

. Digite `remove` o campo e clique em *Remover*.
+
As configurações do servidor de diretório, as configurações de privilégio e os mapeamentos de função são removidos. Os usuários não podem mais fazer login com credenciais deste servidor.


