---
permalink: sm-settings/view-imported-certificates.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, imported, certificate, information, 
summary: Na página certificados, você pode exibir o tipo de certificado, a autoridade emissora e o intervalo de datas válido de certificados para o storage array. 
---
= Exibir informações de certificado importadas
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Na página certificados, você pode exibir o tipo de certificado, a autoridade emissora e o intervalo de datas válido de certificados para o storage array.

.Antes de começar
Você deve estar conetado com um perfil de usuário que inclua permissões de administrador de segurança. Caso contrário, as funções do certificado não aparecem.

.Passos
. Selecione menu:Definições[certificados].
. Selecione uma das guias para exibir informações sobre os certificados.
+
[cols="25h,~"]
|===
| Separador | Descrição 


 a| 
Gerenciamento de array
 a| 
Exibir informações sobre os certificados assinados pela CA importados para cada controlador, incluindo o arquivo raiz, o(s) arquivo(s) intermediário(s) e o(s) arquivo(s) do servidor.



 a| 
Confiável
 a| 
Exibir informações sobre todos os outros tipos de certificados importados para os controladores. Use o campo de filtro em *Mostrar certificados que são...* para exibir certificados instalados pelo usuário ou pré-instalados.

** *User-Installed* -- certificados que um usuário carregou no storage array, que podem incluir certificados confiáveis quando o controlador atua como cliente (em vez de um servidor), certificados LDAPS e certificados de Federação de identidade.
** *Pré-instalado* -- certificados autoassinados incluídos com a matriz de armazenamento.




 a| 
Gerenciamento de chaves
 a| 
Exibir informações sobre os certificados assinados pela CA importados para um servidor de gerenciamento de chaves externo.

|===

