---
permalink: sm-settings/what-else-do-i-need-to-do-to-configure-or-diagnose-iser-over-infiniband.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, diagnose, iser, infiniBand, 
summary: A tabela a seguir lista as funções do System Manager que podem ser usadas para configurar e gerenciar sessões iSER over InfiniBand. 
---
= O que mais preciso fazer para configurar ou diagnosticar iSER em InfiniBand?
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A tabela a seguir lista as funções do System Manager que podem ser usadas para configurar e gerenciar sessões iSER over InfiniBand.

[NOTE]
====
As configurações iSER over InfiniBand estarão disponíveis somente se a controladora do storage array incluir uma porta de gerenciamento de host iSER over InfiniBand.

====
[cols="35h,~"]
|===
| Ação | Localização 


 a| 
Configurar o iSER em portas InfiniBand
 a| 
. Selecione *hardware*.
. Selecione a guia *Controllers & Components* (Controladores e componentes).
. Selecione um controlador.
. Selecione *Configure iSER over InfiniBand Ports*.


ou

. Selecione menu:Definições[sistema].
. Role para baixo até *iSER over InfiniBand settings* e selecione *Configure iSER over InfiniBand ports*.




 a| 
Visualizar estatísticas do iSER em InfiniBand
 a| 
. Selecione menu:Definições[sistema].
. Role para baixo até *iSER over InfiniBand settings* e selecione *View iSER over InfiniBand Statistics*.


|===