---
permalink: sm-settings/what-is-cache-block-size.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cache, block, size, 
summary: O controlador da matriz de armazenamento organiza o cache em blocos, que são blocos de memória que podem ter 8, 16, 32 KiB de tamanho. Todos os volumes no sistema de armazenamento compartilham o mesmo espaço de cache; portanto, os volumes podem ter apenas um tamanho de bloco de cache. 
---
= O que é o tamanho do bloco de cache?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O controlador do storage organiza seu cache em "blocos", que são pedaços de memória que podem ser 8, 16, 32 KiB de tamanho. Todos os volumes no sistema de armazenamento compartilham o mesmo espaço de cache; portanto, os volumes podem ter apenas um tamanho de bloco de cache.

Os aplicativos usam tamanhos de bloco diferentes, o que pode ter um impacto no desempenho de storage. Por padrão, o tamanho do bloco no System Manager é de 32 KiB, mas você pode definir o valor para 8, 16, 32 KiBs. Um tamanho menor é uma boa escolha para sistemas de arquivos ou aplicativos de banco de dados. Um tamanho maior é uma boa escolha para aplicativos que exigem grande transferência de dados, e/S sequencial ou alta largura de banda, como Multimídia.
