---
permalink: sm-settings/what-is-controller-cache.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, controller, cache, 
summary: 'O cache do controlador é um espaço de memória física que simplifica dois tipos de operações de e/S (entrada/saída): Entre os controladores e os hosts e entre os controladores e os discos.' 
---
= O que é cache de controladora?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O cache do controlador é um espaço de memória física que simplifica dois tipos de operações de e/S (entrada/saída): Entre os controladores e os hosts e entre os controladores e os discos.

Para transferências de dados de leitura e gravação, os hosts e controladores se comunicam por conexões de alta velocidade. No entanto, as comunicações do back-end do controlador para os discos são mais lentas, porque os discos são dispositivos relativamente lentos.

Quando o cache do controlador recebe dados, o controlador reconhece aos aplicativos host que agora está segurando os dados. Dessa forma, os aplicativos host não precisam esperar que a e/S seja gravada no disco. Em vez disso, os aplicativos podem continuar as operações. Os dados armazenados em cache também são facilmente acessíveis por aplicativos de servidor, eliminando a necessidade de leituras adicionais de disco para acessar os dados.

O cache da controladora afeta o desempenho geral do storage de várias maneiras:

* O cache funciona como um buffer, para que as transferências de dados de host e disco não precisem ser sincronizadas.
* Os dados para uma operação de leitura ou gravação do host podem estar em cache de uma operação anterior, o que elimina a necessidade de acessar o disco.
* Se o cache de gravação for usado, o host poderá enviar comandos de gravação subsequentes antes que os dados de uma operação de gravação anterior sejam gravados no disco.
* Se a pré-busca de cache estiver ativada, o acesso de leitura sequencial será otimizado. A pré-busca de cache torna uma operação de leitura mais provável de encontrar seus dados no cache, em vez de ler os dados do disco.


[CAUTION]
====
*Possível perda de dados* -- se você ativar a opção *armazenamento em cache sem baterias* e não tiver uma fonte de alimentação universal para proteção, você pode perder dados. Além disso, você pode perder dados se não tiver baterias do controlador e ativar a opção *armazenamento em cache sem baterias*.

====