---
permalink: sm-settings/what-is-host-connectivity-reporting.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host, connectivity, reporting, 
summary: Quando o relatório de conetividade do host é ativado, o storage array monitora continuamente a conexão entre os controladores e os hosts configurados e, em seguida, alerta você se a conexão for interrompida. 
---
= O que é o relatório de conetividade do host?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando o relatório de conetividade do host é ativado, o storage array monitora continuamente a conexão entre os controladores e os hosts configurados e, em seguida, alerta você se a conexão for interrompida.

Interrupções na conexão podem ocorrer se houver um cabo solto, danificado ou ausente, ou outro problema com o host. Nessas situações, o sistema pode abrir uma mensagem Recovery Guru:

* *Redundância de host perdida* -- abre se qualquer controlador não puder se comunicar com o host.
* *Host Type Incorrect* -- abre se o tipo de host for especificado incorretamente na matriz de armazenamento, o que pode resultar em problemas de failover.


Você pode querer desativar o relatório de conetividade do host em situações em que a reinicialização de um controlador pode levar mais tempo do que o tempo limite da conexão. Desativar esse recurso suprime as mensagens Gurus de recuperação.

[NOTE]
====
A desativação do relatório de conetividade do host também desativa o balanceamento automático de carga, que monitora e equilibra o uso de recursos do controlador. No entanto, se você reativar os relatórios de conetividade do host, o recurso de balanceamento de carga automático não será reativado automaticamente.

====