---
permalink: sm-settings/what-do-i-need-to-know-before-configuring-a-syslog-server.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configuring, syslog, server, 
summary: Você pode arquivar logs de auditoria em um servidor syslog externo. 
---
= O que eu preciso saber antes de configurar um servidor syslog?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode arquivar logs de auditoria em um servidor syslog externo.

Antes de configurar um servidor syslog, tenha em mente as seguintes diretrizes.

* Certifique-se de que conhece o endereço do servidor, o protocolo e o número da porta. O endereço do servidor pode ser um nome de domínio totalmente qualificado, um endereço IPv4 ou um endereço IPv6.
* Se o servidor usar um protocolo seguro (por exemplo, TLS), um certificado de autoridade de certificação (CA) deve estar disponível no sistema local. Os certificados CA identificam os proprietários de sites para conexões seguras entre servidores e clientes.
* Após a configuração, todos os novos logs de auditoria são enviados para o servidor syslog. Os registos anteriores não são transferidos.
* As configurações de política de substituição (disponíveis em *Exibir/Editar configurações*) não afetam a forma como os logs são gerenciados com uma configuração de servidor syslog.
* Os logs de auditoria seguem o formato de mensagens RFC 5424.

