---
permalink: sm-settings/what-do-i-need-to-know-about-certificate-revocation-checking.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, certificate, revocation, checking, 
summary: 'O System Manager permite verificar se há certificados revogados usando um servidor OCSP (Online Certificate Status Protocol), em vez de carregar listas de revogação de certificados (CRLs).' 
---
= O que eu preciso saber sobre a verificação de revogação de certificados?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Gerenciador de sistema do SANtricity permite que você verifique se há certificados revogados usando um servidor OCSP (protocolo de status de certificado on-line), em vez de carregar listas de revogação de certificados (CRLs).

Os certificados revogados não devem mais ser confiáveis. Um certificado pode ser revogado por vários motivos; por exemplo, se a Autoridade de Certificação (CA) emitiu incorretamente o certificado, uma chave privada foi comprometida ou a entidade identificada não aderiu aos requisitos da política.

Depois de estabelecer uma conexão com um servidor OCSP no Gerenciador de sistema, o storage array executa a verificação de revogação sempre que se coneta a um servidor AutoSupport, servidor de gerenciamento de chave externa (EKMS), servidor Lightweight Directory Access Protocol over SSL (LDAPS) ou a um servidor Syslog. O storage array tenta validar os certificados desses servidores para garantir que eles não foram revogados. O servidor então retorna um valor de "bom", "revogado" ou "desconhecido" para esse certificado. Se o certificado for revogado ou o array não puder entrar em Contato com o servidor OCSP, a conexão será recusada.

[NOTE]
====
Especificar um endereço de resposta OCSP no System Manager ou na interface de linha de comando (CLI) substitui o endereço OCSP encontrado no arquivo de certificado.

====