---
permalink: sm-settings/why-does-the-cannot-access-other-controller-dialog-appear.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, Cannot, Access, Other, Controller 
summary: 'Quando você executa determinadas operações relacionadas a certificados de CA (por exemplo, importando um certificado), você pode ver uma caixa de diálogo solicitando que você aceite um certificado autoassinado para o segundo controlador.' 
---
= Por que a caixa de diálogo não é possível acessar outro controlador aparece?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você executa determinadas operações relacionadas a certificados de CA (por exemplo, importando um certificado), você pode ver uma caixa de diálogo solicitando que você aceite um certificado autoassinado para o segundo controlador.

Em matrizes de armazenamento com dois controladores (configurações duplex), esta caixa de diálogo às vezes aparece se o Gerenciador de sistema SANtricity não puder se comunicar com o segundo controlador ou se o navegador não puder aceitar o certificado durante um determinado ponto de uma operação.

Se esta caixa de diálogo abrir, clique em *aceitar certificado autoassinado* para continuar. Se outra caixa de diálogo solicitar uma senha, digite a senha do administrador usada para acessar o System Manager.

Se esta caixa de diálogo aparecer novamente e não for possível concluir uma tarefa de certificado, tente um dos seguintes procedimentos:

* Use um tipo de navegador diferente para acessar esse controlador, aceitar o certificado e continuar.
* Acesse o segundo controlador comSystem Manager, aceite o certificado autoassinado e, em seguida, retorne ao primeiro controlador e continue.

