---
permalink: sm-settings/why-are-timestamps-inconsistent-between-the-array-and-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, timestamps, inconsistent, array, alerts, 
summary: 'Quando o storage array envia alertas, ele não corrige o fuso horário do servidor de destino ou host que recebe os alertas. Em vez disso, o storage array usa a hora local (GMT) para criar o carimbo de data/hora usado para o Registro de alerta. Como resultado, você pode ver inconsistências entre os carimbos de data/hora do storage array e o servidor ou host recebendo um alerta.' 
---
= Por que os carimbos de data/hora são inconsistentes entre a matriz e os alertas?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando o storage array envia alertas, ele não corrige o fuso horário do servidor de destino ou host que recebe os alertas. Em vez disso, o storage array usa a hora local (GMT) para criar o carimbo de data/hora usado para o Registro de alerta. Como resultado, você pode ver inconsistências entre os carimbos de data/hora do storage array e o servidor ou host recebendo um alerta.

Como o storage array não corrige o fuso horário ao enviar alertas, o carimbo de data/hora nos alertas é GMT-Relative, que tem um deslocamento de fuso horário de zero. Para calcular um carimbo de data/hora apropriado ao seu fuso horário local, você deve determinar o deslocamento da hora do GMT e, em seguida, adicionar ou subtrair esse valor dos carimbos de data/hora.
