---
permalink: sm-support/enable-or-disable-autosupport-features.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, disable, autosupport, 
summary: Você ativa o recurso AutoSupport e os recursos individuais do AutoSupport durante a configuração inicial ou pode ativá-los ou desativá-los posteriormente. 
---
= Ative ou desative os recursos do AutoSupport
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você ativa o recurso AutoSupport e os recursos individuais do AutoSupport durante a configuração inicial ou pode ativá-los ou desativá-los posteriormente.

.Antes de começar
Se você quiser ativar o AutoSupport OnDemand ou o Diagnóstico remoto, o método de entrega do AutoSupport deve ser definido como HTTPS.

.Sobre esta tarefa
Você pode desativar o recurso AutoSupport a qualquer momento, mas é altamente recomendável que o deixe habilitado. A ativação do recurso AutoSupport pode acelerar significativamente a determinação e a resolução de problemas caso ocorra um problema no storage array.

O recurso AutoSupport é composto por três recursos individuais que você ativa separadamente.

* *Basic AutoSupport* -- permite que sua matriz de armazenamento colete e envie dados automaticamente para o suporte técnico.
* *AutoSupport OnDemand* -- permite que o suporte técnico solicite a retransmissão de um despacho AutoSupport anterior quando necessário para solucionar um problema. Todas as transmissões são iniciadas a partir da matriz de armazenamento, não do servidor AutoSupport. A matriz de armazenamento verifica periodicamente com o servidor AutoSupport para determinar se existem solicitações de retransmissão pendentes e responde de acordo.
* *Diagnóstico remoto* -- permite que o suporte técnico solicite um novo e atualizado despacho do AutoSupport quando necessário para solucionar um problema. Todas as transmissões são iniciadas a partir da matriz de armazenamento, não do servidor AutoSupport. O storage array verifica periodicamente com o servidor AutoSupport para determinar se há novas solicitações pendentes e responde de acordo.


.Passos
. Selecione menu:suporte[Centro de suporte > AutoSupport].
. Selecione *Ativar/Desativar recursos do AutoSupport*.
. Marque as caixas de seleção ao lado dos recursos do AutoSupport que você deseja habilitar.
+
As funcionalidades dependem umas das outras, conforme indicado pela indentação dos itens na caixa de diálogo. Por exemplo, você deve habilitar o OnDemand do AutoSupport antes de ativar o Diagnóstico remoto.

. Clique em *Salvar*.
+
Se desativar o AutoSupport, é apresentada uma notificação na página inicial. Você pode ignorar a notificação clicando em *Ignorar*.


