---
permalink: sm-support/retrieve-trace-buffers.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, retrieve, trace, buffers 
summary: Você pode recuperar os buffers de rastreamento dos controladores e enviar o arquivo para suporte técnico para análise. 
---
= Recupere buffers de rastreamento
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode recuperar os buffers de rastreamento dos controladores e enviar o arquivo para suporte técnico para análise.

.Sobre esta tarefa
O firmware usa os buffers de rastreamento para gravar o processamento, especialmente as condições de exceção, que podem ser úteis para depuração. Você pode recuperar buffers de rastreamento sem interromper a operação do storage array e com efeito mínimo no desempenho.

[NOTE]
====
Execute esta operação somente quando instruído a fazê-lo pelo suporte técnico.

====
.Passos
. Selecione menu:guia Support [Support Center > Diagnostics] (suporte > Centro de suporte > Diagnóstico).
. Selecione *Retrieve Trace Buffers*.
. Marque a caixa de seleção ao lado de cada controlador para o qual você deseja recuperar buffers de rastreamento.
+
Pode selecionar um ou ambos os controladores. Se a mensagem de status do controlador à direita de uma caixa de seleção for Falha ou Desativado, a caixa de seleção será desativada.

. Clique em *Sim*.
+
O arquivo é salvo na pasta Downloads do navegador com o nome do `trace-buffers.7z`arquivo .

. Siga as instruções fornecidas pelo suporte técnico para enviar o arquivo para eles.

