---
permalink: sm-support/view-unreadable-sectors-log.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, unreadable, sectors, log 
summary: Você pode salvar o log de setores ilegíveis e enviar o arquivo para o suporte técnico para análise. 
---
= Visualizar o log de setores ilegíveis no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode salvar o log de setores ilegíveis e enviar o arquivo para o suporte técnico para análise.

.Sobre esta tarefa
O log de setores ilegíveis contém Registros detalhados de setores ilegíveis causados por unidades que relatam erros de Mídia irrecuperáveis. Setores ilegíveis são detetados durante e/S normais e durante operações de modificação, como reconstruções. Quando setores ilegíveis são detetados em um storage array, um alerta precisa de atenção aparece para o storage array. O Recovery Guru distingue qual condição de setor ilegível precisa de atenção. Quaisquer dados contidos em um setor ilegível não podem ser recuperados e devem ser considerados perdidos.

O log de setores ilegíveis pode armazenar até 1.000 setores ilegíveis. Quando o log de setores ilegíveis atinge 1.000 entradas, as seguintes condições se aplicam:

* Se forem detetados novos setores ilegíveis durante a reconstrução, a reconstrução falhará e não será registada qualquer entrada.
* Para novos setores ilegíveis detetados durante a e/S, a e/S falha e nenhuma entrada é registrada.
+
[NOTE]
====
Essas ações incluem gravações RAID 5 e gravações RAID 6 que teriam sido bem-sucedidas antes do estouro.

====


[CAUTION]
====
* Possível perda de dados * - recuperação de setores ilegíveis é um procedimento complicado que pode envolver vários métodos diferentes. Execute esta operação somente quando instruído a fazê-lo pelo suporte técnico.

====
.Passos
. Selecione menu:guia Support [Support Center > Diagnostics] (suporte > Centro de suporte > Diagnóstico).
. Selecione *Exibir/Limpar setores ilegíveis*.
. Para salvar o log de setores ilegíveis:
+
.. Na primeira coluna da tabela, você pode selecionar volumes individuais para os quais deseja salvar o log de setores ilegíveis (clique na caixa de seleção ao lado de cada volume) ou selecionar todos os volumes (marque a caixa de seleção no cabeçalho da tabela).
+
Para encontrar volumes específicos, você pode classificar qualquer uma das colunas ou digitar carateres na caixa *filtro*.

.. Clique em *Salvar*.


+
O arquivo é salvo na pasta Downloads do navegador com o nome `unreadable-sectors.txt`.

. Se o suporte técnico lhe der instruções para limpar o log de setores ilegíveis, execute as seguintes etapas:
+
.. Na primeira coluna da tabela, você pode selecionar volumes individuais para os quais deseja limpar o log de setores ilegíveis (clique na caixa de seleção ao lado de cada volume) ou selecionar todos os volumes (marque a caixa de seleção no cabeçalho da tabela).
.. Clique em *Clear* e confirme que deseja executar a operação.



