---
permalink: sm-support/what-do-the-autosupport-features-do.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, autosupport features, ASUP 
summary: O recurso AutoSupport é composto por três recursos individuais que você ativa separadamente. 
---
= O que fazem os recursos do AutoSupport?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O recurso AutoSupport é composto por três recursos individuais que você ativa separadamente.

* *Basic AutoSupport* -- permite que sua matriz de armazenamento colete e envie dados automaticamente para o suporte técnico.
* *AutoSupport OnDemand* -- permite que o suporte técnico solicite a retransmissão de um despacho AutoSupport anterior quando necessário para solucionar um problema. Todas as transmissões são iniciadas a partir da matriz de armazenamento, não do servidor AutoSupport. A matriz de armazenamento verifica periodicamente com o servidor AutoSupport para determinar se existem solicitações de retransmissão pendentes e responde de acordo.
* *Diagnóstico remoto* -- permite que o suporte técnico solicite um novo e atualizado despacho do AutoSupport quando necessário para solucionar um problema. Todas as transmissões são iniciadas a partir da matriz de armazenamento, não do servidor AutoSupport. O storage array verifica periodicamente com o servidor AutoSupport para determinar se há novas solicitações pendentes e responde de acordo.

