---
permalink: sm-support/what-does-unreadable-sectors-data-show-me.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, unreadable, sectors, 
summary: Você pode exibir dados detalhados sobre setores ilegíveis detetados nas unidades em seu storage array. 
---
= O que os dados de setores ilegíveis me mostram?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir dados detalhados sobre setores ilegíveis detetados nas unidades em seu storage array.

O log de setores ilegíveis mostra primeiro o setor ilegível mais recente. O log contém as seguintes informações sobre os volumes que contêm os setores ilegíveis. Os campos são selecionáveis.

[cols="25h,~"]
|===
| Campo | Descrição 


 a| 
Volume afetado
 a| 
Mostra a etiqueta do volume. Se um volume em falta contiver setores ilegíveis, o Identificador mundial será exibido para o volume em falta.



 a| 
Número de unidade lógica (LUN)
 a| 
Mostra o LUN para o volume. Se o volume não tiver um LUN, a caixa de diálogo mostra na.



 a| 
Atribuído a
 a| 
Mostra os hosts ou clusters de host que têm acesso ao volume. Se o volume não estiver acessível por um host, cluster de host ou mesmo um cluster padrão, a caixa de diálogo mostrará na.

|===
Para ver informações adicionais sobre os setores ilegíveis, clique no sinal de mais ao lado de um volume.

[cols="25h,~"]
|===
| Campo | Descrição 


 a| 
Data/hora
 a| 
Mostra a data e a hora em que o setor ilegível foi detetado.



 a| 
Endereço de bloco lógico de volume
 a| 
Mostra o endereço de bloco lógico (LBA) do volume.



 a| 
Localização da unidade
 a| 
Mostra o compartimento da unidade, a gaveta (se a prateleira da unidade tiver gavetas) e a localização do compartimento.



 a| 
Endereço do bloco lógico da unidade
 a| 
Mostra o LBA da unidade.



 a| 
Tipo de avaria
 a| 
Mostra um dos seguintes tipos de falha:

* *Physical* -- Um erro de Mídia física.
* *Logical* -- Um erro de leitura em outro lugar na faixa causando dados ilegíveis. Por exemplo, um setor ilegível devido a erros de Mídia em outro lugar do volume.
* *Inconsistente* -- dados de redundância inconsistentes.
* *Data Assurance* -- Um erro de garantia de dados.


|===