---
permalink: sm-support/what-do-i-need-to-know-before-upgrading-drive-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrading, drive, firmware 
summary: Antes de atualizar o firmware da sua unidade, esteja ciente desses itens. 
---
= O que eu preciso saber antes de atualizar o firmware da unidade?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de atualizar o firmware da sua unidade, esteja ciente desses itens.

* Como precaução, faça backup de seus dados usando backup de disco para disco, cópia de volume (para um grupo de volumes não afetado pela atualização de firmware planejada) ou um espelho remoto.
* Talvez você queira atualizar apenas algumas unidades para testar o comportamento do novo firmware para garantir que ele esteja funcionando corretamente. Se o novo firmware estiver funcionando corretamente, atualize as unidades restantes.
* Se você tiver alguma unidade com falha, corrija-a antes de iniciar a atualização de firmware.
* Se as unidades puderem fazer uma atualização off-line, interrompa a atividade de e/S para todos os volumes associados às unidades. Quando a atividade de e/S é interrompida, não podem ocorrer operações de configuração associadas a esses volumes.
* Não remova nenhuma unidade durante a atualização do firmware da unidade.
* Não faça alterações de configuração no storage de armazenamento durante a atualização do firmware da unidade.

