---
permalink: sm-support/what-do-i-need-to-know-before-upgrading-the-santricity-os-software.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrading, santricity, os, software 
summary: Antes de atualizar o software e o firmware do controlador, esteja ciente desses itens. 
---
= O que eu preciso saber antes de atualizar o software SANtricity os?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de atualizar o software e o firmware do controlador, tenha em atenção estes itens.

* Você leu o documento e o `readme.txt` arquivo e determinou que deseja fazer a atualização.
* Você sabe se deseja atualizar seu firmware IOM.
+
Normalmente, você deve atualizar todos os componentes ao mesmo tempo. No entanto, você pode decidir não atualizar o firmware IOM se não quiser atualizá-lo como parte da atualização do software da controladora SANtricity os ou se o suporte técnico tiver instruído a fazer o downgrade do firmware IOM (você só pode fazer o downgrade do firmware usando a interface de linha de comando).

* Você sabe se deseja atualizar o arquivo NVSRAM da controladora.
+
Normalmente, você deve atualizar todos os componentes ao mesmo tempo. No entanto, você pode decidir não atualizar o arquivo NVSRAM do controlador se o arquivo tiver sido corrigido ou for uma versão personalizada e você não quiser sobrescrevê-lo.

* Você sabe se deseja ativar agora ou mais tarde.
+
As razões para ativar mais tarde podem incluir:

+
** *Hora do dia* -- a ativação do software e do firmware pode demorar muito tempo, então você pode querer esperar até que as cargas de e/S sejam mais leves. Os controladores fazem failover durante a ativação, portanto, o desempenho pode ser menor do que o normal até a atualização ser concluída.
** * Tipo de pacote* -- você pode querer testar o novo software e firmware em uma matriz de armazenamento antes de atualizar os arquivos em outras matrizes de armazenamento.




Esses componentes fazem parte da atualização do software da controladora do SANtricity os:

* *Software de gerenciamento* -- System Manager é o software que gerencia o storage array.
* *Firmware do controlador* -- o firmware do controlador gerencia a e/S entre hosts e volumes.
* *Controller NVSRAM* -- Controller NVSRAM é um arquivo de controlador que especifica as configurações padrão para os controladores.
* *Firmware IOM* -- o firmware do módulo de e/S (IOM) gerencia a conexão entre uma controladora e um compartimento de unidades. Também monitoriza o estado dos componentes.
* *Software Supervisor* -- o software Supervisor é a máquina virtual em um controlador no qual o software é executado.


Como parte do processo de atualização, o driver multipath/failover e/ou o driver HBA do host também podem precisar ser atualizados para que o host possa interagir com os controladores corretamente.

[NOTE]
====
Para determinar se esse é o caso, consulte https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^] .

====
Se o storage array contiver apenas uma controladora ou você não tiver um driver multipath instalado, interrompa a atividade de e/S para o storage array para evitar erros de aplicativos. Se o seu storage array tiver duas controladoras e você tiver um driver multipath instalado, não será necessário interromper a atividade de e/S.


CAUTION: Não faça alterações no storage array enquanto a atualização ocorrer.
