---
permalink: um-certificates/access-management-terminology-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, access management, terminology 
summary: Saiba como os termos do Gerenciamento de Acesso se aplicam ao Gerenciador Unificado do SANtricity. 
---
= Saiba mais sobre a terminologia de gerenciamento de acesso do SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba como os termos do Gerenciamento de Acesso se aplicam ao Gerenciador Unificado do SANtricity.

[cols="25h,~"]
|===
| Prazo | Descrição 


 a| 
Ative Directory
 a| 
O ative Directory (AD) é um serviço de diretório da Microsoft que usa LDAP para redes de domínio do Windows.



 a| 
Encadernação
 a| 
As operações de vinculação são usadas para autenticar clientes no servidor de diretórios. A vinculação geralmente requer credenciais de conta e senha, mas alguns servidores permitem operações anônimas de vinculação.



 a| 
CA
 a| 
Uma autoridade de certificação (CA) é uma entidade confiável que emite documentos eletrônicos, chamados certificados digitais, para segurança na Internet. Esses certificados identificam proprietários de sites, o que permite conexões seguras entre clientes e servidores.



 a| 
Certificado
 a| 
Um certificado identifica o proprietário de um site para fins de segurança, o que impede que atacantes personificem o site. O certificado contém informações sobre o proprietário do site e a identidade da entidade confiável que certifica (assina) essas informações.



 a| 
LDAP
 a| 
O LDAP (Lightweight Directory Access Protocol) é um protocolo de aplicação para aceder e manter serviços de informação de diretório distribuído. Este protocolo permite que vários aplicativos e serviços diferentes se conetem ao servidor LDAP para validar usuários.



 a| 
RBAC
 a| 
O controle de acesso baseado em função (RBAC) é um método de regular o acesso a recursos de computador ou rede com base nas funções de usuários individuais. O Unified Manager inclui funções predefinidas.



 a| 
SAML
 a| 
Security Assertion Markup Language (SAML) é um padrão baseado em XML para autenticação e autorização entre duas entidades. O SAML permite a autenticação multifator, na qual os usuários devem fornecer dois ou mais itens para provar sua identidade (por exemplo, uma senha e uma impressão digital). O recurso SAML incorporado do storage array é compatível com SAML2,0 para afirmação, autenticação e autorização de identidade.



 a| 
SSO
 a| 
Logon único (SSO) é um serviço de autenticação que permite que um conjunto de credenciais de login acesse vários aplicativos.



 a| 
Proxy de serviços Web
 a| 
O Web Services Proxy, que fornece acesso através de mecanismos HTTPS padrão, permite que os administradores configurem serviços de gerenciamento para matrizes de armazenamento. O proxy pode ser instalado em hosts Windows ou Linux. A interface do Unified Manager está disponível com o Web Services Proxy.

|===