---
permalink: um-certificates/add-directory-server-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, add, directory, server 
summary: Para configurar a autenticação para o Gerenciamento de Acesso, você estabelece comunicações entre um servidor LDAP e o host que executa o Proxy de Serviços da Web para o Gerenciador Unificado do SANtricity. Em seguida, mapeia os grupos de utilizadores LDAP para as funções de utilizador local. 
---
= Adicionar servidor de diretório
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para configurar a autenticação para o Gerenciamento de Acesso, você estabelece comunicações entre um servidor LDAP e o host que executa o Proxy de Serviços da Web para o Gerenciador Unificado do SANtricity. Em seguida, mapeia os grupos de utilizadores LDAP para as funções de utilizador local.

.Antes de começar
* Você deve estar conetado com um perfil de usuário que inclua permissões de administrador de segurança. Caso contrário, as funções de Gerenciamento de Acesso não aparecem.
* Os grupos de usuários devem ser definidos em seu serviço de diretório.
* As credenciais do servidor LDAP devem estar disponíveis, incluindo o nome de domínio, o URL do servidor e, opcionalmente, o nome de usuário e a senha da conta BIND.
* Para servidores LDAPS que usam um protocolo seguro, a cadeia de certificados do servidor LDAP deve ser instalada na sua máquina local.


.Sobre esta tarefa
Adicionar um servidor de diretório é um processo de duas etapas. Primeiro você insere o nome de domínio e URL. Se o servidor usar um protocolo seguro, você também deve carregar um certificado de CA para autenticação se ele for assinado por uma autoridade de assinatura não padrão. Se tiver credenciais para uma conta BIND, também poderá introduzir o nome da conta de utilizador e a palavra-passe. Em seguida, você mapeia os grupos de usuários do servidor LDAP para funções de usuário locais.

.Passos
. Selecione *Gerenciamento de Acesso*.
. Na guia *Serviços de diretório*, selecione *Adicionar servidor de diretório*.
+
A caixa de diálogo Adicionar servidor de diretório é aberta.

. Na guia *Configurações do servidor*, insira as credenciais do servidor LDAP.
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Definição | Descrição 


 a| 
*Configurações de configuração*



 a| 
Domínio(s)
 a| 
Introduza o nome de domínio do servidor LDAP. Para vários domínios, insira os domínios em uma lista separada por vírgulas. O nome de domínio é usado no login (_username__domain_) para especificar em qual servidor de diretório se autenticar.



 a| 
URL do servidor
 a| 
Insira o URL para acessar o servidor LDAP na forma `ldap[s]://*host*:*port*` de .



 a| 
Carregar certificado (opcional)
 a| 

NOTE: Este campo aparece apenas se um protocolo LDAPS for especificado no campo URL do servidor acima.

Clique em *Procurar* e selecione um certificado de CA para carregar. Este é o certificado confiável ou cadeia de certificados usada para autenticar o servidor LDAP.



 a| 
Vincular conta (opcional)
 a| 
Insira uma conta de usuário somente leitura para consultas de pesquisa no servidor LDAP e para pesquisar nos grupos. Introduza o nome da conta num formato de tipo LDAP. Por exemplo, se o usuário bind for chamado de "bindacct", você poderá inserir um valor como `CN=bindacct,CN=Users,DC=cpoc,DC=local` .



 a| 
Vincular senha (opcional)
 a| 

NOTE: Este campo é exibido quando você insere uma conta BIND.

Introduza a palavra-passe para a conta vincular.



 a| 
Teste a conexão do servidor antes de adicionar
 a| 
Selecione esta caixa de verificação se pretender certificar-se de que o sistema pode comunicar com a configuração do servidor LDAP introduzida. O teste ocorre depois de clicar em *Add* na parte inferior da caixa de diálogo.

Se esta caixa de verificação estiver selecionada e o teste falhar, a configuração não será adicionada. Você deve resolver o erro ou desmarcar a caixa de seleção para ignorar o teste e adicionar a configuração.



 a| 
* Configurações de privilégio*



 a| 
Pesquisar DN base
 a| 
Introduza o contexto LDAP para procurar utilizadores, normalmente na forma `CN=Users, DC=cpoc, DC=local` de .



 a| 
Atributo de nome de usuário
 a| 
Insira o atributo que está vinculado ao ID do usuário para autenticação. Por exemplo `sAMAccountName`: .



 a| 
Atributo(s) de grupo
 a| 
Insira uma lista de atributos de grupo no usuário, que é usada para mapeamento de grupo para função. Por exemplo `memberOf, managedObjects`: .

|===
====
. Clique na guia *Mapeamento de função*.
. Atribua grupos LDAP às funções predefinidas. Um grupo pode ter várias funções atribuídas.
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Definição | Descrição 


 a| 
*Mapeamentos*



 a| 
DN do grupo
 a| 
Especifique o nome distinto do grupo (DN) para o grupo de usuários LDAP a ser mapeado. Expressões regulares são suportadas. Estes carateres especiais de expressão regular devem ser escapados com uma barra invertida () se eles não são parte de um padrão de expressão regular



 a| 
Funções
 a| 
Clique no campo e selecione uma das funções de usuário local a ser mapeada para o DN de grupo. Você deve selecionar individualmente cada função que deseja incluir para esse grupo. A função Monitor é necessária em combinação com as outras funções para fazer login no Gerenciador Unificado do SANtricity. As funções mapeadas incluem as seguintes permissões:

** *Storage admin* -- Acesso completo de leitura/gravação a objetos de armazenamento nas matrizes, mas sem acesso à configuração de segurança.
** *Security admin* -- Acesso à configuração de segurança em Gerenciamento de Acesso e Gerenciamento de certificados.
** *Support admin* -- Acesso a todos os recursos de hardware em matrizes de armazenamento, dados de falha e eventos mel. Sem acesso a objetos de armazenamento ou à configuração de segurança.
** *Monitor* -- Acesso somente leitura a todos os objetos de armazenamento, mas sem acesso à configuração de segurança.


|===
====
+

NOTE: A função Monitor é necessária para todos os usuários, incluindo o administrador.

. Se desejar, clique em *Adicionar outro mapeamento* para inserir mais mapeamentos de grupo para função.
. Quando terminar com os mapeamentos, clique em *Add*.
+
O sistema executa uma validação, certificando-se de que a matriz de armazenamento e o servidor LDAP possam se comunicar. Se for apresentada uma mensagem de erro, assinale as credenciais introduzidas na caixa de diálogo e volte a introduzir as informações, se necessário.


