---
permalink: um-certificates/change-local-user-passwords-settings-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, local, user, password, settings 
summary: Pode definir o comprimento mínimo necessário para todas as palavras-passe de utilizador locais novas ou atualizadas. Também pode permitir que os utilizadores locais acedam ao sistema sem introduzir uma palavra-passe. 
---
= Alterar as configurações de senha do usuário local no SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pode definir o comprimento mínimo necessário para todas as palavras-passe de utilizador locais novas ou atualizadas. Também pode permitir que os utilizadores locais acedam ao sistema sem introduzir uma palavra-passe.

.Antes de começar
Você deve estar logado como administrador local, o que inclui permissões de administrador raiz.

.Sobre esta tarefa
Tenha estas diretrizes em mente ao definir o comprimento mínimo para senhas de usuário local:

* A definição de alterações não afeta as palavras-passe de utilizador locais existentes.
* A definição de comprimento mínimo necessário para palavras-passe de utilizador local tem de ter entre 0 e 30 carateres.
* Quaisquer novas senhas de usuário local devem atender ou exceder a configuração de comprimento mínimo atual.
* Não defina um comprimento mínimo para a palavra-passe se pretender que os utilizadores locais acedam ao sistema sem introduzir uma palavra-passe.


.Passos
. Selecione *Gerenciamento de Acesso*.
. Selecione a guia *funções de usuário local*.
. Selecione *Exibir/Editar configurações*.
+
A caixa de diálogo Configurações de senha do usuário local é aberta.

. Execute um dos seguintes procedimentos:
+
** Para permitir que os usuários locais acessem o sistema _sem_ inserir uma senha, desmarque a caixa de seleção "exigir que todas as senhas de usuário local sejam pelo menos".
** Para definir um comprimento mínimo de palavra-passe para todas as palavras-passe de utilizador local, selecione a caixa de verificação "exigir que todas as palavras-passe de utilizador local sejam pelo menos" e, em seguida, utilize a caixa de seleção para definir o comprimento mínimo necessário para todas as palavras-passe de utilizador local.
+
Todas as novas senhas de usuário local devem atender ou exceder a configuração atual.



. Clique em *Salvar*.

