---
permalink: um-certificates/change-passwords-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, passwords 
summary: Você pode alterar as senhas de usuário para cada usuário no Gerenciamento de acesso. 
---
= Alterar senhas para perfis de usuários locais no SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar as senhas de usuário para cada usuário no Gerenciamento de acesso.

.Antes de começar
* Você deve estar logado como administrador local, o que inclui permissões de administrador raiz.
* Você deve saber a senha do administrador local.


.Sobre esta tarefa
Tenha em mente estas diretrizes ao escolher uma senha:

* Quaisquer novas senhas de usuário local devem atender ou exceder a configuração atual para uma senha mínima (em Configurações de visualização/edição).
* As senhas diferenciam maiúsculas de minúsculas.
* Os espaços de saída não são removidos das senhas quando são definidos. Tenha cuidado para incluir espaços se eles foram incluídos na senha.
* Para maior segurança, use pelo menos 15 carateres alfanuméricos e altere a senha com frequência.


.Passos
. Selecione *Gerenciamento de Acesso*.
. Selecione a guia *funções de usuário local*.
. Selecione um usuário na tabela.
+
O botão alterar senha fica disponível.

. Selecione *alterar palavra-passe*.
+
A caixa de diálogo alterar senha será exibida.

. Se não estiver definido um comprimento mínimo de palavra-passe para palavras-passe de utilizador local, pode selecionar a caixa de verificação para exigir que o utilizador introduza uma palavra-passe para aceder ao sistema.
. Introduza a nova palavra-passe para o utilizador selecionado nos dois campos.
. Introduza a palavra-passe do administrador local para confirmar esta operação e, em seguida, clique em *alterar*.


.Resultados
Se o usuário estiver conetado no momento, a alteração da senha fará com que a sessão ativa do usuário seja encerrada.
