---
permalink: um-certificates/faq-user-access-mgmt-um.html 
sidebar: sidebar 
keywords:  
summary: Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta. 
---
= Perguntas frequentes sobre gerenciamento de acesso de usuário para o SANtricity Unified Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta.



== Por que não consigo fazer login?

Se receber um erro ao tentar iniciar sessão, reveja estas possíveis causas.

Erros de login podem ocorrer por um destes motivos:

* Introduziu um nome de utilizador ou uma palavra-passe incorretos.
* Você não tem Privileges suficiente.
* Tentou iniciar sessão sem sucesso várias vezes, o que acionou o modo de bloqueio. Aguarde 10 minutos para voltar a iniciar sessão.
* A autenticação SAML está ativada. Atualize seu navegador para fazer login.




== O que eu preciso saber antes de adicionar um servidor de diretório?

Antes de adicionar um servidor de diretório no Gerenciamento de Acesso, você deve atender a certos requisitos.

* Os grupos de usuários devem ser definidos em seu serviço de diretório.
* As credenciais do servidor LDAP devem estar disponíveis, incluindo o nome de domínio, o URL do servidor e, opcionalmente, o nome de usuário e a senha da conta BIND.
* Para servidores LDAPS que usam um protocolo seguro, a cadeia de certificados do servidor LDAP deve ser instalada na sua máquina local.




== O que eu preciso saber sobre mapeamento para funções de storage array?

Antes de mapear grupos para funções, revise as diretrizes.

Os recursos RBAC (controle de acesso baseado em função) incluem as seguintes funções:

* *Storage admin* -- Acesso completo de leitura/gravação a objetos de armazenamento nas matrizes, mas sem acesso à configuração de segurança.
* *Security admin* -- Acesso à configuração de segurança em Gerenciamento de Acesso e Gerenciamento de certificados.
* *Support admin* -- Acesso a todos os recursos de hardware em matrizes de armazenamento, dados de falha e eventos mel. Sem acesso a objetos de armazenamento ou à configuração de segurança.
* *Monitor* -- Acesso somente leitura a todos os objetos de armazenamento, mas sem acesso à configuração de segurança.


[NOTE]
====
A função Monitor é necessária para todos os usuários, incluindo o administrador.

====
Se estiver a utilizar um servidor LDAP (Lightweight Directory Access Protocol) e Serviços de diretório, certifique-se de que:

* Um administrador definiu grupos de usuários no serviço de diretório.
* Você conhece os nomes de domínio de grupo para os grupos de usuários LDAP.




=== SAML

Se você estiver usando os recursos de Security Assertion Markup Language (SAML) incorporados ao storage array, verifique se:

* Um administrador do Provedor de identidade (IDP) configurou atributos de usuário e associação de grupo no sistema IDP.
* Você conhece os nomes dos membros do grupo.
* Você sabe o valor do atributo para o grupo a ser mapeado. Expressões regulares são suportadas. Esses carateres especiais de expressão regular devem ser escapados com uma barra invertida (`\`) se não fizerem parte de um padrão de expressão regular:
+
[listing]
----
\.[]{}()<>*+-=!?^$|
----
* A função Monitor é necessária para todos os usuários, incluindo o administrador. O Unified Manager não funcionará corretamente para nenhum usuário sem a função Monitor presente.




== O que eu preciso saber antes de configurar e ativar o SAML?

Antes de configurar e habilitar os recursos de Security Assertion Markup Language (SAML) para autenticação, certifique-se de atender aos requisitos a seguir e entender as restrições SAML.



=== Requisitos

Antes de começar, certifique-se de que:

* Um Provedor de identidade (IDP) está configurado na sua rede. Um IDP é um sistema externo usado para solicitar credenciais de um usuário e determinar se o usuário foi autenticado com êxito. Sua equipe de segurança é responsável por manter o IDP.
* Um administrador de IDP configurou atributos de usuário e grupos no sistema de IDP.
* Um administrador de IDP garantiu que o IDP suporta a capacidade de retornar um ID de nome na autenticação.
* Um administrador garantiu que o servidor IDP e o relógio do controlador são sincronizados (através de um servidor NTP ou ajustando as definições do relógio do controlador).
* Um arquivo de metadados IDP é baixado do sistema IDP e está disponível no sistema local usado para acessar o Unified Manager.
* Você sabe o endereço IP ou o nome de domínio do controlador na matriz de armazenamento.




=== Restrições

Além dos requisitos acima, certifique-se de que compreende as seguintes restrições:

* Uma vez que o SAML está ativado, você _não pode_ desabilitá-lo através da interface do usuário, nem pode editar as configurações de IDP. Se você precisar desativar ou editar a configuração SAML, entre em Contato com o suporte técnico para obter assistência. Recomendamos que você teste os logins SSO antes de ativar o SAML na etapa final de configuração. (O sistema também executa um teste de login SSO antes de ativar o SAML.)
* Se você desabilitar o SAML no futuro, o sistema restaurará automaticamente a configuração anterior (funções de usuário local e/ou Serviços de diretório).
* Se os Serviços de diretório estiverem configurados atualmente para autenticação de usuário, o SAML substituirá essa configuração.
* Quando o SAML é configurado, os seguintes clientes não podem acessar os recursos do storage array:
+
** Janela de gerenciamento empresarial (EMW)
** Interface de linha de comando (CLI)
** Clientes de Software Developer Kits (SDK)
** Clientes na banda
** Clientes API REST de Autenticação básica HTTP
** Faça login usando o endpoint padrão da API REST






== Quais são os usuários locais?

Os usuários locais são predefinidos no sistema e incluem permissões específicas.

Os usuários locais incluem:

* *Admin* -- Super administrador que tem acesso a todas as funções do sistema. Este usuário inclui todas as funções. A palavra-passe tem de ser definida no início de sessão pela primeira vez.
* *Storage* -- o administrador responsável por todo o provisionamento de armazenamento. Esse usuário inclui as seguintes funções: Administrador de storage, administrador de suporte e monitor. Esta conta é desativada até que uma palavra-passe seja definida.
* *Segurança* -- o usuário responsável pela configuração de segurança, incluindo Gerenciamento de Acesso e Gerenciamento de certificados. Este usuário inclui as seguintes funções: Admin de segurança e Monitor. Esta conta é desativada até que uma palavra-passe seja definida.
* *Suporte* -- o usuário responsável por recursos de hardware, dados de falha e atualizações de firmware. Este usuário inclui as seguintes funções: Admin de suporte e Monitor. Esta conta é desativada até que uma palavra-passe seja definida.
* *Monitor* -- Um usuário com acesso somente leitura ao sistema. Este utilizador inclui apenas a função Monitor. Esta conta é desativada até que uma palavra-passe seja definida.
* *rw* (leitura/gravação) -- este usuário inclui as seguintes funções: Administrador de armazenamento, administrador de suporte e monitor. Esta conta é desativada até que uma palavra-passe seja definida.
* *Ro* (somente leitura) -- este usuário inclui somente a função Monitor. Esta conta é desativada até que uma palavra-passe seja definida.

