---
permalink: um-certificates/view-local-user-roles-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, view, local, user, roles 
summary: 'Na guia funções do usuário local, você pode exibir os mapeamentos dos usuários para as funções padrão. Esses mapeamentos fazem parte do RBAC (controles de acesso baseados em função) aplicado no Proxy de serviços da Web para o Gerenciador Unificado do SANtricity.' 
---
= Ver funções de utilizador locais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Na guia funções do usuário local, você pode exibir os mapeamentos dos usuários para as funções padrão. Esses mapeamentos fazem parte do RBAC (controles de acesso baseados em função) aplicado no Proxy de serviços da Web para o Gerenciador Unificado do SANtricity.

.Antes de começar
Você deve estar conetado com um perfil de usuário que inclua permissões de administrador de segurança. Caso contrário, as funções de Gerenciamento de Acesso não aparecem.

.Sobre esta tarefa
Os usuários e mapeamentos não podem ser alterados. Apenas as senhas podem ser modificadas.

.Passos
. Selecione *Gerenciamento de Acesso*.
. Selecione a guia *funções de usuário local*.
+
Os usuários são mostrados na tabela:

+
** *Admin* -- Super administrador que tem acesso a todas as funções do sistema. Este usuário inclui todas as funções.
** *Storage* -- o administrador responsável por todo o provisionamento de armazenamento. Esse usuário inclui as seguintes funções: Administrador de storage, administrador de suporte e monitor.
** *Segurança* -- o usuário responsável pela configuração de segurança, incluindo Gerenciamento de Acesso e Gerenciamento de certificados. Este usuário inclui as seguintes funções: Admin de segurança e Monitor.
** *Suporte* -- o usuário responsável por recursos de hardware, dados de falha e atualizações de firmware. Este usuário inclui as seguintes funções: Admin de suporte e Monitor.
** *Monitor* -- Um usuário com acesso somente leitura ao sistema. Este utilizador inclui apenas a função Monitor.
** *rw* (leitura/gravação) -- este usuário inclui as seguintes funções: Administrador de armazenamento, administrador de suporte e monitor.
** *Ro* (somente leitura) -- este usuário inclui somente a função Monitor.



