---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, administrator, password, protection 
summary: Você deve configurar o SANtricity Unified Manager com uma senha de administrador para protegê-lo contra acesso não autorizado. 
---
= Defina a proteção de senha de administrador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar o SANtricity Unified Manager com uma senha de administrador para protegê-lo contra acesso não autorizado.



== Senha de administrador e perfis de usuário

Ao iniciar o Unified Manager pela primeira vez, você será solicitado a definir uma senha de administrador. Qualquer usuário que tenha a senha de administrador pode fazer alterações de configuração nos storages.

Além da senha de administrador, a interface do Unified Manager inclui perfis de usuário pré-configurados com uma ou mais funções mapeadas para eles. Para obter mais informações, link:../um-certificates/how-access-management-works-unified.html["Como o Gerenciamento de Acesso funciona"]consulte .

Os usuários e mapeamentos não podem ser alterados. Apenas as senhas podem ser modificadas. Para alterar senhas, consulte:

* link:change-admin-password-unified.html["Altere a senha de administrador"]
* link:../um-certificates/change-passwords-unified.html["Alterar senhas para perfis de usuário locais"]




== Tempos limite da sessão

O software solicita a senha apenas uma vez durante uma única sessão de gerenciamento. Uma sessão expira após 30 minutos de inatividade por padrão, e nesse momento, você deve digitar a senha novamente. Se outro utilizador aceder ao software a partir de outro cliente de gestão e alterar a palavra-passe enquanto a sessão estiver em curso, ser-lhe-á pedida uma palavra-passe da próxima vez que tentar uma operação de configuração ou uma operação de visualização.

Por razões de segurança, você pode tentar inserir uma senha apenas cinco vezes antes que o software entre em um estado de "bloqueio". Neste estado, o software rejeita tentativas subsequentes de senha. Tem de esperar 10 minutos para repor o estado "normal" antes de tentar introduzir novamente uma palavra-passe.

Você pode ajustar os tempos limite da sessão ou desativar completamente os tempos limite da sessão. Para obter mais informações, link:manage-session-timeouts-unified.html["Gerenciar tempos limite de sessão"]consulte .
