---
permalink: um-admin/change-admin-password-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, admin, password 
summary: Você pode alterar a senha de administrador usada para acessar o Gerenciador Unificado do SANtricity. 
---
= Alterar a senha do administrador no SANtricity Unified Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar a senha de administrador usada para acessar o Gerenciador Unificado do SANtricity.

.Antes de começar
* Você deve estar logado como administrador local, o que inclui permissões de administrador raiz.
* Você deve saber a senha de administrador atual.


.Sobre esta tarefa
Tenha em mente estas diretrizes ao escolher uma senha:

* As senhas diferenciam maiúsculas de minúsculas.
* Os espaços de saída não são removidos das senhas quando são definidos. Tenha cuidado para incluir espaços se eles foram incluídos na senha.
* Para maior segurança, use pelo menos 15 carateres alfanuméricos e altere a senha com frequência.


.Passos
. Selecione menu:Definições[Gestão de Acesso].
. Selecione a guia *funções de usuário local*.
. Selecione o usuário *admin* na tabela.
+
O botão alterar senha fica disponível.

. Selecione *alterar palavra-passe*.
+
A caixa de diálogo alterar senha será exibida.

. Se não estiver definido um comprimento mínimo de palavra-passe para palavras-passe de utilizador local, selecione a caixa de verificação para exigir que o utilizador introduza uma palavra-passe para aceder ao sistema.
. Introduza a nova palavra-passe nos dois campos.
. Introduza a palavra-passe do administrador local para confirmar esta operação e, em seguida, clique em *alterar*.

